load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Linq.AsyncEnumerable.Tests",
    srcs = [
        "AggregateAsyncTests.cs",
        "AggregateByTests.cs",
        "AllAsyncTests.cs",
        "AnyAsyncTests.cs",
        "AppendTests.cs",
        "AsyncEnumerableTests.cs",
        "AverageAsyncTests.cs",
        "CastTests.cs",
        "ChunkTests.cs",
        "ConcatTests.cs",
        "ContainsAsyncTests.cs",
        "CountAsyncTests.cs",
        "CountByTests.cs",
        "DefaultIfEmptyTests.cs",
        "DistinctByTests.cs",
        "DistinctTests.cs",
        "ElementAtAsyncTests.cs",
        "ElementAtOrDefaultAsyncTests.cs",
        "EmptyTests.cs",
        "ExceptByTests.cs",
        "ExceptTests.cs",
        "FirstAsyncTests.cs",
        "FirstOrDefaultAsyncTests.cs",
        "GroupByTests.cs",
        "GroupJoinTests.cs",
        "IndexTests.cs",
        "InfiniteSequenceTests.cs",
        "IntersectByTests.cs",
        "IntersectTests.cs",
        "JoinTests.cs",
        "LastAsyncTests.cs",
        "LastOrDefaultAsyncTests.cs",
        "LeftJoinTests.cs",
        "MaxAsyncTests.cs",
        "MaxByAsyncTests.cs",
        "MinAsyncTests.cs",
        "MinByAsyncTests.cs",
        "OfTypeTests.cs",
        "OrderByTests.cs",
        "PrependTests.cs",
        "QueryComprehesionTests.cs",
        "RangeTests.cs",
        "RepeatTests.cs",
        "ReverseTests.cs",
        "RightJoinTests.cs",
        "SelectManyTests.cs",
        "SelectTests.cs",
        "SequenceEqualAsyncTests.cs",
        "SequenceTests.cs",
        "ShuffleTests.cs",
        "SingleAsyncTests.cs",
        "SingleOrDefaultAsyncTests.cs",
        "SkipLastTests.cs",
        "SkipTests.cs",
        "SkipWhileTests.cs",
        "SumAsyncTests.cs",
        "TakeLastTests.cs",
        "TakeTests.cs",
        "TakeWhileTests.cs",
        "ToArrayAsyncTests.cs",
        "ToAsyncEnumerableTests.cs",
        "ToDictionaryAsyncTests.cs",
        "ToHashSetAsyncTests.cs",
        "ToListAsyncTests.cs",
        "ToLookupAsyncTests.cs",
        "UnionByTests.cs",
        "UnionTests.cs",
        "WhereTests.cs",
        "ZipTests.cs",
    ],
    deps = [
        "//src/libraries/System.Linq.AsyncEnumerable:ref_System.Linq.AsyncEnumerable",
        "//src/libraries/System.Threading.Channels:ref_System.Threading.Channels",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = ["CS1998"],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
