load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.CodeDom.Tests",
    srcs = [
        "Microsoft/CSharp/CSharpCodeProviderTests.cs",
        "Microsoft/VisualBasic/VBCodeProviderTests.cs",
        "System/CodeDom/CodeArgumentReferenceExpressionTests.cs",
        "System/CodeDom/CodeArrayCreateExpressionTests.cs",
        "System/CodeDom/CodeArrayIndexerExpressionTests.cs",
        "System/CodeDom/CodeAssignStatementTests.cs",
        "System/CodeDom/CodeAttachEventStatementTests.cs",
        "System/CodeDom/CodeAttributeArgumentCollectionTests.cs",
        "System/CodeDom/CodeAttributeArgumentTests.cs",
        "System/CodeDom/CodeAttributeDeclarationCollectionTests.cs",
        "System/CodeDom/CodeAttributeDeclarationTests.cs",
        "System/CodeDom/CodeBinaryOperatorExpressionTests.cs",
        "System/CodeDom/CodeCastExpressionTests.cs",
        "System/CodeDom/CodeCatchClauseCollectionTests.cs",
        "System/CodeDom/CodeCatchClauseTests.cs",
        "System/CodeDom/CodeChecksumPragmaTests.cs",
        "System/CodeDom/CodeCollectionTestBase.cs",
        "System/CodeDom/CodeCommentStatementCollectionTests.cs",
        "System/CodeDom/CodeCommentStatementTests.cs",
        "System/CodeDom/CodeCommentTests.cs",
        "System/CodeDom/CodeCompileUnitTests.cs",
        "System/CodeDom/CodeConditionStatementTests.cs",
        "System/CodeDom/CodeConstructorTests.cs",
        "System/CodeDom/CodeDefaultValueExpressionTests.cs",
        "System/CodeDom/CodeDelegateCreateExpressionTests.cs",
        "System/CodeDom/CodeDelegateInvokeExpressionTests.cs",
        "System/CodeDom/CodeDirectionExpressionTests.cs",
        "System/CodeDom/CodeDirectiveCollectionTests.cs",
        "System/CodeDom/CodeEventReferenceExpressionTests.cs",
        "System/CodeDom/CodeExpressionCollectionTests.cs",
        "System/CodeDom/CodeExpressionStatementTests.cs",
        "System/CodeDom/CodeFieldReferenceExpressionTests.cs",
        "System/CodeDom/CodeGotoStatement.cs",
        "System/CodeDom/CodeIndexerExpressionTests.cs",
        "System/CodeDom/CodeIterationStatementTests.cs",
        "System/CodeDom/CodeLabeledStatementTests.cs",
        "System/CodeDom/CodeLinePragmaTests.cs",
        "System/CodeDom/CodeMemberEventTests.cs",
        "System/CodeDom/CodeMemberFieldTests.cs",
        "System/CodeDom/CodeMemberMethodTests.cs",
        "System/CodeDom/CodeMemberPropertyTests.cs",
        "System/CodeDom/CodeMethodInvokeExpressionTests.cs",
        "System/CodeDom/CodeMethodReferenceExpressionTests.cs",
        "System/CodeDom/CodeMethodReturnStatementTests.cs",
        "System/CodeDom/CodeNamespaceCollectionTests.cs",
        "System/CodeDom/CodeNamespaceImportCollectionTests.cs",
        "System/CodeDom/CodeNamespaceImportTests.cs",
        "System/CodeDom/CodeNamespaceTests.cs",
        "System/CodeDom/CodeObjectCreateExpressionTests.cs",
        "System/CodeDom/CodeObjectTestBase.cs",
        "System/CodeDom/CodeParameterDeclarationExpressionCollectionTests.cs",
        "System/CodeDom/CodeParameterDeclarationExpressionTests.cs",
        "System/CodeDom/CodePrimitiveExpressionTests.cs",
        "System/CodeDom/CodePropertyReferenceExpressionTests.cs",
        "System/CodeDom/CodeRegionDirectiveTests.cs",
        "System/CodeDom/CodeRemoveEventStatementTests.cs",
        "System/CodeDom/CodeSnippetCompileUnitTests.cs",
        "System/CodeDom/CodeSnippetExpressionTests.cs",
        "System/CodeDom/CodeSnippetStatementTests.cs",
        "System/CodeDom/CodeSnippetTypeMemberTests.cs",
        "System/CodeDom/CodeStatementCollectionTests.cs",
        "System/CodeDom/CodeStatementTestBase.cs",
        "System/CodeDom/CodeThrowExceptionStatementTests.cs",
        "System/CodeDom/CodeTryCatchFinallyStatementTests.cs",
        "System/CodeDom/CodeTypeConstructorTests.cs",
        "System/CodeDom/CodeTypeDeclarationCollectionTests.cs",
        "System/CodeDom/CodeTypeDeclarationTests.cs",
        "System/CodeDom/CodeTypeDelegateTests.cs",
        "System/CodeDom/CodeTypeMemberCollectionTests.cs",
        "System/CodeDom/CodeTypeMemberTestBase.cs",
        "System/CodeDom/CodeTypeOfExpressionTests.cs",
        "System/CodeDom/CodeTypeParameterCollectionTests.cs",
        "System/CodeDom/CodeTypeParameterTests.cs",
        "System/CodeDom/CodeTypeReferenceCollectionTests.cs",
        "System/CodeDom/CodeTypeReferenceExpressionTests.cs",
        "System/CodeDom/CodeTypeReferenceTests.cs",
        "System/CodeDom/CodeVariableDeclarationStatementTests.cs",
        "System/CodeDom/CodeVariableReferenceExpressionTests.cs",
        "System/CodeDom/Compiler/CSharpCodeGenerationTests.cs",
        "System/CodeDom/Compiler/CSharpCodeGeneratorTests.cs",
        "System/CodeDom/Compiler/CodeCompilerTests.cs",
        "System/CodeDom/Compiler/CodeDomProviderTests.cs",
        "System/CodeDom/Compiler/CodeGenerationTests.cs",
        "System/CodeDom/Compiler/CodeGeneratorOptionsTests.cs",
        "System/CodeDom/Compiler/CodeGeneratorTests.cs",
        "System/CodeDom/Compiler/CodeValidatorTests.cs",
        "System/CodeDom/Compiler/CompilerErrorCollectionTests.cs",
        "System/CodeDom/Compiler/CompilerErrorTests.cs",
        "System/CodeDom/Compiler/CompilerInfoTests.cs",
        "System/CodeDom/Compiler/CompilerParametersTests.cs",
        "System/CodeDom/Compiler/CompilerResultsTests.cs",
        "System/CodeDom/Compiler/ExecutorTests.cs",
        "System/CodeDom/Compiler/VBCodeGenerationTests.cs",
        "System/CodeDom/TempFileCollectionTests.cs",
    ] + [
        "//src/libraries/Common/tests:System/Collections/IList.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/ICollection.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/TestBase.NonGeneric.cs",
        "//src/libraries/Common/tests:System/IO/TempFile.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs",
    ],
    deps = [
        "//src/libraries/System.CodeDom:ref_System.CodeDom",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = [
        "SYSLIB0011",
    ],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
