load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Runtime.InteropServices.Tests",
    srcs = [
        "AssemblyInfo.cs",
        "System/DllNotFoundExceptionTests.cs",
        "System/Runtime/CompilerServices/IDispatchConstantAttributeTests.cs",
        "System/Runtime/CompilerServices/IUnknownConstantAttributeTests.cs",
        "System/Runtime/InteropServices/ArrayWithOffsetTests.cs",
        "System/Runtime/InteropServices/AutomationProxyAttributeTests.cs",
        "System/Runtime/InteropServices/BStrWrapperTests.cs",
        "System/Runtime/InteropServices/BestFitMappingAttributeTests.cs",
        "System/Runtime/InteropServices/CLongTests.cs",
        "System/Runtime/InteropServices/CULongTests.cs",
        "System/Runtime/InteropServices/CallingConventionTests.cs",
        "System/Runtime/InteropServices/ClassInterfaceAttributeTests.cs",
        "System/Runtime/InteropServices/CoClassAttributeTests.cs",
        "System/Runtime/InteropServices/CollectionsMarshalTests.cs",
        "System/Runtime/InteropServices/ComAliasNameAttributeTests.cs",
        "System/Runtime/InteropServices/ComAwareEventInfoTests.cs",
        "System/Runtime/InteropServices/ComCompatibleVersionAttributeTests.cs",
        "System/Runtime/InteropServices/ComConversionLossAttributeTests.cs",
        "System/Runtime/InteropServices/ComDefaultInterfaceAttributeTests.cs",
        "System/Runtime/InteropServices/ComEventInterfaceAttributeTests.cs",
        "System/Runtime/InteropServices/ComEventsHelperTests.cs",
        "System/Runtime/InteropServices/ComRegisterFunctionAttributeTests.cs",
        "System/Runtime/InteropServices/ComSourceInterfacesAttributeTests.cs",
        "System/Runtime/InteropServices/ComUnregisterFunctionAttributeTests.cs",
        "System/Runtime/InteropServices/ComVariantMarshallerTests.cs",
        "System/Runtime/InteropServices/ComVariantTests.cs",
        "System/Runtime/InteropServices/ComVisibleAttributeTests.cs",
        "System/Runtime/InteropServices/CurrencyWrapperTests.cs",
        "System/Runtime/InteropServices/DefaultCharSetAttributeTests.cs",
        "System/Runtime/InteropServices/DefaultDllImportSearchPathsAttributeTests.cs",
        "System/Runtime/InteropServices/DefaultParameterValueAttributeTests.cs",
        "System/Runtime/InteropServices/DispIdAttributeTests.cs",
        "System/Runtime/InteropServices/DispatchWrapperTests.cs",
        "System/Runtime/InteropServices/DllImportAttributeTests.cs",
        "System/Runtime/InteropServices/ErrorWrapperTests.cs",
        "System/Runtime/InteropServices/FieldOffsetAttributeTests.cs",
        "System/Runtime/InteropServices/GCHandleTests.cs",
        "System/Runtime/InteropServices/GuidAttributeTests.cs",
        "System/Runtime/InteropServices/HandleCollectorTests.cs",
        "System/Runtime/InteropServices/HandleRefTests.cs",
        "System/Runtime/InteropServices/ImportedFromTypeLibAttributeTests.cs",
        "System/Runtime/InteropServices/InterfaceTypeAttributeTests.cs",
        "System/Runtime/InteropServices/LCIDConversionAttributeTests.cs",
        "System/Runtime/InteropServices/LibraryImportAttributeTests.cs",
        "System/Runtime/InteropServices/ManagedToNativeComInteropStubAttributeTests.cs",
        "System/Runtime/InteropServices/Marshal/AddRefTests.cs",
        "System/Runtime/InteropServices/Marshal/AllocHGlobalTests.cs",
        "System/Runtime/InteropServices/Marshal/BindToMonikerTests.cs",
        "System/Runtime/InteropServices/Marshal/ChangeWrapperHandleStrengthTests.cs",
        "System/Runtime/InteropServices/Marshal/Common/COMWrappersImpl.cs",
        "System/Runtime/InteropServices/Marshal/Common/CommonTypes.cs",
        "System/Runtime/InteropServices/Marshal/Common/Variant.cs",
        "System/Runtime/InteropServices/Marshal/Copy/ByteArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/Copy/CharArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/Copy/DoubleArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/Copy/Int16ArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/Copy/Int32ArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/Copy/Int64ArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/Copy/IntPtrArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/Copy/SingleArrayTests.cs",
        "System/Runtime/InteropServices/Marshal/CreateAggregatedObjectTests.cs",
        "System/Runtime/InteropServices/Marshal/CreateWrapperOfTypeTests.cs",
        "System/Runtime/InteropServices/Marshal/DestroyStructureTests.cs",
        "System/Runtime/InteropServices/Marshal/FinalReleaseComObjectTests.cs",
        "System/Runtime/InteropServices/Marshal/FreeBSTRTests.cs",
        "System/Runtime/InteropServices/Marshal/FreeCoTaskMemTests.cs",
        "System/Runtime/InteropServices/Marshal/FreeHGlobalTests.cs",
        "System/Runtime/InteropServices/Marshal/GenerateGuidForTypeTests.cs",
        "System/Runtime/InteropServices/Marshal/GenerateProgIdForTypeTests.cs",
        "System/Runtime/InteropServices/Marshal/GetComInterfaceForObjectTests.cs",
        "System/Runtime/InteropServices/Marshal/GetComObjectDataTests.cs",
        "System/Runtime/InteropServices/Marshal/GetDelegateForFunctionPointerTests.cs",
        "System/Runtime/InteropServices/Marshal/GetEndComSlotTests.cs",
        "System/Runtime/InteropServices/Marshal/GetExceptionCodeTests.cs",
        "System/Runtime/InteropServices/Marshal/GetExceptionForHRTests.cs",
        "System/Runtime/InteropServices/Marshal/GetExceptionPointersTests.cs",
        "System/Runtime/InteropServices/Marshal/GetFunctionPointerForDelegateTests.cs",
        "System/Runtime/InteropServices/Marshal/GetHINSTANCETests.cs",
        "System/Runtime/InteropServices/Marshal/GetHRForExceptionTests.cs",
        "System/Runtime/InteropServices/Marshal/GetIDispatchForObjectTests.cs",
        "System/Runtime/InteropServices/Marshal/GetIUnknownForObjectTests.cs",
        "System/Runtime/InteropServices/Marshal/GetObjectForIUnknownTests.cs",
        "System/Runtime/InteropServices/Marshal/GetStartComSlotTests.cs",
        "System/Runtime/InteropServices/Marshal/GetTypeFromCLSIDTests.cs",
        "System/Runtime/InteropServices/Marshal/GetTypeInfoNameTests.cs",
        "System/Runtime/InteropServices/Marshal/GetTypedObjectForIUnknownTests.cs",
        "System/Runtime/InteropServices/Marshal/GetUniqueObjectForIUnknownTests.cs",
        "System/Runtime/InteropServices/Marshal/InitHandleTests.cs",
        "System/Runtime/InteropServices/Marshal/IsComObjectTests.cs",
        "System/Runtime/InteropServices/Marshal/IsTypeVisibleFromComTests.cs",
        "System/Runtime/InteropServices/Marshal/LastErrorTests.cs",
        "System/Runtime/InteropServices/Marshal/OffsetOfTests.cs",
        "System/Runtime/InteropServices/Marshal/PInvokeErrorMessageTests.cs",
        "System/Runtime/InteropServices/Marshal/PrelinkAllTests.cs",
        "System/Runtime/InteropServices/Marshal/PrelinkTests.cs",
        "System/Runtime/InteropServices/Marshal/PtrToStringAnsiTests.cs",
        "System/Runtime/InteropServices/Marshal/PtrToStringAutoTests.cs",
        "System/Runtime/InteropServices/Marshal/PtrToStringBSTR.cs",
        "System/Runtime/InteropServices/Marshal/PtrToStringUTF8Tests.cs",
        "System/Runtime/InteropServices/Marshal/PtrToStringUniTests.cs",
        "System/Runtime/InteropServices/Marshal/PtrToStructureTests.cs",
        "System/Runtime/InteropServices/Marshal/QueryInterfaceTests.cs",
        "System/Runtime/InteropServices/Marshal/ReAllocCoTaskMemTests.cs",
        "System/Runtime/InteropServices/Marshal/ReAllocHGlobalTests.cs",
        "System/Runtime/InteropServices/Marshal/ReadWrite/ByteTests.cs",
        "System/Runtime/InteropServices/Marshal/ReadWrite/Int16Tests.cs",
        "System/Runtime/InteropServices/Marshal/ReadWrite/Int32Tests.cs",
        "System/Runtime/InteropServices/Marshal/ReadWrite/Int64Tests.cs",
        "System/Runtime/InteropServices/Marshal/ReadWrite/IntPtrTests.cs",
        "System/Runtime/InteropServices/Marshal/ReleaseComObjectTests.cs",
        "System/Runtime/InteropServices/Marshal/ReleaseTests.cs",
        "System/Runtime/InteropServices/Marshal/SecureStringToBSTRTests.cs",
        "System/Runtime/InteropServices/Marshal/SecureStringToCoTaskMemAnsiTests.cs",
        "System/Runtime/InteropServices/Marshal/SecureStringToCoTaskMemUnicodeTests.cs",
        "System/Runtime/InteropServices/Marshal/SecureStringToGlobalAllocAnsiTests.cs",
        "System/Runtime/InteropServices/Marshal/SecureStringToGlobalAllocUnicodeTests.cs",
        "System/Runtime/InteropServices/Marshal/SetComObjectDataTests.cs",
        "System/Runtime/InteropServices/Marshal/SizeOfTests.cs",
        "System/Runtime/InteropServices/Marshal/StringMarshalingTests.cs",
        "System/Runtime/InteropServices/Marshal/StringToBSTRTests.cs",
        "System/Runtime/InteropServices/Marshal/StringToCoTaskMemAnsiTests.cs",
        "System/Runtime/InteropServices/Marshal/StringToCoTaskMemAutoTests.cs",
        "System/Runtime/InteropServices/Marshal/StringToCoTaskMemUTF8Tests.cs",
        "System/Runtime/InteropServices/Marshal/StringToCoTaskMemUniTests.cs",
        "System/Runtime/InteropServices/Marshal/StringToHGlobalAnsiTests.cs",
        "System/Runtime/InteropServices/Marshal/StringToHGlobalAutoTests.cs",
        "System/Runtime/InteropServices/Marshal/StringToHGlobalUniTests.cs",
        "System/Runtime/InteropServices/Marshal/StructureToPtrTests.cs",
        "System/Runtime/InteropServices/Marshal/ThrowExceptionForHRTests.cs",
        "System/Runtime/InteropServices/Marshal/UnsafeAddrOfPinnedArrayElementTests.cs",
        "System/Runtime/InteropServices/Marshal/ZeroFreeCoTaskMemAnsiTests.cs",
        "System/Runtime/InteropServices/Marshal/ZeroFreeCoTaskMemUTF8Tests.cs",
        "System/Runtime/InteropServices/Marshal/ZeroFreeCoTaskMemUnicodeTests.cs",
        "System/Runtime/InteropServices/Marshal/ZeroFreeGlobalAllocAnsiTests.cs",
        "System/Runtime/InteropServices/Marshal/ZeroFreeGlobalAllocUnicodeTests.cs",
        "System/Runtime/InteropServices/MarshalAsAttributeTests.cs",
        "System/Runtime/InteropServices/NFloatTests.GenericMath.cs",
        "System/Runtime/InteropServices/NFloatTests.cs",
        "System/Runtime/InteropServices/NativeMemoryTests.cs",
        "System/Runtime/InteropServices/ObjectiveC/LibObjC.cs",
        "System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs",
        "System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs",
        "System/Runtime/InteropServices/PosixSignalContextTests.cs",
        "System/Runtime/InteropServices/PosixSignalRegistrationTests.Unix.cs",
        "System/Runtime/InteropServices/PosixSignalRegistrationTests.cs",
        "System/Runtime/InteropServices/PrimaryInteropAssemblyAttributeTests.cs",
        "System/Runtime/InteropServices/ProgIdAttributeTests.cs",
        "System/Runtime/InteropServices/RuntimeEnvironmentTests.cs",
        "System/Runtime/InteropServices/SafeBufferTests.cs",
        "System/Runtime/InteropServices/StandardOleMarshalObjectTests.cs",
        "System/Runtime/InteropServices/StructLayoutAttributeTests.cs",
        "System/Runtime/InteropServices/TypeIdentifierAttributeTests.cs",
        "System/Runtime/InteropServices/TypeLibFuncAttributeTests.cs",
        "System/Runtime/InteropServices/TypeLibImportClassAttributeTests.cs",
        "System/Runtime/InteropServices/TypeLibTypeAttributeTests.cs",
        "System/Runtime/InteropServices/TypeLibVarAttributeTests.cs",
        "System/Runtime/InteropServices/TypeLibVersionAttributeTests.cs",
        "System/Runtime/InteropServices/UnknownWrapperTests.cs",
        "System/Runtime/InteropServices/UnmanagedFunctionPointerAttributeTests.cs",
        "System/Runtime/InteropServices/VariantWrapperTests.cs",
    ] + [
        "//src/libraries/Common/tests:System/GenericMathHelpers.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
    ],
    deps = [
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:ComInterfaceGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    allow_unsafe_blocks = True,
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
