load("//:defs.bzl", "csharp_library")

csharp_library(
    name = "ILCompiler.Diagnostics",
    srcs = [
        "AssemblyInfo.cs",
        "ISymNGenWriter.cs",
        "MethodInfo.cs",
        "PdbWriter.cs",
        "PerfMapWriter.cs",
        "ReadyToRunDiagnosticsConstants.cs",
    ],
    defines = ["READYTORUN"],
    compiler_options = ["/unsafe"],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
    ],
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
)
