load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Diagnostics.PerformanceCounter.cs",
    "ref/System.Diagnostics.PerformanceCounter.netcoreapp.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Diagnostics.PerformanceCounter",
    srcs = [
        "ref/System.Diagnostics.PerformanceCounter.cs",
        "ref/System.Diagnostics.PerformanceCounter.netcoreapp.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Diagnostics.PerformanceCounter",
    skip_locals_init = False,
    pnse = True,
    pnse_message = "SR.PlatformNotSupported_PerfCounters",
    pnse_ref_srcs = [
        "ref/System.Diagnostics.PerformanceCounter.cs",
        "ref/System.Diagnostics.PerformanceCounter.netcoreapp.cs",
    ],
    multitarget = True,
    srcs = [],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
    resx_file = "src/Resources/Strings.resx",
    supported_os_platforms_short = ["windows"],
    nullable = "disable",
)

ref_impl_pair(
    name = "live_System.Diagnostics.PerformanceCounter",
    ref = ":ref_System.Diagnostics.PerformanceCounter",
    lib = ":impl_System.Diagnostics.PerformanceCounter",
    visibility = ["//visibility:public"],
)
