load("//src/libraries:defs.bzl", "live_csharp_library", "netcoreapp_ref_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.IO.Hashing",
    srcs = [
        "ref/System.IO.Hashing.cs",
        "ref/System.IO.Hashing.netcoreapp.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
    nowarn = ["CS0809"],
)

live_csharp_library(
    name = "live_System.IO.Hashing",
    srcs = [
        "src/System/IO/Hashing/Crc32.Arm.cs",
        "src/System/IO/Hashing/Crc32.Table.cs",
        "src/System/IO/Hashing/Crc32.Vectorized.cs",
        "src/System/IO/Hashing/Crc32.cs",
        "src/System/IO/Hashing/Crc64.Table.cs",
        "src/System/IO/Hashing/Crc64.Vectorized.cs",
        "src/System/IO/Hashing/Crc64.cs",
        "src/System/IO/Hashing/NonCryptographicHashAlgorithm.cs",
        "src/System/IO/Hashing/VectorHelper.cs",
        "src/System/IO/Hashing/XxHash128.cs",
        "src/System/IO/Hashing/XxHash3.cs",
        "src/System/IO/Hashing/XxHash32.State.cs",
        "src/System/IO/Hashing/XxHash32.cs",
        "src/System/IO/Hashing/XxHash64.State.cs",
        "src/System/IO/Hashing/XxHash64.cs",
        "src/System/IO/Hashing/XxHashShared.cs",
        "src/System/ThrowHelper.cs",
    ] + [
        "//src/libraries/Common:src/System/SR.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    nullable = "annotations",
    visibility = ["//visibility:public"],
)
