load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Reflection.Emit.ILGeneration.Tests",
    srcs = [
        "CustomAttributeBuilderTests.cs",
        "ILGenerator/DeclareLocalTests.cs",
        "ILGenerator/DefineLabelTests.cs",
        "ILGenerator/Emit1Tests.cs",
        "ILGenerator/Emit2Tests.cs",
        "ILGenerator/Emit3Tests.cs",
        "ILGenerator/Emit4Tests.cs",
        "ILGenerator/Emit5Tests.cs",
        "ILGenerator/EmitMethodInfo.cs",
        "ILGenerator/EmitWithModsTests.cs",
        "ILGenerator/EmitWriteLineTests.cs",
        "ILGenerator/ExceptionEmitTests.cs",
        "ILGenerator/ILOffsetTests.cs",
        "Label/LabelEquals.cs",
        "Label/LabelGetHashCode.cs",
        "Label/LabelId.cs",
        "LocalBuilder/LocalBuilderIsPinned.cs",
        "LocalBuilder/LocalBuilderLocalIndex.cs",
        "LocalBuilder/LocalBuilderLocalType.cs",
        "ParameterBuilder/PropertyTests.cs",
        "ParameterBuilder/SetConstant.cs",
        "ParameterBuilder/SetCustomAttributeTests.cs",
        "SignatureHelper/SignatureHelperAddArgument.cs",
        "SignatureHelper/SignatureHelperAddArguments.cs",
        "SignatureHelper/SignatureHelperDynamicCodeNotSupported.cs",
        "SignatureHelper/SignatureHelperEquals.cs",
        "SignatureHelper/SignatureHelperGetFieldSigHelper.cs",
        "SignatureHelper/SignatureHelperGetLocalVarSigHelper.cs",
        "SignatureHelper/SignatureHelperGetMethodSigHelper.cs",
        "SignatureHelper/SignatureHelperGetPropertySigHelper.cs",
        "SignatureHelper/SignatureHelperGetSignature.cs",
        "SignatureHelper/SignatureHelperToString.cs",
        "Utilities.cs",
    ],
    deps = [
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
