# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
parameters:
  PublishRidAgnosticPackagesFromPlatform: windows_x64
  publishingInfraVersion: 3
stages:
- stage: PrepareForPublish
  displayName: Prepare for Publish
  variables:
  - template: /eng/common/templates/variables/pool-providers.yml@self
  jobs:
  - template: /eng/pipelines/official/jobs/prepare-signed-artifacts.yml@self
    parameters:
      PublishRidAgnosticPackagesFromPlatform: ${{ parameters.PublishRidAgnosticPackagesFromPlatform }}
  - template: /eng/common/templates/job/publish-build-assets.yml@self
    parameters:
      publishUsingPipelines: true
      publishAssetsImmediately: true
      dependsOn: PrepareSignedArtifacts
      pool:
        name: $(DncEngInternalBuildPool)
        demands: ImageOverride -equals 1es-windows-2022
      symbolPublishingAdditionalParameters: '/p:PublishSpecialClrFiles=true'
- template: /eng/common/templates/post-build/post-build.yml@self
  parameters:
    publishingInfraVersion: ${{ parameters.publishingInfraVersion }}
    validateDependsOn:
    - PrepareForPublish
    enableSymbolValidation: false
    enableSigningValidation: false
    enableNugetValidation: false
    enableSourceLinkValidation: false
    publishAssetsImmediately: true
    SDLValidationParameters:
      enable: false
      artifactNames:
      - PackageArtifacts
      - BlobArtifacts
      params: >-
        -SourceToolsList @("policheck","credscan") -TsaInstanceURL "$(TsaInstanceURL)" -TsaProjectName "$(TsaProjectName)" -TsaNotificationEmail "$(TsaNotificationEmail)" -TsaCodebaseAdmin "$(TsaCodebaseAdmin)" -TsaBugAreaPath "$(TsaBugAreaPath)" -TsaIterationPath "$(TsaIterationPath)" -TsaRepositoryName "$(TsaRepositoryName)" -TsaCodebaseName "$(TsaCodebaseName)" -TsaPublish $True
    symbolPublishingAdditionalParameters: '/p:PublishSpecialClrFiles=true'
    publishInstallersAndChecksums: true