load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Memory.Tests",
    srcs = [
        "AllocationHelper.cs",
        "ArrayBufferWriter/ArrayBufferWriterTests.Byte.cs",
        "ArrayBufferWriter/ArrayBufferWriterTests.Char.cs",
        "ArrayBufferWriter/ArrayBufferWriterTests.String.cs",
        "ArrayBufferWriter/ArrayBufferWriterTests.T.cs",
        "Base64/Base64DecoderUnitTests.cs",
        "Base64/Base64EncoderUnitTests.cs",
        "Base64/Base64TestBase.cs",
        "Base64/Base64TestHelper.cs",
        "Base64/Base64ValidationUnitTests.cs",
        "Base64Url/Base64UrlDecoderUnitTests.cs",
        "Base64Url/Base64UrlEncoderUnitTests.cs",
        "Base64Url/Base64UrlUnicodeAPIsUnitTests.cs",
        "Base64Url/Base64UrlValidationUnitTests.cs",
        "Binary/BinaryReaderUnitTests.cs",
        "Binary/BinaryWriterUnitTests.cs",
        "Binary/ReverseEndiannessUnitTests.cs",
        "BuffersExtensions/BuffersExtensionsTests.cs",
        "EncodingExtensions/EncodingExtensionsTests.cs",
        "Memory/AsMemory.cs",
        "Memory/CopyTo.cs",
        "Memory/CtorArray.cs",
        "Memory/CtorArrayIntInt.cs",
        "Memory/CustomMemoryForTest.cs",
        "Memory/Empty.cs",
        "Memory/Equality.cs",
        "Memory/GetHashCode.cs",
        "Memory/ImplicitConversion.cs",
        "Memory/IndexAndRange.cs",
        "Memory/MemoryManager.cs",
        "Memory/Pin.cs",
        "Memory/Slice.cs",
        "Memory/Span.cs",
        "Memory/Strings.cs",
        "Memory/ToArray.cs",
        "Memory/ToString.cs",
        "Memory/Trim.cs",
        "MemoryMarshal/AsBytesReadOnlySpan.cs",
        "MemoryMarshal/AsBytesSpan.cs",
        "MemoryMarshal/AsMemory.cs",
        "MemoryMarshal/AsReadOnlyRef.cs",
        "MemoryMarshal/AsRef.cs",
        "MemoryMarshal/CastReadOnlySpan.cs",
        "MemoryMarshal/CastSpan.cs",
        "MemoryMarshal/CreateFromPinnedArray.cs",
        "MemoryMarshal/CreateReadOnlySpan.cs",
        "MemoryMarshal/CreateReadOnlySpanFromNullTerminated.cs",
        "MemoryMarshal/CreateSpan.cs",
        "MemoryMarshal/GetArrayDataReference.cs",
        "MemoryMarshal/GetReference.cs",
        "MemoryMarshal/ToEnumerable.cs",
        "MemoryMarshal/TryGetArray.cs",
        "MemoryMarshal/TryGetMemoryManager.cs",
        "MemoryMarshal/TryGetString.cs",
        "MemoryPool/MemoryPool.cs",
        "ParsersAndFormatters/Formatter/FormatterTestData.cs",
        "ParsersAndFormatters/Formatter/FormatterTests.cs",
        "ParsersAndFormatters/Formatter/RealFormatterTests.cs",
        "ParsersAndFormatters/Formatter/TestData.Formatter.cs",
        "ParsersAndFormatters/Formatter/ValidateFormatter.cs",
        "ParsersAndFormatters/Parser/ParserTestData.cs",
        "ParsersAndFormatters/Parser/ParserTests.2gbOverflow.cs",
        "ParsersAndFormatters/Parser/ParserTests.Negative.cs",
        "ParsersAndFormatters/Parser/ParserTests.cs",
        "ParsersAndFormatters/Parser/RealParserTests.cs",
        "ParsersAndFormatters/Parser/TestData.Parser.Boolean.cs",
        "ParsersAndFormatters/Parser/TestData.Parser.Date.cs",
        "ParsersAndFormatters/Parser/TestData.Parser.DecimalsAndFloats.cs",
        "ParsersAndFormatters/Parser/TestData.Parser.Guid.cs",
        "ParsersAndFormatters/Parser/TestData.Parser.Integer.cs",
        "ParsersAndFormatters/Parser/TestData.Parser.TimeSpan.cs",
        "ParsersAndFormatters/Parser/TestData.Parser.cs",
        "ParsersAndFormatters/Parser/ValidateParser.cs",
        "ParsersAndFormatters/PseudoDateTime.cs",
        "ParsersAndFormatters/StandardFormatTests.cs",
        "ParsersAndFormatters/SupportedFormats.cs",
        "ParsersAndFormatters/TestData.cs",
        "ParsersAndFormatters/TestUtils.cs",
        "ReadOnlyBuffer/BufferSegment.cs",
        "ReadOnlyBuffer/ReadOnlySequenceFactory.byte.cs",
        "ReadOnlyBuffer/ReadOnlySequenceFactory.char.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.Common.byte.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.Common.char.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.Common.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.Default.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.Empty.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.TryGet.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.byte.cs",
        "ReadOnlyBuffer/ReadOnlySequenceTests.char.cs",
        "ReadOnlyBuffer/SequencePosition.cs",
        "ReadOnlyMemory/CopyTo.cs",
        "ReadOnlyMemory/CtorArray.cs",
        "ReadOnlyMemory/CtorArrayIntInt.cs",
        "ReadOnlyMemory/Empty.cs",
        "ReadOnlyMemory/Equality.cs",
        "ReadOnlyMemory/GetHashCode.cs",
        "ReadOnlyMemory/ImplicitConversion.cs",
        "ReadOnlyMemory/Pin.cs",
        "ReadOnlyMemory/Slice.cs",
        "ReadOnlyMemory/Span.cs",
        "ReadOnlyMemory/Strings.cs",
        "ReadOnlyMemory/ToArray.cs",
        "ReadOnlyMemory/ToString.cs",
        "ReadOnlySpan/AsSpan.cs",
        "ReadOnlySpan/BinarySearch.cs",
        "ReadOnlySpan/CastUp.cs",
        "ReadOnlySpan/Comparers.cs",
        "ReadOnlySpan/Contains.T.cs",
        "ReadOnlySpan/Contains.byte.cs",
        "ReadOnlySpan/CopyTo.cs",
        "ReadOnlySpan/Count.T.cs",
        "ReadOnlySpan/Count.byte.cs",
        "ReadOnlySpan/CountAny.cs",
        "ReadOnlySpan/CtorArray.cs",
        "ReadOnlySpan/CtorArrayIntInt.cs",
        "ReadOnlySpan/CtorPointerInt.cs",
        "ReadOnlySpan/CtorRef.cs",
        "ReadOnlySpan/Empty.cs",
        "ReadOnlySpan/EndsWith.T.cs",
        "ReadOnlySpan/EndsWith.byte.cs",
        "ReadOnlySpan/EndsWith.long.cs",
        "ReadOnlySpan/Equality.cs",
        "ReadOnlySpan/Equals.cs",
        "ReadOnlySpan/GetEnumerator.cs",
        "ReadOnlySpan/GetHashCode.cs",
        "ReadOnlySpan/GetPinnableReference.cs",
        "ReadOnlySpan/ImplicitConversion.cs",
        "ReadOnlySpan/IndexOf.T.cs",
        "ReadOnlySpan/IndexOf.byte.cs",
        "ReadOnlySpan/IndexOfAny.T.cs",
        "ReadOnlySpan/IndexOfAny.byte.cs",
        "ReadOnlySpan/IndexOfAny.char.cs",
        "ReadOnlySpan/IndexOfSequence.T.cs",
        "ReadOnlySpan/IndexOfSequence.byte.cs",
        "ReadOnlySpan/LastIndexOf.T.cs",
        "ReadOnlySpan/LastIndexOf.byte.cs",
        "ReadOnlySpan/LastIndexOfAny.T.cs",
        "ReadOnlySpan/LastIndexOfAny.byte.cs",
        "ReadOnlySpan/LastIndexOfSequence.T.cs",
        "ReadOnlySpan/LastIndexOfSequence.byte.cs",
        "ReadOnlySpan/Overflow.cs",
        "ReadOnlySpan/Overlaps.cs",
        "ReadOnlySpan/SequenceCompareTo.T.cs",
        "ReadOnlySpan/SequenceCompareTo.bool.cs",
        "ReadOnlySpan/SequenceCompareTo.byte.cs",
        "ReadOnlySpan/SequenceCompareTo.int.cs",
        "ReadOnlySpan/SequenceCompareTo.long.cs",
        "ReadOnlySpan/SequenceEqual.T.cs",
        "ReadOnlySpan/SequenceEqual.byte.cs",
        "ReadOnlySpan/SequenceEqual.long.cs",
        "ReadOnlySpan/Slice.cs",
        "ReadOnlySpan/Split.T.cs",
        "ReadOnlySpan/StartsWith.T.cs",
        "ReadOnlySpan/StartsWith.byte.cs",
        "ReadOnlySpan/StartsWith.long.cs",
        "ReadOnlySpan/ToArray.cs",
        "ReadOnlySpan/ToString.cs",
        "ReadOnlySpan/ToUpperLower.cs",
        "SequenceReader/Advance.cs",
        "SequenceReader/BasicTests.cs",
        "SequenceReader/BinaryExtensions.cs",
        "SequenceReader/CopyTo.cs",
        "SequenceReader/IsNext.cs",
        "SequenceReader/OwnedArray.cs",
        "SequenceReader/ReadTo.cs",
        "SequenceReader/Rewind.cs",
        "SequenceReader/SequenceFactory.cs",
        "SequenceReader/SequenceSegment.cs",
        "SequenceReader/SkipDelimiter.cs",
        "SequenceReader/SpanLiteralExtensions.cs",
        "Span/AsSpan.cs",
        "Span/Clear.cs",
        "Span/CommonPrefixLength.T.cs",
        "Span/Contains.T.cs",
        "Span/CopyTo.cs",
        "Span/CtorArray.cs",
        "Span/CtorArrayIntInt.cs",
        "Span/CtorPointerInt.cs",
        "Span/CtorRef.cs",
        "Span/Empty.cs",
        "Span/EndsWith.T.cs",
        "Span/EndsWith.byte.cs",
        "Span/EndsWith.char.cs",
        "Span/EndsWith.long.cs",
        "Span/EnumerateLines.cs",
        "Span/EnumerateRunes.cs",
        "Span/Equality.cs",
        "Span/Fill.cs",
        "Span/GcReporting.cs",
        "Span/GetEnumerator.cs",
        "Span/GetHashCode.cs",
        "Span/GetPinnableReference.cs",
        "Span/ImplicitConversion.cs",
        "Span/IndexOf.T.cs",
        "Span/IndexOf.byte.cs",
        "Span/IndexOf.char.cs",
        "Span/IndexOfAny.AlgorithmicComplexity.cs",
        "Span/IndexOfAny.T.cs",
        "Span/IndexOfAny.byte.cs",
        "Span/IndexOfAny.char.cs",
        "Span/IndexOfAnyExcept.T.cs",
        "Span/IndexOfAnyInRange.cs",
        "Span/IndexOfSequence.T.cs",
        "Span/IndexOfSequence.byte.cs",
        "Span/IndexOfSequence.char.cs",
        "Span/Indexer.cs",
        "Span/LastIndexOf.T.cs",
        "Span/LastIndexOf.byte.cs",
        "Span/LastIndexOf.char.cs",
        "Span/LastIndexOfAny.T.cs",
        "Span/LastIndexOfAny.byte.cs",
        "Span/LastIndexOfSequence.T.cs",
        "Span/LastIndexOfSequence.byte.cs",
        "Span/LastIndexOfSequence.char.cs",
        "Span/Overflow.cs",
        "Span/Overlaps.cs",
        "Span/Reflection.cs",
        "Span/Replace.T.cs",
        "Span/ReplaceAny.cs",
        "Span/Reverse.cs",
        "Span/SearchValues.cs",
        "Span/SequenceCompareTo.T.cs",
        "Span/SequenceCompareTo.bool.cs",
        "Span/SequenceCompareTo.byte.cs",
        "Span/SequenceCompareTo.char.cs",
        "Span/SequenceCompareTo.int.cs",
        "Span/SequenceCompareTo.long.cs",
        "Span/SequenceEqual.T.cs",
        "Span/SequenceEqual.byte.cs",
        "Span/SequenceEqual.char.cs",
        "Span/SequenceEqual.long.cs",
        "Span/Slice.cs",
        "Span/Sort.cs",
        "Span/StartsWith.T.cs",
        "Span/StartsWith.byte.cs",
        "Span/StartsWith.char.cs",
        "Span/StartsWith.long.cs",
        "Span/StringSearchValues.cs",
        "Span/ToArray.cs",
        "Span/ToString.cs",
        "Span/TryWrite.cs",
        "TInt.cs",
        "TestException.cs",
        "TestHelpers.cs",
        "TestMemory.cs",
    ] + [
        "//src/libraries/Common/tests:System/Buffers/NativeMemoryManager.cs",
        "//src/libraries/Common/tests:System/RealFormatterTestsBase.cs",
        "//src/libraries/Common/tests:System/RealParserTestsBase.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
