
load("//:defs.bzl", "csharp_binary")

csharp_binary(
    name = "ResGen",
    srcs = [
        "FileStreamResource.cs",
        "FileUtilities.cs",
        "IResource.cs",
        "InputFormatNotSupportedException.cs",
        "LiveObjectResource.cs",
        "Logger.cs",
        "MSBuildResXReader.cs",
        "NameUtilities.cs",
        "ProcessResourceFiles.cs",
        "Program.cs",
        "StringResource.cs",
        "TypeConverterByteArrayResource.cs",
        "TypeConverterStringResource.cs",
    ],
    deps = [
        "@paket.main//system.resources.extensions",
    ],
    nowarn = [
        "CS1701",
        # MSBuild does not generate XML docs for tool projects
        "CS1572",
    ],
    nullable = "annotations",
    target_frameworks = [ "net10.0" ],
    visibility = ["//visibility:public"],
)