load("//:defs.bzl", "gen_resx_source")
load("//src/tests:live_test.bzl", "library_test")

gen_resx_source(
    name = "gen_resx",
    out = "SR.g.cs",
    assembly_name = "System.Formats.Tar",
    resx_file = "//src/libraries/System.Formats.Tar:src/Resources/Strings.resx",
)

library_test(
    name = "System.Formats.Tar.Tests",
    srcs = [
        "CompressedTar.Async.Tests.cs",
        "CompressedTar.Tests.cs",
        "SimulatedDataStream.cs",
        "TarEntry/GnuTarEntry.Conversion.Tests.cs",
        "TarEntry/GnuTarEntry.Tests.cs",
        "TarEntry/PaxTarEntry.Conversion.Tests.cs",
        "TarEntry/PaxTarEntry.Tests.cs",
        "TarEntry/TarEntry.Conversion.Tests.Base.cs",
        "TarEntry/TarEntry.ExtractToFile.Tests.Unix.cs",
        "TarEntry/TarEntry.ExtractToFile.Tests.cs",
        "TarEntry/TarEntry.ExtractToFileAsync.Tests.cs",
        "TarEntry/UstarTarEntry.Conversion.Tests.cs",
        "TarEntry/UstarTarEntry.Tests.cs",
        "TarEntry/V7TarEntry.Conversion.Tests.cs",
        "TarEntry/V7TarEntry.Tests.cs",
        "TarFile/TarFile.CreateFromDirectory.File.Roundtrip.cs",
        "TarFile/TarFile.CreateFromDirectory.File.Tests.cs",
        "TarFile/TarFile.CreateFromDirectory.Stream.Tests.cs",
        "TarFile/TarFile.CreateFromDirectoryAsync.File.Roundtrip.cs",
        "TarFile/TarFile.CreateFromDirectoryAsync.File.Tests.cs",
        "TarFile/TarFile.CreateFromDirectoryAsync.Stream.Tests.cs",
        "TarFile/TarFile.ExtractToDirectory.Base.cs",
        "TarFile/TarFile.ExtractToDirectory.File.Tests.Unix.cs",
        "TarFile/TarFile.ExtractToDirectory.File.Tests.cs",
        "TarFile/TarFile.ExtractToDirectory.Stream.Tests.cs",
        "TarFile/TarFile.ExtractToDirectoryAsync.File.Tests.Unix.cs",
        "TarFile/TarFile.ExtractToDirectoryAsync.File.Tests.cs",
        "TarFile/TarFile.ExtractToDirectoryAsync.Stream.Tests.cs",
        "TarReader/TarReader.Async.Tests.cs",
        "TarReader/TarReader.File.Async.Tests.Base.cs",
        "TarReader/TarReader.File.Async.Tests.cs",
        "TarReader/TarReader.File.GlobalExtendedAttributes.Async.Tests.cs",
        "TarReader/TarReader.File.GlobalExtendedAttributes.Tests.cs",
        "TarReader/TarReader.File.Tests.Base.cs",
        "TarReader/TarReader.File.Tests.cs",
        "TarReader/TarReader.GetNextEntry.Tests.cs",
        "TarReader/TarReader.GetNextEntryAsync.Tests.cs",
        "TarReader/TarReader.TarEntry.ExtractToFile.Tests.Unix.cs",
        "TarReader/TarReader.TarEntry.ExtractToFile.Tests.cs",
        "TarReader/TarReader.TarEntry.ExtractToFileAsync.Tests.Unix.cs",
        "TarReader/TarReader.TarEntry.ExtractToFileAsync.Tests.cs",
        "TarReader/TarReader.Tests.cs",
        "TarTestsBase.Gnu.cs",
        "TarTestsBase.Pax.cs",
        "TarTestsBase.Posix.cs",
        "TarTestsBase.Ustar.cs",
        "TarTestsBase.V7.cs",
        "TarTestsBase.cs",
        "TarWriter/TarWriter.Async.Tests.cs",
        "TarWriter/TarWriter.File.Base.Unix.cs",
        "TarWriter/TarWriter.Tests.cs",
        "TarWriter/TarWriter.WriteEntry.Base.cs",
        "TarWriter/TarWriter.WriteEntry.Entry.Gnu.Tests.cs",
        "TarWriter/TarWriter.WriteEntry.Entry.Pax.Tests.cs",
        "TarWriter/TarWriter.WriteEntry.Entry.Roundtrip.Tests.cs",
        "TarWriter/TarWriter.WriteEntry.Entry.Ustar.Tests.cs",
        "TarWriter/TarWriter.WriteEntry.Entry.V7.Tests.cs",
        "TarWriter/TarWriter.WriteEntry.File.Tests.Unix.cs",
        "TarWriter/TarWriter.WriteEntry.File.Tests.cs",
        "TarWriter/TarWriter.WriteEntry.Tests.cs",
        "TarWriter/TarWriter.WriteEntryAsync.Entry.Gnu.Tests.cs",
        "TarWriter/TarWriter.WriteEntryAsync.Entry.Pax.Tests.cs",
        "TarWriter/TarWriter.WriteEntryAsync.Entry.Roundtrip.Tests.cs",
        "TarWriter/TarWriter.WriteEntryAsync.Entry.Ustar.Tests.cs",
        "TarWriter/TarWriter.WriteEntryAsync.Entry.V7.Tests.cs",
        "TarWriter/TarWriter.WriteEntryAsync.File.Tests.Unix.cs",
        "TarWriter/TarWriter.WriteEntryAsync.File.Tests.cs",
        "TarWriter/TarWriter.WriteEntryAsync.Tests.cs",
    ] + [
        # Common test files
        "//src/libraries/Common/tests:System/IO/TempDirectory.cs",
        "//src/libraries/Common/tests:System/IO/ReparsePointUtilities.cs",
        "//src/libraries/Common/tests:System/IO/WrappedStream.cs",
        # Common source files
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        # Unix interop files
        "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.IOErrors.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.DeviceFiles.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetEUid.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetPwUid.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetGroupName.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Link.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MkFifo.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Stat.cs",
        # SR resource generation
        "//src/libraries/Common:src/System/SR.cs",
        ":gen_resx",
    ],
    deps = [
        "//src/libraries/System.Formats.Tar:ref_System.Formats.Tar",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
        "//src/libraries/System.IO.Compression:ref_System.IO.Compression",
        "//src/libraries/System.IO.Compression.ZipFile:ref_System.IO.Compression.ZipFile",
        "//src/libraries/System.Net.Requests:ref_System.Net.Requests",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    allow_unsafe_blocks = True,
    data = ["@paket.main//system.formats.tar.testdata:content_files"],
    size = "large",
)
