load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

exports_files([
    "ref/System.Data.Common.cs",
    "ref/System.Data.Common.Forwards.cs",
    "ref/System.Data.Common.manual.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Data.Common",
    srcs = [
        "ref/System.Data.Common.cs",
        "ref/System.Data.Common.Forwards.cs",
        "ref/System.Data.Common.manual.cs",
    ],
    nowarn = ["CS0618"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Transactions.Local:ref_System.Transactions.Local",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Data.Common",
    analyzers = [
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    srcs = [
        "src/System/Data/AcceptRejectRule.cs",
        "src/System/Data/AggregateType.cs",
        "src/System/Data/BaseCollection.cs",
        "src/System/Data/CatalogLocation.cs",
        "src/System/Data/ColumnTypeConverter.cs",
        "src/System/Data/CommandBehavior.cs",
        "src/System/Data/CommandType.cs",
        "src/System/Data/Common/AdapterUtil.Common.cs",
        "src/System/Data/Common/BigIntegerStorage.cs",
        "src/System/Data/Common/BooleanStorage.cs",
        "src/System/Data/Common/ByteStorage.cs",
        "src/System/Data/Common/CharStorage.cs",
        "src/System/Data/Common/DBCommandBuilder.cs",
        "src/System/Data/Common/DBSchemaRow.cs",
        "src/System/Data/Common/DBSchemaTable.cs",
        "src/System/Data/Common/DataAdapter.cs",
        "src/System/Data/Common/DataColumnMapping.cs",
        "src/System/Data/Common/DataColumnMappingCollection.cs",
        "src/System/Data/Common/DataCommonEventSource.cs",
        "src/System/Data/Common/DataRecordInternal.cs",
        "src/System/Data/Common/DataStorage.cs",
        "src/System/Data/Common/DataTableMapping.cs",
        "src/System/Data/Common/DataTableMappingCollection.cs",
        "src/System/Data/Common/DateTimeOffsetStorage.cs",
        "src/System/Data/Common/DateTimeStorage.cs",
        "src/System/Data/Common/DbBatch.cs",
        "src/System/Data/Common/DbBatchCommand.cs",
        "src/System/Data/Common/DbBatchCommandCollection.cs",
        "src/System/Data/Common/DbColumn.cs",
        "src/System/Data/Common/DbCommand.cs",
        "src/System/Data/Common/DbConnection.cs",
        "src/System/Data/Common/DbConnectionOptions.cs",
        "src/System/Data/Common/DbConnectionStringBuilder.cs",
        "src/System/Data/Common/DbConnectionStringBuilderDescriptor.cs",
        "src/System/Data/Common/DbConnectionStringCommon.cs",
        "src/System/Data/Common/DbDataAdapter.cs",
        "src/System/Data/Common/DbDataReader.cs",
        "src/System/Data/Common/DbDataReaderExtensions.cs",
        "src/System/Data/Common/DbDataRecord.cs",
        "src/System/Data/Common/DbDataSource.cs",
        "src/System/Data/Common/DbDataSourceEnumerator.cs",
        "src/System/Data/Common/DbEnumerator.cs",
        "src/System/Data/Common/DbException.cs",
        "src/System/Data/Common/DbMetaDataCollectionNames.cs",
        "src/System/Data/Common/DbMetaDataColumnNames.cs",
        "src/System/Data/Common/DbParameter.cs",
        "src/System/Data/Common/DbParameterCollection.cs",
        "src/System/Data/Common/DbProviderFactories.cs",
        "src/System/Data/Common/DbProviderFactory.cs",
        "src/System/Data/Common/DbProviderSpecificTypePropertyAttribute.cs",
        "src/System/Data/Common/DbTransaction.cs",
        "src/System/Data/Common/DecimalStorage.cs",
        "src/System/Data/Common/DefaultDataSource.cs",
        "src/System/Data/Common/DoubleStorage.cs",
        "src/System/Data/Common/FieldNameLookup.cs",
        "src/System/Data/Common/Groupbybehavior.cs",
        "src/System/Data/Common/IDbColumnSchemaGenerator.cs",
        "src/System/Data/Common/Int16Storage.cs",
        "src/System/Data/Common/Int32Storage.cs",
        "src/System/Data/Common/Int64Storage.cs",
        "src/System/Data/Common/ObjectStorage.cs",
        "src/System/Data/Common/RowUpdatedEventArgs.cs",
        "src/System/Data/Common/RowUpdatingEventArgs.cs",
        "src/System/Data/Common/SByteStorage.cs",
        "src/System/Data/Common/SQLConvert.cs",
        "src/System/Data/Common/SQLTypes/SQLBinaryStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLByteStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLBytesStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLCharsStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLDateTimeStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLDecimalStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLDoubleStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLGuidStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLInt16Storage.cs",
        "src/System/Data/Common/SQLTypes/SQLInt32Storage.cs",
        "src/System/Data/Common/SQLTypes/SQLInt64Storage.cs",
        "src/System/Data/Common/SQLTypes/SQLMoneyStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLSingleStorage.cs",
        "src/System/Data/Common/SQLTypes/SQLStringStorage.cs",
        "src/System/Data/Common/SQLTypes/SQlBooleanStorage.cs",
        "src/System/Data/Common/SchemaTableColumn.cs",
        "src/System/Data/Common/SchemaTableOptionalColumn.cs",
        "src/System/Data/Common/SingleStorage.cs",
        "src/System/Data/Common/SqlUDTStorage.cs",
        "src/System/Data/Common/StringStorage.cs",
        "src/System/Data/Common/SupportedJoinOperators.cs",
        "src/System/Data/Common/TimeSpanStorage.cs",
        "src/System/Data/Common/UInt16Storage.cs",
        "src/System/Data/Common/UInt32Storage.cs",
        "src/System/Data/Common/UInt64Storage.cs",
        "src/System/Data/Common/identifiercase.cs",
        "src/System/Data/ConflictOptions.cs",
        "src/System/Data/ConnectionState.cs",
        "src/System/Data/Constraint.cs",
        "src/System/Data/ConstraintCollection.cs",
        "src/System/Data/ConstraintConverter.cs",
        "src/System/Data/ConstraintEnumerator.cs",
        "src/System/Data/DBConcurrencyException.cs",
        "src/System/Data/DataColumn.cs",
        "src/System/Data/DataColumnChangeEvent.cs",
        "src/System/Data/DataColumnChangeEventHandler.cs",
        "src/System/Data/DataColumnCollection.cs",
        "src/System/Data/DataColumnPropertyDescriptor.cs",
        "src/System/Data/DataError.cs",
        "src/System/Data/DataException.cs",
        "src/System/Data/DataKey.cs",
        "src/System/Data/DataReaderExtensions.cs",
        "src/System/Data/DataRelation.cs",
        "src/System/Data/DataRelationCollection.cs",
        "src/System/Data/DataRelationPropertyDescriptor.cs",
        "src/System/Data/DataRow.cs",
        "src/System/Data/DataRowAction.cs",
        "src/System/Data/DataRowChangeEvent.cs",
        "src/System/Data/DataRowChangeEventHandler.cs",
        "src/System/Data/DataRowCollection.cs",
        "src/System/Data/DataRowComparer.cs",
        "src/System/Data/DataRowCreatedEventHandler.cs",
        "src/System/Data/DataRowExtensions.cs",
        "src/System/Data/DataRowState.cs",
        "src/System/Data/DataRowVersion.cs",
        "src/System/Data/DataRowView.cs",
        "src/System/Data/DataSerializationFormat.cs",
        "src/System/Data/DataSet.cs",
        "src/System/Data/DataSetDateTime.cs",
        "src/System/Data/DataSetUtil.cs",
        "src/System/Data/DataSysAttribute.cs",
        "src/System/Data/DataTable.cs",
        "src/System/Data/DataTableClearEvent.cs",
        "src/System/Data/DataTableClearEventHandler.cs",
        "src/System/Data/DataTableCollection.cs",
        "src/System/Data/DataTableExtensions.cs",
        "src/System/Data/DataTableNewRowEvent.cs",
        "src/System/Data/DataTableNewRowEventHandler.cs",
        "src/System/Data/DataTablePropertyDescriptor.cs",
        "src/System/Data/DataTableReader.cs",
        "src/System/Data/DataTableReaderListener.cs",
        "src/System/Data/DataTableTypeConverter.cs",
        "src/System/Data/DataView.cs",
        "src/System/Data/DataViewListener.cs",
        "src/System/Data/DataViewManager.cs",
        "src/System/Data/DataViewManagerListItemTypeDescriptor.cs",
        "src/System/Data/DataViewRowState.cs",
        "src/System/Data/DataViewSetting.cs",
        "src/System/Data/DataViewSettingCollection.cs",
        "src/System/Data/DbType.cs",
        "src/System/Data/DefaultValueTypeConverter.cs",
        "src/System/Data/EnumerableRowCollection.cs",
        "src/System/Data/EnumerableRowCollectionExtensions.cs",
        "src/System/Data/FillErrorEventArgs.cs",
        "src/System/Data/FillErrorEventHandler.cs",
        "src/System/Data/Filter/AggregateNode.cs",
        "src/System/Data/Filter/BinaryNode.cs",
        "src/System/Data/Filter/ConstNode.cs",
        "src/System/Data/Filter/DataExpression.cs",
        "src/System/Data/Filter/ExpressionNode.cs",
        "src/System/Data/Filter/ExpressionParser.cs",
        "src/System/Data/Filter/FilterException.cs",
        "src/System/Data/Filter/FunctionNode.cs",
        "src/System/Data/Filter/IFilter.cs",
        "src/System/Data/Filter/LookupNode.cs",
        "src/System/Data/Filter/NameNode.cs",
        "src/System/Data/Filter/Operators.cs",
        "src/System/Data/Filter/UnaryNode.cs",
        "src/System/Data/Filter/ZeroOpNode.cs",
        "src/System/Data/ForeignKeyConstraint.cs",
        "src/System/Data/IColumnMapping.cs",
        "src/System/Data/IColumnMappingCollection.cs",
        "src/System/Data/IDataAdapter.cs",
        "src/System/Data/IDataParameter.cs",
        "src/System/Data/IDataParameterCollection.cs",
        "src/System/Data/IDataReader.cs",
        "src/System/Data/IDataRecord.cs",
        "src/System/Data/IDbCommand.cs",
        "src/System/Data/IDbConnection.cs",
        "src/System/Data/IDbDataAdapter.cs",
        "src/System/Data/IDbDataParameter.cs",
        "src/System/Data/IDbTransaction.cs",
        "src/System/Data/ITableMapping.cs",
        "src/System/Data/ITableMappingCollection.cs",
        "src/System/Data/IsolationLevel.cs",
        "src/System/Data/KeyRestrictionBehavior.cs",
        "src/System/Data/LinqDataView.cs",
        "src/System/Data/LoadOption.cs",
        "src/System/Data/LocalAppContextSwitches.cs",
        "src/System/Data/MappingType.cs",
        "src/System/Data/MergeFailedEvent.cs",
        "src/System/Data/MergeFailedEventHandler.cs",
        "src/System/Data/Merger.cs",
        "src/System/Data/MissingMappingAction.cs",
        "src/System/Data/MissingSchemaAction.cs",
        "src/System/Data/OrderedEnumerableRowCollection.cs",
        "src/System/Data/ParameterDirection.cs",
        "src/System/Data/PrimaryKeyTypeConverter.cs",
        "src/System/Data/PropertyCollection.cs",
        "src/System/Data/ProviderBase/DataReaderContainer.cs",
        "src/System/Data/ProviderBase/SchemaMapping.cs",
        "src/System/Data/Range.cs",
        "src/System/Data/RbTree.cs",
        "src/System/Data/RecordManager.cs",
        "src/System/Data/RelatedView.cs",
        "src/System/Data/RelationshipConverter.cs",
        "src/System/Data/Rule.cs",
        "src/System/Data/SQLTypes/INullable.cs",
        "src/System/Data/SQLTypes/SQLBinary.cs",
        "src/System/Data/SQLTypes/SQLBoolean.cs",
        "src/System/Data/SQLTypes/SQLByte.cs",
        "src/System/Data/SQLTypes/SQLBytes.cs",
        "src/System/Data/SQLTypes/SQLChars.cs",
        "src/System/Data/SQLTypes/SQLDateTime.cs",
        "src/System/Data/SQLTypes/SQLDecimal.cs",
        "src/System/Data/SQLTypes/SQLDouble.cs",
        "src/System/Data/SQLTypes/SQLGuid.cs",
        "src/System/Data/SQLTypes/SQLInt16.cs",
        "src/System/Data/SQLTypes/SQLInt32.cs",
        "src/System/Data/SQLTypes/SQLInt64.cs",
        "src/System/Data/SQLTypes/SQLMoney.cs",
        "src/System/Data/SQLTypes/SQLSingle.cs",
        "src/System/Data/SQLTypes/SQLString.cs",
        "src/System/Data/SQLTypes/SQLUtility.cs",
        "src/System/Data/SQLTypes/SqlXml.cs",
        "src/System/Data/SchemaSerializationMode.cs",
        "src/System/Data/SchemaType.cs",
        "src/System/Data/Select.cs",
        "src/System/Data/Selection.cs",
        "src/System/Data/SimpleType.cs",
        "src/System/Data/SortExpressionBuilder.cs",
        "src/System/Data/SqlDbType.cs",
        "src/System/Data/StateChangeEvent.cs",
        "src/System/Data/StateChangeEventHandler.cs",
        "src/System/Data/StatementCompletedEventArgs.cs",
        "src/System/Data/StatementCompletedEventHandler.cs",
        "src/System/Data/StatementType.cs",
        "src/System/Data/StrongTypingException.cs",
        "src/System/Data/TypeLimiter.cs",
        "src/System/Data/TypedTableBase.cs",
        "src/System/Data/TypedTableBaseExtensions.cs",
        "src/System/Data/UniqueConstraint.cs",
        "src/System/Data/UpdateRowSource.cs",
        "src/System/Data/XDRSchema.cs",
        "src/System/Data/XMLDiffLoader.cs",
        "src/System/Data/XMLSchema.cs",
        "src/System/Data/XmlDataLoader.cs",
        "src/System/Data/XmlKeywords.cs",
        "src/System/Data/XmlReadMode.cs",
        "src/System/Data/XmlToDatasetMap.cs",
        "src/System/Data/XmlWriteMode.cs",
        "src/System/Data/updatestatus.cs",
        "src/System/Data/xmlsaver.cs",
        "src/System/HResults.cs",
        "src/System/Xml/BaseTreeIterator.cs",
        "src/System/Xml/DataDocumentXPathNavigator.cs",
        "src/System/Xml/DataPointer.cs",
        "src/System/Xml/DataSetMappper.cs",
        "src/System/Xml/IXmlDataVirtualNode.cs",
        "src/System/Xml/RegionIterator.cs",
        "src/System/Xml/TreeIterator.cs",
        "src/System/Xml/XPathNodePointer.cs",
        "src/System/Xml/XmlBoundElement.cs",
        "src/System/Xml/XmlDataDocument.cs",
        "src/System/Xml/XmlDataImplementation.cs",
    ] + [
        "src/System.Data.Common.TypeForwards.cs",
        # CommonPath files
        "//src/libraries/Common:src/System/LocalAppContextSwitches.Common.cs",
        "//src/libraries/Common:src/System/Data/Common/AdapterUtil.cs",
        "//src/libraries/Common:src/System/Data/Common/DbConnectionOptions.Common.cs",
        "//src/libraries/Common:src/System/Data/Common/DbConnectionPoolKey.cs",
        "//src/libraries/Common:src/System/Data/Common/MultipartIdentifier.cs",
        "//src/libraries/Common:src/System/Data/Common/NameValuePair.cs",
        "//src/libraries/Common:src/System/Data/Common/SQLResource.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    nowarn = ["SYSLIB0038"],
    deps = [
        "//src/libraries:ref_System.Private.CoreLib",
        "//src/libraries:impl_System.Runtime",
        "//src/libraries/System.Collections:impl_System.Collections",
        "//src/libraries/System.Collections.Concurrent:impl_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Linq.Expressions:ref_System.Linq.Expressions",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries:impl_System.Private.Uri",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Transactions.Local:ref_System.Transactions.Local",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XmlSerializer:ref_System.Xml.XmlSerializer",
    ],
)
