<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <CLRTestPriority>0</CLRTestPriority>
    <IlcManagedGC>true</IlcManagedGC>
    <CLRTestTargetUnsupported Condition="'$(TargetsAppleMobile)' == 'true'">true</CLRTestTargetUnsupported>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <ReferenceXUnitWrapperGenerator>false</ReferenceXUnitWrapperGenerator>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ManagedGCBgcAllocationStress.cs" />
    <CLRTestEnvironmentVariable Include="DOTNET_gcConcurrent" Value="1" />
    <CLRTestEnvironmentVariable Include="DOTNET_GCRegionRange" Value="10000000" />
  </ItemGroup>
</Project>
