load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Security.Cryptography.Pkcs.Tests",
    srcs = [
        "AlgorithmIdentifierTest.cs",
        "CertLoader.Settings.cs",
        "CertLoader.cs",
        "Certificates.cs",
        "CmsRecipientCollectionTests.cs",
        "CryptographicAttributeObjectCollectionTests.cs",
        "EnvelopedCms/CertificateTests.cs",
        "EnvelopedCms/ContentEncryptionAlgorithmTests.cs",
        "EnvelopedCms/DecryptTests.KeyPersistence.cs",
        "EnvelopedCms/DecryptTests.cs",
        "EnvelopedCms/DecryptTestsRsaPaddingModeTests.cs",
        "EnvelopedCms/DecryptTestsUsingCertWithPrivateKey.cs",
        "EnvelopedCms/DecryptTestsUsingExplicitPrivateKey.cs",
        "EnvelopedCms/EdgeCasesTests.cs",
        "EnvelopedCms/GeneralTests.cs",
        "EnvelopedCms/KeyAgreeRecipientInfoTests.cs",
        "EnvelopedCms/KeyTransRecipientInfoRsaOaepCertTests.cs",
        "EnvelopedCms/KeyTransRecipientInfoRsaPaddingModeTests.cs",
        "EnvelopedCms/KeyTransRecipientInfoTests.cs",
        "EnvelopedCms/StateTests.cs",
        "EnvelopedCms/SubjectIdentifierTests.cs",
        "EnvelopedCms/UnprotectedAttributeTests.cs",
        "ImportedCollection.cs",
        "Oids.cs",
        "Pkcs12/CertBagTests.cs",
        "Pkcs12/CustomBagTypeTests.cs",
        "Pkcs12/KeyBagTests.cs",
        "Pkcs12/Pkcs12BuilderTests.cs",
        "Pkcs12/Pkcs12Documents.cs",
        "Pkcs12/Pkcs12InfoTests.cs",
        "Pkcs12/Pkcs12SafeBagTests.cs",
        "Pkcs12/Pkcs12SafeContentsTests.cs",
        "Pkcs12/Pkcs9LocalKeyIdTests.cs",
        "Pkcs12/SafeContentsBagTests.cs",
        "Pkcs12/SecretBagTests.cs",
        "Pkcs12/ShroudedKeyBagTests.cs",
        "Pkcs12/SimpleRead.cs",
        "Pkcs12/WriteToWindows.cs",
        "Pkcs8PrivateKeyInfoTests.cs",
        "Pkcs9AttributeTests.cs",
        "PrivateKeyHelpers.cs",
        "RecipientInfoCollectionTests.cs",
        "Rfc3161/TimestampRequestTests.cs",
        "Rfc3161/TimestampTokenInfoTests.cs",
        "Rfc3161/TimestampTokenTestData.cs",
        "Rfc3161/TimestampTokenTests.cs",
        "SignatureSupport.cs",
        "SignedCms/CmsSignerTests.cs",
        "SignedCms/CounterSigningDerOrder.cs",
        "SignedCms/SignedCmsTests.cs",
        "SignedCms/SignedCmsTests.netcoreapp.cs",
        "SignedCms/SignedCmsWholeDocumentTests.cs",
        "SignedCms/SignedDocuments.cs",
        "SignedCms/SignerInfoTests.cs",
        "SignedCms/SignerInfoTests.netcoreapp.cs",
    ] + [
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.Ietf.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.GeneratedCertificates.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/ByteUtils.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/PlatformSupport.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/CngKeyWrapper.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/SignatureSupport.cs",
    ],
    deps = [
        "//src/libraries/System.Security.Cryptography.Pkcs:ref_System.Security.Cryptography.Pkcs",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Formats.Asn1:ref_System.Formats.Asn1",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    nowarn = ["SYSLIB0057", "SYSLIB5006"],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
