load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.Configuration.Ini.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.Configuration.Ini",
    srcs = [
        "ref/Microsoft.Extensions.Configuration.Ini.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.Configuration:ref_Microsoft.Extensions.Configuration",
        "//src/libraries/Microsoft.Extensions.Configuration.Abstractions:ref_Microsoft.Extensions.Configuration.Abstractions",
        "//src/libraries/Microsoft.Extensions.Configuration.FileExtensions:ref_Microsoft.Extensions.Configuration.FileExtensions",
        "//src/libraries/Microsoft.Extensions.FileProviders.Abstractions:ref_Microsoft.Extensions.FileProviders.Abstractions",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_Microsoft.Extensions.Configuration.Ini",
    skip_locals_init = False,
    multitarget = True,
    srcs = glob(["src/**/*.cs"]),
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.Configuration:ref_Microsoft.Extensions.Configuration",
        "//src/libraries/Microsoft.Extensions.Configuration.Abstractions:ref_Microsoft.Extensions.Configuration.Abstractions",
        "//src/libraries/Microsoft.Extensions.Configuration.FileExtensions:ref_Microsoft.Extensions.Configuration.FileExtensions",
        "//src/libraries/Microsoft.Extensions.FileProviders.Abstractions:ref_Microsoft.Extensions.FileProviders.Abstractions",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Memory:ref_System.Memory",
    ],
    resx_file = "src/Resources/Strings.resx",
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.Configuration.Ini",
    ref = ":ref_Microsoft.Extensions.Configuration.Ini",
    lib = ":impl_Microsoft.Extensions.Configuration.Ini",
    visibility = ["//visibility:public"],
)
