load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Text.RegularExpressions.Tests",
    srcs = [
        "AttRegexTests.cs",
        "CaptureCollectionTests.cs",
        "CaptureCollectionTests2.cs",
        "CustomDerivedRegexScenarioTest.cs",
        "GeneratedRegexAttributeTests.cs",
        "GroupCollectionReadOnlyDictionaryTests.cs",
        "GroupCollectionTests.cs",
        "GroupCollectionTests2.cs",
        "MatchCollectionTests.cs",
        "MatchCollectionTests2.cs",
        "MonoRegexTests.cs",
        "PrecompiledRegexScenarioTest.cs",
        "Regex.Cache.Tests.cs",
        "Regex.CompileToAssembly.Tests.cs",
        "Regex.Count.Tests.cs",
        "Regex.Ctor.Tests.cs",
        "Regex.EnumerateMatches.Tests.cs",
        "Regex.EnumerateSplits.Tests.cs",
        "Regex.EscapeUnescape.Tests.cs",
        "Regex.GetGroupNames.Tests.cs",
        "Regex.Groups.Tests.cs",
        "Regex.KnownPattern.Tests.cs",
        "Regex.Match.Tests.cs",
        "Regex.MultipleMatches.Tests.cs",
        "Regex.Replace.Tests.cs",
        "Regex.Split.Tests.cs",
        "Regex.Tests.Common.cs",
        "Regex.UnicodeChar.Tests.cs",
        "RegexAssert.netcoreapp.cs",
        "RegexCharacterSetTests.cs",
        "RegexCompilationInfoTests.cs",
        "RegexCultureTests.cs",
        "RegexExperiment.cs",
        "RegexGeneratorHelper.netcoreapp.cs",
        "RegexGeneratorOutputTests.cs",
        "RegexGeneratorParserTests.cs",
        "RegexGroupNameTests.cs",
        "RegexIgnoreCaseTests.cs",
        "RegexMatchTimeoutExceptionTests.cs",
        "RegexParserTests.cs",
        "RegexParserTests.netcoreapp.cs",
        "RegexPcreTests.cs",
        "RegexRunnerTests.cs",
        "RegexRustTests.cs",
    ] + [
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
    ],
    deps = [
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Metadata:ref_System.Reflection.Metadata",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Text.Json:ref_System.Text.Json",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/shims/System.Reflection:impl_System.Reflection",
        "//src/libraries/shims/System.Threading.Tasks:impl_System.Threading.Tasks",
        "//src/libraries/shims/netstandard:impl_netstandard",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.codeanalysis.common",
        "@paket.main//microsoft.codeanalysis.csharp",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    analyzers = [
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
    data = ["@paket.main//system.text.regularexpressions.testdata:content_files"],
    nowarn = ["xUnit2008", "SYSLIB0036", "SYSLIB1045", "SYSLIB0011", "SYSLIB0050", "SYSLIB0051"],
    size = "large",
)
