load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Linq.Parallel.Tests",
    srcs = [
        "Combinatorial/CancellationParallelQueryCombinationTests.cs",
        "Combinatorial/FailingParallelQueryCombinationTests.cs",
        "Combinatorial/ParallelQueryCombinationTests.cs",
        "Combinatorial/SourcesAndOperators.cs",
        "Combinatorial/UnorderedParallelQueryCombinationTests.cs",
        "DegreeOfParallelismTests.cs",
        "EtwTests.cs",
        "ExchangeTests.cs",
        "Helpers/AssertThrows.cs",
        "Helpers/Comparers.cs",
        "Helpers/CustomPartitioners.cs",
        "Helpers/DeliberateTestException.cs",
        "Helpers/Enumerables.cs",
        "Helpers/Functions.cs",
        "Helpers/IntegerRangeSet.cs",
        "Helpers/KeyValuePair.cs",
        "Helpers/Labeled.cs",
        "Helpers/Sources.cs",
        "Helpers/UnorderedSources.cs",
        "ParallelEnumerableTests.cs",
        "PlinqModesTests.cs",
        "QueryOperators/AggregateTests.cs",
        "QueryOperators/AllTests.cs",
        "QueryOperators/AnyTests.cs",
        "QueryOperators/AsEnumerableTests.cs",
        "QueryOperators/AsSequentialTests.cs",
        "QueryOperators/AverageTests.cs",
        "QueryOperators/CastTests.cs",
        "QueryOperators/ConcatTests.cs",
        "QueryOperators/ContainsTests.cs",
        "QueryOperators/CountLongCountTests.cs",
        "QueryOperators/DefaultIfEmptyTests.cs",
        "QueryOperators/DistinctTests.cs",
        "QueryOperators/ElementAtElementAtOrDefaultTests.cs",
        "QueryOperators/ExceptTests.cs",
        "QueryOperators/FirstFirstOrDefaultTests.cs",
        "QueryOperators/ForAllTests.cs",
        "QueryOperators/GetEnumeratorTests.cs",
        "QueryOperators/GroupByTests.cs",
        "QueryOperators/GroupJoinTests.cs",
        "QueryOperators/IntersectTests.cs",
        "QueryOperators/JoinTests.cs",
        "QueryOperators/LastLastOrDefaultTests.cs",
        "QueryOperators/MaxTests.cs",
        "QueryOperators/MinTests.cs",
        "QueryOperators/OfTypeTests.cs",
        "QueryOperators/OrderByThenByTests.cs",
        "QueryOperators/ReverseTests.cs",
        "QueryOperators/SelectSelectManyTests.cs",
        "QueryOperators/SequenceEqualTests.cs",
        "QueryOperators/SingleSingleOrDefaultTests.cs",
        "QueryOperators/SkipSkipWhileTests.cs",
        "QueryOperators/SumTests.cs",
        "QueryOperators/TakeTakeWhileTests.cs",
        "QueryOperators/ToArrayTests.cs",
        "QueryOperators/ToDictionaryTests.cs",
        "QueryOperators/ToListTests.cs",
        "QueryOperators/ToLookupTests.cs",
        "QueryOperators/UnionTests.cs",
        "QueryOperators/WhereTests.cs",
        "QueryOperators/ZipTests.cs",
        "WithCancellationTests.cs",
        "XunitAssemblyAttributes.cs",
    ] + [
        "//src/libraries/Common/tests:System/Diagnostics/Tracing/TestEventListener.cs",
        "//src/libraries/Common/tests:System/ShouldNotBeInvokedException.cs",
        "//src/libraries/Common/tests:System/Threading/ThreadPoolHelpers.cs",
    ],
    deps = [
        "//src/libraries/System.Linq.Parallel:ref_System.Linq.Parallel",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
