load("//:defs.bzl", "csharp_library")

exports_files(["PEReaderExtensions.cs"])

csharp_library(
    name = "ILCompiler.Reflection.ReadyToRun",
    srcs = [
        "Amd64/GcInfo.cs",
        "Amd64/GcSlotTable.cs",
        "Amd64/GcTransition.cs",
        "Amd64/Registers.cs",
        "Amd64/UnwindInfo.cs",
        "Arm/Registers.cs",
        "Arm/UnwindInfo.cs",
        "Arm64/Registers.cs",
        "Arm64/UnwindInfo.cs",
        "DebugInfo.cs",
        "DebugInfoTypes.cs",
        "DisassemblingTypeProvider.cs",
        "EHInfo.cs",
        "GCInfoTypes.cs",
        "GCRefMap.cs",
        "IAssemblyMetadata.cs",
        "IAssemblyResolver.cs",
        "InliningInfoSection.cs",
        "InliningInfoSection2.cs",
        "LoongArch64/Registers.cs",
        "LoongArch64/UnwindInfo.cs",
        "ManifestAssemblyMetadata.cs",
        "NativeArray.cs",
        "NativeHashtable.cs",
        "NativeReader.cs",
        "NibbleReader.cs",
        "PEReaderExtensions.cs",
        "PgoInfo.cs",
        "PgoInfoKey.cs",
        "ReadyToRunHeader.cs",
        "ReadyToRunImportSection.cs",
        "ReadyToRunMethod.cs",
        "ReadyToRunReader.cs",
        "ReadyToRunSection.cs",
        "ReadyToRunSignature.cs",
        "RiscV64/Registers.cs",
        "RiscV64/UnwindInfo.cs",
        "StandaloneAssemblyMetadata.cs",
        "StringExtensions.cs",
        "TransitionBlock.cs",
        "x86/CallPattern.cs",
        "x86/GcInfo.cs",
        "x86/GcSlotTable.cs",
        "x86/GcTransition.cs",
        "x86/InfoHdr.cs",
        "x86/NoGcRegionTable.cs",
        "x86/Registers.cs",
        "x86/UnwindInfo.cs",
    ] + [
        "//src/coreclr/tools/Common:Internal/Runtime/CorConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ModuleHeaders.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ReadyToRunConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ReadyToRunInstructionSet.cs",
        "//src/coreclr/tools/Common:Pgo/PgoFormat.cs",
    ],
    compiler_options = ["/unsafe"],
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
)
