load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Collections.Specialized.Tests",
    srcs = [
        "BitVector32Tests.cs",
        "Helpers.cs",
        "HybridDictionary/HybridDictionary.AddTests.cs",
        "HybridDictionary/HybridDictionary.CtorTests.cs",
        "HybridDictionary/HybridDictionary.KeysTests.cs",
        "HybridDictionary/HybridDictionary.RemoveTests.cs",
        "HybridDictionary/HybridDictionary.SetItemTests.cs",
        "HybridDictionary/HybridDictionary.ValuesTests.cs",
        "HybridDictionary/HybridDictionaryTests.cs",
        "ListDictionary/ListDictionary.IDictionary.Tests.cs",
        "ListDictionary/ListDictionary.Keys.Tests.cs",
        "ListDictionary/ListDictionary.Values.Tests.cs",
        "ListDictionaryTests.cs",
        "NameObjectCollectionBase/MyNameObjectCollection.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.ConstructorTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.CopyToTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.GetAllValuesTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.GetEnumeratorTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.KeysTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.ReadOnlyTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.RemoveAtTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.SetItemTests.cs",
        "NameObjectCollectionBase/NameObjectCollectionBase.SyncRootTests.cs",
        "NameValueCollection/NameValueCollection.AddNVCTests.cs",
        "NameValueCollection/NameValueCollection.AddStringStringTests.cs",
        "NameValueCollection/NameValueCollection.ClearTests.cs",
        "NameValueCollection/NameValueCollection.CopyToTests.cs",
        "NameValueCollection/NameValueCollection.CtorTests.cs",
        "NameValueCollection/NameValueCollection.GetIntTests.cs",
        "NameValueCollection/NameValueCollection.GetItemTests.cs",
        "NameValueCollection/NameValueCollection.GetKeyTests.cs",
        "NameValueCollection/NameValueCollection.GetStringTests.cs",
        "NameValueCollection/NameValueCollection.GetValuesIntTests.cs",
        "NameValueCollection/NameValueCollection.GetValuesStringTests.cs",
        "NameValueCollection/NameValueCollection.ReadOnlyTests.cs",
        "NameValueCollection/NameValueCollection.RemoveTests.cs",
        "NameValueCollection/NameValueCollection.SetItemTests.cs",
        "NameValueCollection/NameValueCollection.SetTests.cs",
        "OrderedDictionary/OrderedDictionaryTests.cs",
        "StringCollectionTests.cs",
        "StringDictionary/StringDictionary.AddTests.cs",
        "StringDictionary/StringDictionary.ContainsKeyTests.cs",
        "StringDictionary/StringDictionary.ContainsValueTests.cs",
        "StringDictionary/StringDictionary.CopyToTests.cs",
        "StringDictionary/StringDictionary.CtorTests.cs",
        "StringDictionary/StringDictionary.GetEnumeratorTests.cs",
        "StringDictionary/StringDictionary.GetItemTests.cs",
        "StringDictionary/StringDictionary.KeysTests.cs",
        "StringDictionary/StringDictionary.RemoveTests.cs",
        "StringDictionary/StringDictionary.SetItemTests.cs",
        "StringDictionary/StringDictionary.SyncRootTests.cs",
        "StringDictionary/StringDictionary.ValuesTests.cs",
        "StringDictionary/StringDictionaryClearTests.cs",
    ] + [
        "//src/libraries/Common/tests:System/Collections/CollectionAsserts.cs",
        "//src/libraries/Common/tests:System/Collections/ICollection.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Serialization.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/TestBase.NonGeneric.cs",
        "//src/libraries/Common/tests:System/Collections/TestingTypes.cs",
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = [
        "SYSLIB0011",
        "SYSLIB0050",
        "SYSLIB0051",
    ],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
