load("//src/libraries:defs.bzl", "live_csharp_library")

exports_files([
    "AndroidTestRunner/AndroidTestRunner.cs",
    "AppleTestRunner/AppleTestRunner.cs",
    "Extensions/ConfigurationRootTest.cs",
    "Extensions/NonCapturingTimerTest.cs",
    "Extensions/SingleThreadedSynchronizationContext.cs",
    "Extensions/TypeNameHelperTest.cs",
    "LibraryTestRunner.cs",
    "Microsoft/Win32/TempRegistryKey.cs",
    "SingleFileTestRunner/SingleFileTestRunner.cs",
    "SourceGenerators/GeneratorTestHelpers.cs",
    "SourceGenerators/GlobalOptionsOnlyProvider.cs",
    "SourceGenerators/LiveReferencePack.cs",
    "SourceGenerators/RoslynTestUtils.cs",
    "StaticTestGenerator/Program.cs",
    "StreamConformanceTests/System/IO/StreamConformanceTests.cs",
    "System/Buffers/NativeMemoryManager.cs",
    "System/Collections/CollectionAsserts.cs",
    "System/Collections/DebugView.Tests.cs",
    "System/Collections/DelegateEqualityComparer.cs",
    "System/Collections/DictionaryEntry.Tests.cs",
    "System/Collections/DictionaryExtensions.cs",
    "System/Collections/ICollection.Generic.Tests.cs",
    "System/Collections/ICollection.NonGeneric.Tests.cs",
    "System/Collections/ICollectionTest.cs",
    "System/Collections/IDictionary.Generic.Tests.cs",
    "System/Collections/IDictionary.Generic.Tests.netcoreapp.cs",
    "System/Collections/IDictionary.NonGeneric.Tests.cs",
    "System/Collections/IDictionary.NonGeneric.Tests.netcoreapp.cs",
    "System/Collections/IDictionaryTest.cs",
    "System/Collections/IEnumerable.Generic.Serialization.Tests.cs",
    "System/Collections/IEnumerable.Generic.Tests.cs",
    "System/Collections/IEnumerable.NonGeneric.Serialization.Tests.cs",
    "System/Collections/IEnumerable.NonGeneric.Tests.cs",
    "System/Collections/IEnumerableTest.cs",
    "System/Collections/IGenericSharedAPI.Tests.cs",
    "System/Collections/IList.Generic.Tests.cs",
    "System/Collections/IList.NonGeneric.Tests.cs",
    "System/Collections/IListTest.cs",
    "System/Collections/ISet.Generic.Tests.cs",
    "System/Collections/TestBase.Generic.cs",
    "System/Collections/TestBase.NonGeneric.cs",
    "System/Collections/TestingTypes.cs",
    "System/Collections/Utils.cs",
    "System/DateTimeTestHelpers.cs",
    "System/Diagnostics/DebuggerAttributes.cs",
    "System/Diagnostics/Tracing/ConsoleEventListener.cs",
    "System/Diagnostics/Tracing/TestEventListener.cs",
    "System/DirectoryServices/LdapConfiguration.cs",
    "System/Drawing/Helpers.cs",
    "System/EnumTypes.cs",
    "System/FunctionPointerCallingConventionTests.cs",
    "System/FunctionPointerEqualityTests.cs",
    "System/FunctionPointerTests.cs",
    "System/GenericMathHelpers.cs",
    "System/GenericMathTestMemberData.cs",
    "System/IO/ByteLoggingStream.cs",
    "System/IO/CallTrackingStream.cs",
    "System/IO/Compression/CRC.cs",
    "System/IO/Compression/CompressionStreamTestBase.cs",
    "System/IO/Compression/CompressionStreamUnitTestBase.cs",
    "System/IO/Compression/FileData.cs",
    "System/IO/Compression/LocalMemoryStream.cs",
    "System/IO/Compression/NoAsyncCallsStream.cs",
    "System/IO/Compression/NoSyncCallsStream.cs",
    "System/IO/Compression/StreamHelpers.cs",
    "System/IO/Compression/ZipTestHelper.ZipFile.cs",
    "System/IO/Compression/ZipTestHelper.cs",
    "System/IO/ConnectedStreams.cs",
    "System/IO/DelayStream.cs",
    "System/IO/DelegateDelegatingStream.cs",
    "System/IO/DelegateStream.cs",
    "System/IO/InterceptStreamWriter.cs",
    "System/IO/PathFeatures.cs",
    "System/IO/PositionValueStream.cs",
    "System/IO/ReparsePointUtilities.cs",
    "System/IO/TempDirectory.cs",
    "System/IO/TempFile.cs",
    "System/IO/VirtualDriveHelper.Windows.cs",
    "System/IO/WrappedMemoryStream.cs",
    "System/IO/WrappedStream.cs",
    "System/Linq/SkipTakeData.cs",
    "System/MockType.cs",
    "System/ModifiedTypeTests.cs",
    "System/Net/ActivityRecorder.cs",
    "System/Net/Capability.RawSocketPermissions.cs",
    "System/Net/Capability.Security.Unix.cs",
    "System/Net/Capability.Security.Windows.cs",
    "System/Net/Capability.Security.cs",
    "System/Net/Capability.Sockets.cs",
    "System/Net/Configuration.Certificates.Dynamic.cs",
    "System/Net/Configuration.Certificates.cs",
    "System/Net/Configuration.Http.cs",
    "System/Net/Configuration.Ping.cs",
    "System/Net/Configuration.Security.cs",
    "System/Net/Configuration.Sockets.cs",
    "System/Net/Configuration.WebSockets.cs",
    "System/Net/Configuration.cs",
    "System/Net/EnterpriseTests/EnterpriseTestConfiguration.cs",
    "System/Net/EventSourceTestLogging.cs",
    "System/Net/Http/ByteAtATimeContent.cs",
    "System/Net/Http/ChannelBindingAwareContent.cs",
    "System/Net/Http/CustomContent.cs",
    "System/Net/Http/DefaultCredentialsTest.cs",
    "System/Net/Http/DribbleStream.cs",
    "System/Net/Http/GenericLoopbackServer.cs",
    "System/Net/Http/HPackEncoder.cs",
    "System/Net/Http/Http2Frames.cs",
    "System/Net/Http/Http2LoopbackConnection.cs",
    "System/Net/Http/Http2LoopbackServer.cs",
    "System/Net/Http/Http3LoopbackConnection.cs",
    "System/Net/Http/Http3LoopbackServer.cs",
    "System/Net/Http/Http3LoopbackStream.cs",
    "System/Net/Http/HttpAgnosticLoopbackServer.cs",
    "System/Net/Http/HttpClient.SelectedSitesTest.cs",
    "System/Net/Http/HttpClientEKUTest.cs",
    "System/Net/Http/HttpClientHandlerTest.AcceptAllCerts.cs",
    "System/Net/Http/HttpClientHandlerTest.Asynchrony.cs",
    "System/Net/Http/HttpClientHandlerTest.Authentication.cs",
    "System/Net/Http/HttpClientHandlerTest.AutoRedirect.cs",
    "System/Net/Http/HttpClientHandlerTest.Cancellation.cs",
    "System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs",
    "System/Net/Http/HttpClientHandlerTest.Cookies.cs",
    "System/Net/Http/HttpClientHandlerTest.Decompression.cs",
    "System/Net/Http/HttpClientHandlerTest.DefaultProxyCredentials.cs",
    "System/Net/Http/HttpClientHandlerTest.MaxConnectionsPerServer.cs",
    "System/Net/Http/HttpClientHandlerTest.MaxResponseHeadersLength.cs",
    "System/Net/Http/HttpClientHandlerTest.Proxy.cs",
    "System/Net/Http/HttpClientHandlerTest.RemoteServer.cs",
    "System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs",
    "System/Net/Http/HttpClientHandlerTest.SslProtocols.cs",
    "System/Net/Http/HttpClientHandlerTest.cs",
    "System/Net/Http/HttpClientHandlerTestBase.cs",
    "System/Net/Http/HttpMessageHandlerLoopbackServer.cs",
    "System/Net/Http/HttpProtocolTests.cs",
    "System/Net/Http/HuffmanDecoder.cs",
    "System/Net/Http/HuffmanEncoder.cs",
    "System/Net/Http/IdnaProtocolTests.cs",
    "System/Net/Http/LoopbackProxyServer.cs",
    "System/Net/Http/LoopbackServer.AuthenticationHelpers.cs",
    "System/Net/Http/LoopbackServer.cs",
    "System/Net/Http/PostScenarioTest.cs",
    "System/Net/Http/QPackTestDecoder.cs",
    "System/Net/Http/QPackTestEncoder.cs",
    "System/Net/Http/RepeatedFlushContent.cs",
    "System/Net/Http/ResponseStreamTest.cs",
    "System/Net/Http/SyncBlockingContent.cs",
    "System/Net/Http/TestHelper.cs",
    "System/Net/Http/ThrowingContent.cs",
    "System/Net/HttpsTestClient.cs",
    "System/Net/HttpsTestServer.cs",
    "System/Net/ManualChunkingStream.cs",
    "System/Net/Prerequisites/NetCoreServer/GenericHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/DeflateHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/EchoBodyHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/EchoHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/EchoWebSocketHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/EchoWebSocketHeadersHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/EmptyContentHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/GZipHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/LargeResponse.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/RedirectHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/StatusCodeHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/TestHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/VerifyUploadHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Handlers/VersionHandler.cs",
    "System/Net/Prerequisites/NetCoreServer/Helpers/AuthenticationHelper.cs",
    "System/Net/Prerequisites/NetCoreServer/Helpers/ContentHelper.cs",
    "System/Net/Prerequisites/NetCoreServer/Helpers/NameValueCollectionConverter.cs",
    "System/Net/Prerequisites/NetCoreServer/Helpers/RequestHelper.cs",
    "System/Net/Prerequisites/NetCoreServer/Helpers/RequestInformation.cs",
    "System/Net/Prerequisites/NetCoreServer/Helpers/WebSocketAcceptHelper.cs",
    "System/Net/Prerequisites/NetCoreServer/Program.cs",
    "System/Net/Prerequisites/NetCoreServer/Startup.cs",
    "System/Net/Prerequisites/RemoteLoopServer/GenericHandler.cs",
    "System/Net/Prerequisites/RemoteLoopServer/Handlers/RemoteLoopHandler.cs",
    "System/Net/Prerequisites/RemoteLoopServer/Program.cs",
    "System/Net/Prerequisites/RemoteLoopServer/Startup.cs",
    "System/Net/QuicLoad.cs",
    "System/Net/RandomReadWriteSizeStream.cs",
    "System/Net/RemoteExecutorExtensions.cs",
    "System/Net/RemoteServerQuery.cs",
    "System/Net/Security/FakeNegotiateServer.cs",
    "System/Net/Security/FakeNtlmServer.cs",
    "System/Net/Security/Kerberos/FakeKdcServer.cs",
    "System/Net/Security/Kerberos/FakeKerberosPrincipal.cs",
    "System/Net/Security/Kerberos/FakePrincipalService.cs",
    "System/Net/Security/Kerberos/FakeRealmReferral.cs",
    "System/Net/Security/Kerberos/FakeRealmService.cs",
    "System/Net/Security/Kerberos/FakeRealmSettings.cs",
    "System/Net/Security/Kerberos/FakeTrustedRealms.cs",
    "System/Net/Security/Kerberos/KerberosExecutor.cs",
    "System/Net/Sockets/Fletcher32.cs",
    "System/Net/Sockets/SocketImplementationType.cs",
    "System/Net/Sockets/SocketTestExtensions.cs",
    "System/Net/Sockets/SocketTestServer.cs",
    "System/Net/Sockets/SocketTestServerAPM.cs",
    "System/Net/Sockets/SocketTestServerAsync.cs",
    "System/Net/Sockets/TestSettings.cs",
    "System/Net/SslProtocolSupport.cs",
    "System/Net/SslStreamCertificatePolicy.cs",
    "System/Net/TestLogging.cs",
    "System/Net/TestWebProxies.cs",
    "System/Net/VerboseTestLogging.cs",
    "System/Net/WebSockets/WebSocketEchoHelper.cs",
    "System/Net/WebSockets/WebSocketEchoOptions.cs",
    "System/NonRuntimeType.cs",
    "System/ObjectCloner.cs",
    "System/RandomDataGenerator.cs",
    "System/RealFormatterTestsBase.cs",
    "System/RealParserTestsBase.cs",
    "System/Reflection/MockParameterInfo.cs",
    "System/Runtime/CompilerServices/RuntimeHelpers.cs",
    "System/Runtime/Serialization/DataContractSerializerHelper.cs",
    "System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs",
    "System/Runtime/Serialization/Utils.cs",
    "System/Security/Cryptography/AesGcmTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherOneShotTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.Data.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/AesContractTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/AesCornerTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/AesFactory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/AesModeTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/DecryptorReusability.cs",
    "System/Security/Cryptography/AlgorithmImplementations/AES/KeyWrapTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaContractTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaFactoryTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaImplementationTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaMockImplementation.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestData.Raw.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestData.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestHelpers.cs",
    "System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestsBase.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DES/DESCipherOneShotTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DES/DESCipherTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DES/DESContractTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DES/DESFactory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DES/DesTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSAFactory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSAFactoryTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSAImportExport.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSAKeyFileTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSAKeyGeneration.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSAKeyPemTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.NistValidation.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatter.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSATestData.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DSAXml.cs",
    "System/Security/Cryptography/AlgorithmImplementations/DSA/DsaFamilySignatureFormatTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/EC/CurveDef.cs",
    "System/Security/Cryptography/AlgorithmImplementations/EC/ECKeyFileTests.LimitedPrivate.cs",
    "System/Security/Cryptography/AlgorithmImplementations/EC/ECKeyFileTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/EC/ECKeyPemTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/EC/EccTestBase.cs",
    "System/Security/Cryptography/AlgorithmImplementations/EC/EccTestData.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDhKeyFileTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanFactory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanFactoryTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanKeyPemTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.Hash.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.Hmac.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.ImportExport.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.NistValidation.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.Raw.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.Tls.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.Xml.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDiffieHellman/ECDiffieHellmanTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaFactory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaFactoryTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaImportExport.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaKeyFileTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaKeyPemTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaSignatureFormatTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaStub.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaTests.NistValidation.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaTests.netcoreapp.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaTestsBase.cs",
    "System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaXml.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaCngTests.Windows.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaCngTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaImplementationTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestHelpers.Cng.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestHelpers.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestImplementation.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsBase.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.Ietf.cs",
    "System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RC2/RC2CipherOneShotTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RC2/RC2CipherTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RC2/RC2ContractTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RC2/RC2Factory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RC2/RC2Tests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.netcoreapp.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/ImportExport.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/KeyGeneration.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSAFactory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSAFactoryTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSAKeyExchangeFormatter.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSAKeyFileTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSAKeyPemTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSASignatureFormatter.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSATestHelpers.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/RSAXml.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.netcoreapp.cs",
    "System/Security/Cryptography/AlgorithmImplementations/RSA/TestData.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaAlgorithmTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaContractTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaFactoryTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaImplementationTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaMockImplementation.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaPlatformTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.GeneratedCertificates.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestHelpers.cs",
    "System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/Symmetric/SymmetricOneShotBase.cs",
    "System/Security/Cryptography/AlgorithmImplementations/TripleDES/TripleDESCipherOneShotTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/TripleDES/TripleDESCipherTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/TripleDES/TripleDESContractTests.cs",
    "System/Security/Cryptography/AlgorithmImplementations/TripleDES/TripleDESFactory.cs",
    "System/Security/Cryptography/AlgorithmImplementations/TripleDES/TripleDESReusabilityTests.cs",
    "System/Security/Cryptography/AsnUtils.cs",
    "System/Security/Cryptography/AsymmetricSignatureFormatter.cs",
    "System/Security/Cryptography/ByteUtils.cs",
    "System/Security/Cryptography/CngKeyWrapper.cs",
    "System/Security/Cryptography/CommonAEADTests.cs",
    "System/Security/Cryptography/CompositeMLDsaAlgorithmTests.cs",
    "System/Security/Cryptography/CryptoUtils.cs",
    "System/Security/Cryptography/HashInfo.cs",
    "System/Security/Cryptography/MLDsaAlgorithmTests.cs",
    "System/Security/Cryptography/MLKemAlgorithmTests.cs",
    "System/Security/Cryptography/MLKemBaseTests.cs",
    "System/Security/Cryptography/MLKemCngTests.NotSupported.cs",
    "System/Security/Cryptography/MLKemCngTests.Windows.cs",
    "System/Security/Cryptography/MLKemContractTests.cs",
    "System/Security/Cryptography/MLKemImplementationTests.cs",
    "System/Security/Cryptography/MLKemKeyTests.cs",
    "System/Security/Cryptography/MLKemNotSupportedTests.cs",
    "System/Security/Cryptography/MLKemTestData.cs",
    "System/Security/Cryptography/MLKemTests.cs",
    "System/Security/Cryptography/OpenSslNamedKeys.Helpers.cs",
    "System/Security/Cryptography/PbeParametersTests.cs",
    "System/Security/Cryptography/PlatformSupport.cs",
    "System/Security/Cryptography/SP800108HmacCounterKdfTests.ArgValidation.cs",
    "System/Security/Cryptography/SP800108HmacCounterKdfTests.Functional.cs",
    "System/Security/Cryptography/SP800108HmacCounterKdfTests.Helpers.cs",
    "System/Security/Cryptography/SP800108HmacCounterKdfTests.ThreadSafety.cs",
    "System/Security/Cryptography/SignatureSupport.cs",
    "System/Security/Cryptography/X509Certificates/CertificateAuthority.cs",
    "System/Security/Cryptography/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.Shared.cs",
    "System/Security/Cryptography/X509Certificates/MLKemCertTests.cs",
    "System/Security/Cryptography/X509Certificates/RevocationResponder.cs",
    "System/Security/Cryptography/X509Certificates/TempFileHolder.cs",
    "System/Security/Cryptography/X509Certificates/TestData.cs",
    "System/Security/Cryptography/X509Certificates/X509CertificateLoaderPkcs12CollectionTests.cs",
    "System/Security/Cryptography/X509Certificates/X509CertificateLoaderPkcs12Tests.WindowsAttributes.cs",
    "System/Security/Cryptography/X509Certificates/X509CertificateLoaderPkcs12Tests.cs",
    "System/Security/Cryptography/X509Certificates/X509CertificateLoaderTests.cs",
    "System/ShouldNotBeInvokedException.cs",
    "System/Threading/Tasks/GetStateMachineData.cs",
    "System/Threading/Tasks/Sources/ManualResetValueTaskSource.cs",
    "System/Threading/Tasks/Sources/ManualResetValueTaskSourceFactory.cs",
    "System/Threading/Tasks/TaskTimeoutExtensions.cs",
    "System/Threading/ThreadPoolHelpers.cs",
    "System/Threading/ThreadTestHelpers.cs",
    "System/Threading/TrackingSynchronizationContext.cs",
    "System/TimeProviderTests.cs",
    "System/Xml/BaseLibManaged/Globalization.cs",
    "System/Xml/ModuleCore/XunitRunner.cs",
    "System/Xml/ModuleCore/XunitTestCase.cs",
    "System/Xml/ModuleCore/cattrbase.cs",
    "System/Xml/ModuleCore/ccommon.cs",
    "System/Xml/ModuleCore/cerror.cs",
    "System/Xml/ModuleCore/cltmconsole.cs",
    "System/Xml/ModuleCore/cmodinfo.cs",
    "System/Xml/ModuleCore/cparser.cs",
    "System/Xml/ModuleCore/ctestbase.cs",
    "System/Xml/ModuleCore/ctestcase.cs",
    "System/Xml/ModuleCore/ctestexception.cs",
    "System/Xml/ModuleCore/ctestmodule.cs",
    "System/Xml/ModuleCore/cvariation.cs",
    "System/Xml/ModuleCore/interop.cs",
    "System/Xml/XPath/Common/FileHelper.cs",
    "System/Xml/XPath/Common/ICreateNavigator.cs",
    "System/Xml/XPath/Common/Utils.cs",
    "System/Xml/XPath/Common/XPathResult.cs",
    "System/Xml/XPath/Common/XPathResultToken.cs",
    "System/Xml/XPath/CoreFunctionLibrary/BooleanFunctionsTests.cs",
    "System/Xml/XPath/CoreFunctionLibrary/ComplexExpressionsTests.cs",
    "System/Xml/XPath/CoreFunctionLibrary/NodeSetFunctionsTests.cs",
    "System/Xml/XPath/CoreFunctionLibrary/NodeSetMatchesTests.cs",
    "System/Xml/XPath/CoreFunctionLibrary/NumberFunctionsTests.cs",
    "System/Xml/XPath/CoreFunctionLibrary/ParameterTypeCoercionTests.cs",
    "System/Xml/XPath/CoreFunctionLibrary/StringFunctionsTests.cs",
    "System/Xml/XPath/CustomerScenarios/CustomerScenariosTests.cs",
    "System/Xml/XPath/CustomerScenarios/MatchesTests.cs",
    "System/Xml/XPath/FuncExpressions/BasicMatchesTests.cs",
    "System/Xml/XPath/FuncExpressions/BasicsTests.cs",
    "System/Xml/XPath/FuncExpressions/BooleansTests.cs",
    "System/Xml/XPath/FuncExpressions/NodeSetsMatchesTests.cs",
    "System/Xml/XPath/FuncExpressions/NodeSetsTests.cs",
    "System/Xml/XPath/FuncExpressions/NumbersTests.cs",
    "System/Xml/XPath/FuncExpressions/SetContextFunctionalTests.cs",
    "System/Xml/XPath/FuncExpressions/SetContextMatchesTests.cs",
    "System/Xml/XPath/FuncLocation/PathAbbreviatedSyntaxMatchesTests.cs",
    "System/Xml/XPath/FuncLocation/PathAbbreviatedSyntaxTests.cs",
    "System/Xml/XPath/FuncLocation/PathAxeCombinationsTests.cs",
    "System/Xml/XPath/FuncLocation/PathAxeComplexExprMatchesTests.cs",
    "System/Xml/XPath/FuncLocation/PathAxeComplexExprTests.cs",
    "System/Xml/XPath/FuncLocation/PathAxeMatchesTests.cs",
    "System/Xml/XPath/FuncLocation/PathAxesTests.cs",
    "System/Xml/XPath/FuncLocation/PathNodeMatchesTests.cs",
    "System/Xml/XPath/FuncLocation/PathNodeTests.cs",
    "System/Xml/XPath/FuncLocation/PathPredicateComplexExprTests.cs",
    "System/Xml/XPath/FuncLocation/PathPredicateMatchesTests.cs",
    "System/Xml/XPath/FuncLocation/PathPredicatePositionTests.cs",
    "System/Xml/XPath/FuncLocation/PathPredicatesTests.cs",
    "System/Xml/XPath/FuncLocation/StepMatchesTests.cs",
    "System/Xml/XPath/FuncLocation/StepsTests.cs",
    "System/Xml/XPath/MiscellaneousCases/GlobalizationTests.cs",
    "System/Xml/XPath/MiscellaneousCases/LexicalStructureTests.cs",
    "System/Xml/XPath/MiscellaneousCases/MatchesTests.cs",
    "System/Xml/XPath/MiscellaneousCases/MiscellaneousCasesTests.cs",
    "System/Xml/XPath/MiscellaneousCases/NodeSetsTests.cs",
    "System/Xml/XPath/MiscellaneousCases/RegressionTestsTests.cs",
    "System/Xml/XPath/TestsWithEncoding/MiscWithEncodings.cs",
    "System/Xml/XPath/XDocument/CreateNavigatorComparer.cs",
    "System/Xml/XPath/XDocument/CreateNavigatorFromXDocument.cs",
    "System/Xml/XPath/XDocument/NavigatorComparer.cs",
    "System/Xml/XPath/XPathExpressionTests/CompileTests.cs",
    "System/Xml/XPath/XPathExpressionTests/EvaluateTests.cs",
    "System/Xml/XPath/XmlDocument/CreateNavigatorFromXmlDocument.cs",
    "System/Xml/XmlCoreTest/AsyncUtil.cs",
    "System/Xml/XmlCoreTest/CustomWriter.cs",
    "System/Xml/XmlCoreTest/FilePathUtil.cs",
    "System/Xml/XmlCoreTest/ManagedNodeWriter.cs",
    "System/Xml/XmlCoreTest/MiscUtil.cs",
    "System/Xml/XmlCoreTest/ReaderCreateUtil.cs",
    "System/Xml/XmlCoreTest/ReaderUtil.cs",
    "System/Xml/XmlCoreTest/TestData.g.cs",
    "System/Xml/XmlCoreTest/UnicodeCharHelper.cs",
    "System/Xml/XmlCoreTest/WriterFactory.cs",
    "System/Xml/XmlDiff/XmlDiff.cs",
    "System/Xml/XmlDiff/XmlDiffDocument.cs",
    "System/Xml/XmlDiff/XmlDiffOption.cs",
    "TestUtilities.Unicode/System/Text/Unicode/BidiClass.cs",
    "TestUtilities.Unicode/System/Text/Unicode/CodePoint.cs",
    "TestUtilities.Unicode/System/Text/Unicode/CodePointFlags.cs",
    "TestUtilities.Unicode/System/Text/Unicode/GraphemeClusterBreakProperty.cs",
    "TestUtilities.Unicode/System/Text/Unicode/ParsedUnicodeData.cs",
    "TestUtilities.Unicode/System/Text/Unicode/PropsFileEntry.cs",
    "TestUtilities.Unicode/System/Text/Unicode/Resources.cs",
    "TestUtilities.Unicode/System/Text/Unicode/UnicodeData.cs",
    "TestUtilities.Unicode/System/Text/Unicode/UnicodeDataFileEntry.cs",
    "TestUtilities/Interop/Interop.Libraries.cs",
    "TestUtilities/RandomTestCaseOrderer.cs",
    "TestUtilities/RandomTestCollectionOrderer.cs",
    "TestUtilities/System/AdminHelpers.cs",
    "TestUtilities/System/AssemblyPathHelper.cs",
    "TestUtilities/System/AssertExtensions.cs",
    "TestUtilities/System/Buffers/BoundedMemory.Creation.cs",
    "TestUtilities/System/Buffers/BoundedMemory.Default.cs",
    "TestUtilities/System/Buffers/BoundedMemory.Unix.cs",
    "TestUtilities/System/Buffers/BoundedMemory.Windows.cs",
    "TestUtilities/System/Buffers/BoundedMemory.cs",
    "TestUtilities/System/Buffers/PoisonPagePlacement.cs",
    "TestUtilities/System/DisableParallelization.cs",
    "TestUtilities/System/DisableParallelizationPerAssembly.cs",
    "TestUtilities/System/IO/FileCleanupTestBase.cs",
    "TestUtilities/System/IO/PathGenerator.cs",
    "TestUtilities/System/IO/StreamExtensions.cs",
    "TestUtilities/System/LineEndingsHelper.cs",
    "TestUtilities/System/PlatformDetection.Unix.cs",
    "TestUtilities/System/PlatformDetection.Windows.cs",
    "TestUtilities/System/PlatformDetection.cs",
    "TestUtilities/System/RetryHelper.cs",
    "TestUtilities/System/Runtime/InteropServices/SafeBufferUtil.cs",
    "TestUtilities/System/TestEnvironment.cs",
    "TestUtilities/System/ThreadCultureChange.cs",
    "TestUtilities/System/WindowsIdentityFixture.cs",
    "TestUtilities/System/WindowsTestFileShare.cs",
    "TestUtilities/TestEventListener.cs",
    "Tests/Interop/OSReleaseTests.cs",
    "Tests/Interop/cgroupsTests.cs",
    "Tests/Interop/procfsTests.cs",
    "Tests/RandomizedTestOrderAssemblyInfo.cs",
    "Tests/SourceGenerators/SourceWriterTests.cs",
    "Tests/System/Collections/Generic/ArrayBuilderTests.cs",
    "Tests/System/IO/ConnectedStreamsTests.cs",
    "Tests/System/IO/PathInternal.Tests.cs",
    "Tests/System/IO/PathInternal.Unix.Tests.cs",
    "Tests/System/IO/PathInternal.Windows.Tests.cs",
    "Tests/System/IO/RowConfigReaderTests.cs",
    "Tests/System/IO/StringParserTests.cs",
    "Tests/System/IO/Win32Marshal.Tests.cs",
    "Tests/System/Net/ArrayBufferTests.cs",
    "Tests/System/Net/HttpDateParserTests.cs",
    "Tests/System/Net/HttpKnownHeaderNamesTests.cs",
    "Tests/System/Net/MultiArrayBufferTests.cs",
    "Tests/System/Net/aspnetcore/Http2/DynamicTableTest.cs",
    "Tests/System/Net/aspnetcore/Http2/HPackDecoderTest.cs",
    "Tests/System/Net/aspnetcore/Http2/HPackIntegerTest.cs",
    "Tests/System/Net/aspnetcore/Http2/HuffmanDecodingTests.cs",
    "Tests/System/Net/aspnetcore/Http3/QPackDecoderTest.cs",
    "Tests/System/Net/aspnetcore/Http3/VariableLengthIntegerHelperTests.cs",
    "Tests/System/PasteArgumentsTests.cs",
    "Tests/System/Security/IdentityHelperTests.cs",
    "Tests/System/StringTests.cs",
    "Tests/System/Text/SimpleRegexTests.cs",
    "Tests/System/Text/ValueStringBuilderTests.cs",
    "Tests/TheoryDataExtensions.cs",
    "WasmTestRunner/WasmTestRunner.cs",
] + [
    "Data/TinyAssembly.dll",
    "Data/TinyAssembly.il",
])

live_csharp_library(
    name = "TestUtilities",
    srcs = [
        "TestUtilities/Interop/Interop.Libraries.cs",
        "TestUtilities/RandomTestCaseOrderer.cs",
        "TestUtilities/RandomTestCollectionOrderer.cs",
        "TestUtilities/System/AdminHelpers.cs",
        "TestUtilities/System/AssemblyPathHelper.cs",
        "TestUtilities/System/AssertExtensions.cs",
        "TestUtilities/System/Buffers/BoundedMemory.Creation.cs",
        "TestUtilities/System/Buffers/BoundedMemory.Default.cs",
        "TestUtilities/System/Buffers/BoundedMemory.Unix.cs",
        "TestUtilities/System/Buffers/BoundedMemory.Windows.cs",
        "TestUtilities/System/Buffers/BoundedMemory.cs",
        "TestUtilities/System/Buffers/PoisonPagePlacement.cs",
        "TestUtilities/System/DisableParallelization.cs",
        "TestUtilities/System/DisableParallelizationPerAssembly.cs",
        "TestUtilities/System/IO/FileCleanupTestBase.cs",
        "TestUtilities/System/IO/PathGenerator.cs",
        "TestUtilities/System/IO/StreamExtensions.cs",
        "TestUtilities/System/LineEndingsHelper.cs",
        "TestUtilities/System/PlatformDetection.Unix.cs",
        "TestUtilities/System/PlatformDetection.Windows.cs",
        "TestUtilities/System/PlatformDetection.cs",
        "TestUtilities/System/RetryHelper.cs",
        "TestUtilities/System/Runtime/InteropServices/SafeBufferUtil.cs",
        "TestUtilities/System/TestEnvironment.cs",
        "TestUtilities/System/ThreadCultureChange.cs",
        "TestUtilities/System/WindowsIdentityFixture.cs",
        "TestUtilities/TestEventListener.cs",
    ] + [
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.BOOL.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.CreateFile.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.FileOperations.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.GetCurrentProcess.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.GetFinalPathNameByHandle.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.SECURITY_ATTRIBUTES.cs",
        "//src/libraries/Common:src/Interop/Windows/NtDll/Interop.RtlGetVersion.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.OpenProcessToken.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.CloseHandle.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.TOKEN_INFORMATION_CLASS.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.GetTokenInformation_void.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.TOKEN_ELEVATION.cs",
        "//src/libraries/Common:src/Microsoft/Win32/SafeHandles/SafeTokenHandle.cs",
        "//src/libraries/Common:src/System/IO/PathInternal.Windows.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.Initialization.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSslAvailable.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSslVersion.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSslGetProtocolSupport.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetEUid.cs",
        "//src/libraries/Common:src/Interop/Android/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.Ssl.ProtocolSupport.cs",
    ],
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
        "@paket.main//xunit.extensibility.execution",
        "//src/libraries:ref_System.Linq.Expressions",
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries/Microsoft.Win32.Registry:ref_Microsoft.Win32.Registry",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.IO.MemoryMappedFiles:ref_System.IO.MemoryMappedFiles",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Security.Principal.Windows:ref_System.Security.Principal.Windows",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
    ],
    allow_unsafe_blocks = True,
    visibility = ["//visibility:public"],
    nowarn = [
        "CS8632",
    ],
)

live_csharp_library(
    name = "StreamConformanceTests",
    srcs = ["StreamConformanceTests/System/IO/StreamConformanceTests.cs"] + [
        "//src/libraries/Common/tests:System/IO/ConnectedStreams.cs",
        "//src/libraries/Common/tests:System/IO/CallTrackingStream.cs",
        "//src/libraries/Common:src/System/Net/ArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/MultiArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/StreamBuffer.cs",
        "//src/libraries/Common:src/System/IO/DelegatingStream.cs",
    ],
    deps = [
        ":TestUtilities",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    visibility = ["//visibility:public"],
)
