load("//:defs.bzl", "csharp_library")
load("//src/libraries:defs.bzl", "live_csharp_library")

exports_files(glob(["**/*.cs"]) + glob(["Data/**"]))

csharp_library(
    name = "TestUtilities",
    nowarn = ["CA1510", "CA1511", "CA1512", "CA1513", "CA1845", "CA1846", "CA1847", "IL2121", "SYSLIB0011", "SYSLIB0050", "SYSLIB0051"],
    srcs = glob(
        ["TestUtilities/**/*.cs"],
        exclude = [
            "TestUtilities/System/WindowsTestFileShare.cs",
            # Not compiled by MSBuild TestUtilities project
            "TestUtilities/System/DisableParallelizationPerAssembly.cs",
        ],
    ) + [
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.BOOL.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.CreateFile.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.FileOperations.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.GetCurrentProcess.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.GetFinalPathNameByHandle.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.SECURITY_ATTRIBUTES.cs",
        "//src/libraries/Common:src/Interop/Windows/NtDll/Interop.RtlGetVersion.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.OpenProcessToken.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.CloseHandle.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.TOKEN_INFORMATION_CLASS.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.GetTokenInformation_void.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.TOKEN_ELEVATION.cs",
        "//src/libraries/Common:src/Microsoft/Win32/SafeHandles/SafeTokenHandle.cs",
        "//src/libraries/Common:src/System/IO/PathInternal.Windows.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.Initialization.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSslAvailable.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSslVersion.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSslGetProtocolSupport.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetEUid.cs",
        "//src/libraries/Common:src/Interop/Android/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.Ssl.ProtocolSupport.cs",
    ],
    nullable = "enable",
    langversion = "preview",
    compiler_options = [
        "/features:strict",
        "/features:nullablePublicOnly",
    ],
    target_frameworks = ["net8.0"],
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
        "@paket.main//xunit.extensibility.execution",
    ],
    allow_unsafe_blocks = True,
    treat_warnings_as_errors = False,
    visibility = ["//visibility:public"],
)

live_csharp_library(
    name = "StreamConformanceTests",
    nowarn = ["IL2121", "SYSLIB0011", "SYSLIB0050", "SYSLIB0051"],
    srcs = glob(["StreamConformanceTests/**/*.cs"]) + [
        "//src/libraries/Common/tests:System/IO/ConnectedStreams.cs",
        "//src/libraries/Common/tests:System/IO/CallTrackingStream.cs",
        "//src/libraries/Common:src/System/Net/ArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/MultiArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/StreamBuffer.cs",
        "//src/libraries/Common:src/System/IO/DelegatingStream.cs",
    ],
    deps = [
        ":TestUtilities",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    visibility = ["//visibility:public"],
)
