load("@rules_dotnet//dotnet:defs.bzl", "csharp_library")

csharp_library(
    name = "Mono.Linker.Tests.Cases.Expectations",
    srcs = [
        "Assertions/AddedPseudoAttributeAttribute.cs",
        "Assertions/BaseExpectedLinkedBehaviorAttribute.cs",
        "Assertions/BaseInAssemblyAttribute.cs",
        "Assertions/BaseMemberAssertionAttribute.cs",
        "Assertions/CreatedMemberAttribute.cs",
        "Assertions/CreatedMemberInAssemblyAttribute.cs",
        "Assertions/DependencyRecordedAttribute.cs",
        "Assertions/DisableILVerifyDiffingAttribute.cs",
        "Assertions/DisplayNameAttribute.cs",
        "Assertions/EnableLoggerAttribute.cs",
        "Assertions/ExpectBodyModifiedAttribute.cs",
        "Assertions/ExpectExactlyResolvedDocumentationSignatureAttribute.cs",
        "Assertions/ExpectExceptionHandlersModifiedAttribute.cs",
        "Assertions/ExpectGeneratedDocumentationSignatureAttribute.cs",
        "Assertions/ExpectILFailureAttribute.cs",
        "Assertions/ExpectLocalsModifiedAttribute.cs",
        "Assertions/ExpectNonZeroExitCodeAttribute.cs",
        "Assertions/ExpectResolvedDocumentationSignatureAttribute.cs",
        "Assertions/ExpectUnresolvedDocumentationSignatureAttribute.cs",
        "Assertions/ExpectedInstructionSequenceAttribute.cs",
        "Assertions/ExpectedInstructionSequenceOnMemberInAssemblyAttribute.cs",
        "Assertions/ExpectedLocalsSequenceAttribute.cs",
        "Assertions/ExpectedNoWarningsAttribute.cs",
        "Assertions/ExpectedWarningAttribute.cs",
        "Assertions/IgnoreTestCaseAttribute.cs",
        "Assertions/KeptAllTypesAndMembersInAssemblyAttribute.cs",
        "Assertions/KeptAssemblyAttribute.cs",
        "Assertions/KeptAttribute.cs",
        "Assertions/KeptAttributeAttribute.cs",
        "Assertions/KeptAttributeInAssemblyAttribute.cs",
        "Assertions/KeptAttributeOnConstraintAttribute.cs",
        "Assertions/KeptAttributeOnFixedBufferTypeAttribute.cs",
        "Assertions/KeptBackingFieldAttribute.cs",
        "Assertions/KeptBaseOnTypeInAssemblyAttribute.cs",
        "Assertions/KeptBaseTypeAttribute.cs",
        "Assertions/KeptByAttribute.cs",
        "Assertions/KeptDelegateCacheFieldAttribute.cs",
        "Assertions/KeptEventAddMethodAttribute.cs",
        "Assertions/KeptEventRemoveMethodAttribute.cs",
        "Assertions/KeptExportedTypeAttribute.cs",
        "Assertions/KeptFixedBufferAttribute.cs",
        "Assertions/KeptGenericParamAttributesAttribute.cs",
        "Assertions/KeptInitializerData.cs",
        "Assertions/KeptInterfaceAttribute.cs",
        "Assertions/KeptInterfaceOnTypeInAssemblyAttribute.cs",
        "Assertions/KeptMemberAttribute.cs",
        "Assertions/KeptMemberInAssemblyAttribute.cs",
        "Assertions/KeptModuleReferenceAttribute.cs",
        "Assertions/KeptOverrideAttribute.cs",
        "Assertions/KeptOverrideOnMethodInAssemblyAttribute.cs",
        "Assertions/KeptPrivateImplementationDetails.cs",
        "Assertions/KeptReferenceAttribute.cs",
        "Assertions/KeptReferencesInAssemblyAttribute.cs",
        "Assertions/KeptResourceAttribute.cs",
        "Assertions/KeptResourceInAssemblyAttribute.cs",
        "Assertions/KeptSecurityAttribute.cs",
        "Assertions/KeptSymbolsAttribute.cs",
        "Assertions/KeptTypeInAssemblyAttribute.cs",
        "Assertions/LogContainsAttribute.cs",
        "Assertions/LogDoesNotContainAttribute.cs",
        "Assertions/NoLinkedOutputAttribute.cs",
        "Assertions/RemovedAssemblyAttribute.cs",
        "Assertions/RemovedAssemblyReference.cs",
        "Assertions/RemovedAttributeInAssembly.cs",
        "Assertions/RemovedForwarderAttribute.cs",
        "Assertions/RemovedInterfaceOnTypeInAssemblyAttribute.cs",
        "Assertions/RemovedMemberInAssemblyAttribute.cs",
        "Assertions/RemovedNameValueAttribute.cs",
        "Assertions/RemovedOverrideAttribute.cs",
        "Assertions/RemovedOverrideOnMethodInAssemblyAttribute.cs",
        "Assertions/RemovedPseudoAttributeAttribute.cs",
        "Assertions/RemovedResourceInAssemblyAttribute.cs",
        "Assertions/RemovedSymbolsAttribute.cs",
        "Assertions/RemovedTypeInAssemblyAttribute.cs",
        "Assertions/SkipILVerifyAttribute.cs",
        "Assertions/SkipKeptItemsValidationAttribute.cs",
        "Assertions/SkipRemainingErrorsValidationAttribute.cs",
        "Assertions/TestCaseRequirementsAttribute.cs",
        "Assertions/TestRunCharacteristics.cs",
        "Assertions/Tool.cs",
        "Assertions/UnexpectedWarningAttribute.cs",
        "Assertions/VerifyMetadataNamesAttribute.cs",
        "Helpers/DataFlowStringExtensions.cs",
        "Helpers/DataFlowTypeExtensions.cs",
        "Helpers/PlatformAssemblies.cs",
        "Metadata/BaseMetadataAttribute.cs",
        "Metadata/DefineAttribute.cs",
        "Metadata/DeleteBeforeAttribute.cs",
        "Metadata/GenerateTargetFrameworkAttribute.cs",
        "Metadata/IgnoreDescriptorsAttribute.cs",
        "Metadata/IgnoreLinkAttributesAttribute.cs",
        "Metadata/IgnoreSubstitutionsAttribute.cs",
        "Metadata/Il8nAttribute.cs",
        "Metadata/KeepTypeForwarderOnlyAssembliesAttribute.cs",
        "Metadata/NotATestCaseAttribute.cs",
        "Metadata/ReferenceAttribute.cs",
        "Metadata/ReferenceDependencyAttribute.cs",
        "Metadata/SandboxDependencyAttribute.cs",
        "Metadata/SetupCSharpCompilerToUseAttribute.cs",
        "Metadata/SetupCompileAfterAttribute.cs",
        "Metadata/SetupCompileArgumentAttribute.cs",
        "Metadata/SetupCompileAsLibraryAttribute.cs",
        "Metadata/SetupCompileAssemblyNameAttribute.cs",
        "Metadata/SetupCompileBeforeAttribute.cs",
        "Metadata/SetupCompileResourceAttribute.cs",
        "Metadata/SetupIlcFrameworkCompilationAttribute.cs",
        "Metadata/SetupLinkAttributesFile.cs",
        "Metadata/SetupLinkerActionAttribute.cs",
        "Metadata/SetupLinkerArgumentAttribute.cs",
        "Metadata/SetupLinkerDefaultActionAttribute.cs",
        "Metadata/SetupLinkerDescriptorFile.cs",
        "Metadata/SetupLinkerDumpDependenciesAttribute.cs.cs",
        "Metadata/SetupLinkerLinkAllAttribute.cs",
        "Metadata/SetupLinkerLinkPublicAndFamilyAttribute.cs",
        "Metadata/SetupLinkerLinkSymbolsAttribute.cs",
        "Metadata/SetupLinkerResponseFileAttribute.cs",
        "Metadata/SetupLinkerSubstitutionFileAttribute.cs",
        "Metadata/SetupLinkerTrimModeAttribute.cs",
        "Metadata/SetupRootEntireAssemblyAttribute.cs",
        "Metadata/SkipUnresolvedAttribute.cs",
        "Metadata/StripDescriptorsAttribute.cs",
        "Metadata/StripLinkAttributesAttribute.cs",
        "Metadata/StripSubstitutionsAttribute.cs",
        "Support/DynamicallyAccessedMembersAttribute.cs",
        "Support/IntrinsicAttribute.cs",
        "Support/RemoveAttributeInstancesAttribute.cs",
    ] + [
        "//src/tools/illink/src/ILLink.Shared:DynamicallyAccessedMemberTypesEx.cs",
        "//src/tools/illink/src/ILLink.Shared:RequiresDynamicCodeAttribute.cs",
        "//src/tools/illink/src/ILLink.Shared:RequiresUnreferencedCodeAttribute.cs",
    ],
    out = "Mono.Linker.Tests.Cases.Expectations",
    target_frameworks = ["net10.0"],
    nowarn = ["CS0436"],
    visibility = ["//src/tools/illink:__subpackages__"],
)
