# Package for eng/ (enables subpackage references)

load("//:defs.bzl", "XUNIT_CONSOLE_RUNNER_REPO")

exports_files([
    "run_binary.sh.tpl",
    "run_test.sh.tpl",
    "run_library_test.sh.tpl",
    "testing/xunit/xunit.runner.json",
])

filegroup(
    name = "xunit_console_runner",
    srcs = [
        "@{}//:tools/net/xunit.console.dll".format(XUNIT_CONSOLE_RUNNER_REPO),
        "@{}//:tools/net/xunit.console.runtimeconfig.json".format(XUNIT_CONSOLE_RUNNER_REPO),
        "@{}//:tools/net/xunit.console.deps.json".format(XUNIT_CONSOLE_RUNNER_REPO),
        "@{}//:tools/net/xunit.runner.reporters.netcoreapp10.dll".format(XUNIT_CONSOLE_RUNNER_REPO),
        "@{}//:tools/net/xunit.runner.utility.netcoreapp10.dll".format(XUNIT_CONSOLE_RUNNER_REPO),
    ],
    visibility = ["//visibility:public"],
)
