load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.IO.FileSystem.Watcher.Tests",
    srcs = [
        "Args.ErrorEventArgs.cs",
        "Args.FileSystemEventArgs.cs",
        "Args.RenamedEventArgs.cs",
        "AssemblyInfo.cs",
        "FileSystemWatcher.Directory.Changed.cs",
        "FileSystemWatcher.Directory.Create.cs",
        "FileSystemWatcher.Directory.Delete.cs",
        "FileSystemWatcher.Directory.Move.cs",
        "FileSystemWatcher.Directory.NotifyFilter.cs",
        "FileSystemWatcher.File.Changed.cs",
        "FileSystemWatcher.File.Create.cs",
        "FileSystemWatcher.File.Delete.cs",
        "FileSystemWatcher.File.Move.cs",
        "FileSystemWatcher.File.NotifyFilter.cs",
        "FileSystemWatcher.InternalBufferSize.cs",
        "FileSystemWatcher.MultipleWatchers.cs",
        "FileSystemWatcher.SymbolicLink.cs",
        "FileSystemWatcher.Unix.cs",
        "FileSystemWatcher.WaitForChanged.cs",
        "FileSystemWatcher.cs",
        "FileSystemWatcher.unit.cs",
        "InternalBufferOverflowException.cs",
        "Utility/FileSystemWatcherTest.cs",
        "Utility/TestFileSystemWatcher.cs",
    ] + [
        "//src/libraries/Common/tests:System/IO/TempFile.cs",
        "//src/libraries/Common/tests:System/IO/TempDirectory.cs",
        "//src/libraries/Common/tests:System/IO/ReparsePointUtilities.cs",
        "//src/libraries/Common/tests:System/Threading/ThreadTestHelpers.cs",
        "//src/libraries/Common/tests:TestUtilities/System/DisableParallelization.cs",
        "//src/libraries/Common:src/System/IO/PathInternal.cs",
        "//src/libraries/Common:src/System/IO/PathInternal.Unix.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ResourceLimits.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
    ],
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    deps = [
        "//src/libraries/System.IO.FileSystem.Watcher:ref_System.IO.FileSystem.Watcher",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
