load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Management.cs",
    "ref/System.Management.manual.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Management",
    srcs = [
        "ref/System.Management.cs",
        "ref/System.Management.manual.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.CodeDom:ref_System.CodeDom",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Management",
    skip_locals_init = False,
    pnse = True,
    pnse_message = "SR.PlatformNotSupported_SystemManagement",
    pnse_ref_srcs = [
        "ref/System.Management.cs",
        "ref/System.Management.manual.cs",
    ],
    multitarget = True,
    srcs = [],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.CodeDom:ref_System.CodeDom",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
    resx_file = "src/Resources/Strings.resx",
    supported_os_platforms_short = ["windows"],
    nullable = "disable",
)

ref_impl_pair(
    name = "live_System.Management",
    ref = ":ref_System.Management",
    lib = ":impl_System.Management",
    visibility = ["//visibility:public"],
)
