load("//src/tests:live_test.bzl", "coreclr_test", "il_coreclr_test")

coreclr_test(
    name = "Runtime_101046",
    srcs = ["Runtime_101046.cs"],
    optimize = True,
    allow_unsafe_blocks = True,
)

il_coreclr_test(
    name = "Runtime_101046",
    srcs = ["Runtime_101046.il"],
    optimize = True,
)
