exports_files([
    "CommandLineHelpers.cs",
    "Compiler/CodeGenerationFailedException.cs",
    "Compiler/CompilationBuilder.cs",
    "Compiler/CompilationModuleGroup.cs",
    "Compiler/CompilerTypeSystemContext.Validation.cs",
    "Compiler/CompilerTypeSystemContext.cs",
    "Compiler/Dataflow/DynamicallyAccessedMembersBinder.cs",
    "Compiler/Dataflow/EcmaExtensions.cs",
    "Compiler/Dataflow/GenericParameterProxy.cs",
    "Compiler/Dataflow/MethodProxy.cs",
    "Compiler/Dataflow/ParameterProxy.cs",
    "Compiler/Dataflow/TypeExtensions.cs",
    "Compiler/Dataflow/TypeProxy.cs",
    "Compiler/DependencyAnalysis/AssemblyStubNode.cs",
    "Compiler/DependencyAnalysis/CompilerComparer.cs",
    "Compiler/DependencyAnalysis/EmbeddedDataContainerNode.cs",
    "Compiler/DependencyAnalysis/IMethodBodyNode.cs",
    "Compiler/DependencyAnalysis/IMethodNode.cs",
    "Compiler/DependencyAnalysis/INodeWithCodeInfo.cs",
    "Compiler/DependencyAnalysis/INodeWithRuntimeDeterminedDependencies.cs",
    "Compiler/DependencyAnalysis/ISortableNode.cs",
    "Compiler/DependencyAnalysis/ISymbolNode.cs",
    "Compiler/DependencyAnalysis/MethodReadOnlyDataNode.cs",
    "Compiler/DependencyAnalysis/ObjectDataBuilder.cs",
    "Compiler/DependencyAnalysis/ObjectNode.cs",
    "Compiler/DependencyAnalysis/ObjectNodeSection.cs",
    "Compiler/DependencyAnalysis/Relocation.cs",
    "Compiler/DependencyAnalysis/ShadowConcreteMethodNode.cs",
    "Compiler/DependencyAnalysis/SortableDependencyNode.cs",
    "Compiler/DependencyAnalysis/Target_ARM/ARMEmitter.cs",
    "Compiler/DependencyAnalysis/Target_ARM/Register.cs",
    "Compiler/DependencyAnalysis/Target_ARM/TargetRegisterMap.cs",
    "Compiler/DependencyAnalysis/Target_ARM64/ARM64Emitter.cs",
    "Compiler/DependencyAnalysis/Target_ARM64/AddrMode.cs",
    "Compiler/DependencyAnalysis/Target_ARM64/Register.cs",
    "Compiler/DependencyAnalysis/Target_ARM64/TargetRegisterMap.cs",
    "Compiler/DependencyAnalysis/Target_LoongArch64/AddrMode.cs",
    "Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64Emitter.cs",
    "Compiler/DependencyAnalysis/Target_LoongArch64/Register.cs",
    "Compiler/DependencyAnalysis/Target_LoongArch64/TargetRegisterMap.cs",
    "Compiler/DependencyAnalysis/Target_RiscV64/AddrMode.cs",
    "Compiler/DependencyAnalysis/Target_RiscV64/Register.cs",
    "Compiler/DependencyAnalysis/Target_RiscV64/RiscV64Emitter.cs",
    "Compiler/DependencyAnalysis/Target_RiscV64/TargetRegisterMap.cs",
    "Compiler/DependencyAnalysis/Target_X64/AddrMode.cs",
    "Compiler/DependencyAnalysis/Target_X64/Register.cs",
    "Compiler/DependencyAnalysis/Target_X64/TargetRegisterMap.cs",
    "Compiler/DependencyAnalysis/Target_X64/X64Emitter.cs",
    "Compiler/DependencyAnalysis/Target_X86/AddrMode.cs",
    "Compiler/DependencyAnalysis/Target_X86/Register.cs",
    "Compiler/DependencyAnalysis/Target_X86/TargetRegisterMap.cs",
    "Compiler/DependencyAnalysis/Target_X86/X86Emitter.cs",
    "Compiler/DependencyTrackingLevel.cs",
    "Compiler/DevirtualizationManager.cs",
    "Compiler/DisplayNameHelpers.cs",
    "Compiler/EventPseudoDesc.cs",
    "Compiler/FeatureSettings.cs",
    "Compiler/GenericCycleDetection/Graph.Cycles.cs",
    "Compiler/GenericCycleDetection/Graph.Vertex.cs",
    "Compiler/GenericCycleDetection/Graph.cs",
    "Compiler/GenericCycleDetection/GraphBuilder.ForEach.cs",
    "Compiler/GenericCycleDetection/GraphBuilder.MethodCall.cs",
    "Compiler/GenericCycleDetection/GraphBuilder.cs",
    "Compiler/GenericCycleDetection/ModuleCycleInfo.cs",
    "Compiler/HardwareIntrinsicHelpers.cs",
    "Compiler/ICompilationRootProvider.cs",
    "Compiler/InstructionSetSupport.cs",
    "Compiler/Int128FieldLayoutAlgorithm.cs",
    "Compiler/InternalCompilerErrorException.cs",
    "Compiler/MethodExtensions.cs",
    "Compiler/NameMangler.cs",
    "Compiler/NativeAotNameMangler.cs",
    "Compiler/ProcessLinkerXmlBase.cs",
    "Compiler/PropertyPseudoDesc.cs",
    "Compiler/PseudoDescExtensions.cs",
    "Compiler/SingleMethodRootProvider.cs",
    "Compiler/TypeExtensions.cs",
    "Compiler/TypePreserve.cs",
    "Compiler/VectorFieldLayoutAlgorithm.cs",
    "Compiler/Win32Resources/ResourceData.Reader.cs",
    "Compiler/Win32Resources/ResourceData.ResourcesDataModel.cs",
    "Compiler/Win32Resources/ResourceData.UpdateResourceDataModel.cs",
    "Compiler/Win32Resources/ResourceData.Win32Structs.cs",
    "Compiler/Win32Resources/ResourceData.cs",
    "InstructionSetHelpers.cs",
    "Internal/LowLevelLinq/LowLevelEnumerable.ToArray.cs",
    "Internal/LowLevelLinq/LowLevelEnumerable.cs",
    "Internal/Metadata/NativeFormat/Generator/CsWriter.cs",
    "Internal/Metadata/NativeFormat/Generator/MdBinaryReaderGen.cs",
    "Internal/Metadata/NativeFormat/Generator/MdBinaryWriterGen.cs",
    "Internal/Metadata/NativeFormat/Generator/Program.cs",
    "Internal/Metadata/NativeFormat/Generator/PublicGen.cs",
    "Internal/Metadata/NativeFormat/Generator/ReaderGen.cs",
    "Internal/Metadata/NativeFormat/Generator/SchemaDef.cs",
    "Internal/Metadata/NativeFormat/Generator/WriterGen.cs",
    "Internal/Metadata/NativeFormat/MdBinaryReader.cs",
    "Internal/Metadata/NativeFormat/MdBinaryReaderGen.cs",
    "Internal/Metadata/NativeFormat/MetadataTypeHashingAlgorithms.cs",
    "Internal/Metadata/NativeFormat/NativeFormatReaderCommonGen.cs",
    "Internal/Metadata/NativeFormat/NativeFormatReaderGen.cs",
    "Internal/Metadata/NativeFormat/NativeMetadataReader.cs",
    "Internal/NativeFormat/NativeFormat.cs",
    "Internal/NativeFormat/NativeFormatReader.Metadata.cs",
    "Internal/NativeFormat/NativeFormatReader.Primitives.cs",
    "Internal/NativeFormat/NativeFormatReader.String.cs",
    "Internal/NativeFormat/NativeFormatReader.cs",
    "Internal/NativeFormat/NativeFormatWriter.Primitives.cs",
    "Internal/NativeFormat/NativeFormatWriter.cs",
    "Internal/NativeFormat/NativeFormatWriterExtensions.cs",
    "Internal/Runtime/CorConstants.cs",
    "Internal/Runtime/DehydratedData.cs",
    "Internal/Runtime/EETypeBuilderHelpers.cs",
    "Internal/Runtime/GCDescEncoder.cs",
    "Internal/Runtime/ITargetBinaryWriter.cs",
    "Internal/Runtime/InterfaceDispatchCellCachePointerFlags.cs",
    "Internal/Runtime/InteropConstants.cs",
    "Internal/Runtime/MappingTableFlags.cs",
    "Internal/Runtime/MetadataBlob.cs",
    "Internal/Runtime/MethodTable.Constants.cs",
    "Internal/Runtime/ModuleHeaders.cs",
    "Internal/Runtime/ReadyToRunConstants.cs",
    "Internal/Runtime/ReadyToRunInstructionSet.cs",
    "Internal/Runtime/ReadyToRunInstructionSetHelper.cs",
    "Internal/Runtime/RiscVLoongArch64FpStruct.cs",
    "Internal/Runtime/RuntimeConstants.cs",
    "Internal/Runtime/StackTraceData.cs",
    "Internal/Text/Utf8String.cs",
    "Internal/Text/Utf8StringBuilder.cs",
    "JitInterface/CorInfoHelpFunc.cs",
    "JitInterface/CorInfoImpl.cs",
    "JitInterface/CorInfoImpl_generated.cs",
    "JitInterface/CorInfoInstructionSet.cs",
    "JitInterface/CorInfoTypes.VarInfo.cs",
    "JitInterface/CorInfoTypes.cs",
    "JitInterface/IJitHashableOnly.cs",
    "JitInterface/JitConfigProvider.cs",
    "JitInterface/JitTypeNameFormatter.cs",
    "JitInterface/SwiftPhysicalLowering.cs",
    "JitInterface/SystemVStructClassificator.cs",
    "JitInterface/ThunkGenerator/InstructionSetGenerator.cs",
    "JitInterface/ThunkGenerator/Program.cs",
    "JitInterface/UnboxingMethodDesc.cs",
    "JitInterface/UnboxingMethodDescFactory.cs",
    "Microsoft/SourceLink/Tools/SourceLinkMap.cs",
    "Pgo/PgoFormat.cs",
    "Pgo/TypeSystemEntityOrUnknown.cs",
    "Sorting/ArrayAccessor.cs",
    "Sorting/ICompareAsEqualAction.cs",
    "Sorting/ISortableDataStructureAccessor.cs",
    "Sorting/ListAccessor.cs",
    "Sorting/MergeSort.cs",
    "Sorting/MergeSortCore.cs",
    "System/Collections/Generic/ArrayBuilder.cs",
    "System/FormattingHelpers.cs",
    "TypeSystem/Canon/ArrayType.Canon.cs",
    "TypeSystem/Canon/ByRefType.Canon.cs",
    "TypeSystem/Canon/CanonTypes.Diagnostic.cs",
    "TypeSystem/Canon/CanonTypes.Interop.cs",
    "TypeSystem/Canon/CanonTypes.Metadata.cs",
    "TypeSystem/Canon/CanonTypes.Sorting.cs",
    "TypeSystem/Canon/CanonTypes.cs",
    "TypeSystem/Canon/DefType.Canon.cs",
    "TypeSystem/Canon/FunctionPointerType.Canon.cs",
    "TypeSystem/Canon/GenericParameterDesc.Canon.cs",
    "TypeSystem/Canon/InstantiatedMethod.Canon.cs",
    "TypeSystem/Canon/InstantiatedType.Canon.cs",
    "TypeSystem/Canon/MetadataType.Canon.cs",
    "TypeSystem/Canon/MethodDelegator.Canon.cs",
    "TypeSystem/Canon/MethodDesc.Canon.cs",
    "TypeSystem/Canon/MethodForInstantiatedType.Canon.cs",
    "TypeSystem/Canon/ParameterizedType.Canon.cs",
    "TypeSystem/Canon/PointerType.Canon.cs",
    "TypeSystem/Canon/SignatureVariable.Canon.cs",
    "TypeSystem/Canon/StandardCanonicalizationAlgorithm.cs",
    "TypeSystem/Canon/TypeDesc.Canon.cs",
    "TypeSystem/Canon/TypeSystemContext.Canon.cs",
    "TypeSystem/CodeGen/FieldDesc.CodeGen.cs",
    "TypeSystem/CodeGen/INonEmittableType.cs",
    "TypeSystem/CodeGen/MethodDelegator.CodeGen.cs",
    "TypeSystem/CodeGen/MethodDesc.CodeGen.cs",
    "TypeSystem/CodeGen/NativeStructType.CodeGen.cs",
    "TypeSystem/CodeGen/TargetDetails.CodeGen.cs",
    "TypeSystem/CodeGen/TypeDesc.CodeGen.cs",
    "TypeSystem/Common/AlignmentHelper.cs",
    "TypeSystem/Common/ArrayMethod.Diagnostic.cs",
    "TypeSystem/Common/ArrayOfTRuntimeInterfacesAlgorithm.cs",
    "TypeSystem/Common/ArrayType.cs",
    "TypeSystem/Common/BaseTypeRuntimeInterfacesAlgorithm.cs",
    "TypeSystem/Common/ByRefType.cs",
    "TypeSystem/Common/CastingHelper.TypeEquivalence.cs",
    "TypeSystem/Common/CastingHelper.cs",
    "TypeSystem/Common/ConstructedTypeRewritingHelpers.cs",
    "TypeSystem/Common/DefType.Diagnostic.cs",
    "TypeSystem/Common/DefType.Dummy.Diagnostic.cs",
    "TypeSystem/Common/DefType.FieldLayout.cs",
    "TypeSystem/Common/DefType.cs",
    "TypeSystem/Common/ExceptionStringID.cs",
    "TypeSystem/Common/ExplicitLayoutValidator.cs",
    "TypeSystem/Common/FieldDesc.FieldLayout.cs",
    "TypeSystem/Common/FieldDesc.ToString.cs",
    "TypeSystem/Common/FieldDesc.cs",
    "TypeSystem/Common/FieldForInstantiatedType.FieldLayout.cs",
    "TypeSystem/Common/FieldForInstantiatedType.cs",
    "TypeSystem/Common/FieldLayoutAlgorithm.cs",
    "TypeSystem/Common/FieldLayoutIntervalCalculator.cs",
    "TypeSystem/Common/FunctionPointerType.cs",
    "TypeSystem/Common/GenericParameterDesc.Diagnostic.cs",
    "TypeSystem/Common/GenericParameterDesc.Dummy.Diagnostic.cs",
    "TypeSystem/Common/GenericParameterDesc.cs",
    "TypeSystem/Common/IAssemblyDesc.cs",
    "TypeSystem/Common/IModuleResolver.cs",
    "TypeSystem/Common/ImpliedRepeatedFieldDesc.Sorting.cs",
    "TypeSystem/Common/ImpliedRepeatedFieldDesc.cs",
    "TypeSystem/Common/InstantiatedMethod.Diagnostic.cs",
    "TypeSystem/Common/InstantiatedMethod.cs",
    "TypeSystem/Common/InstantiatedType.Diagnostic.cs",
    "TypeSystem/Common/InstantiatedType.Interfaces.cs",
    "TypeSystem/Common/InstantiatedType.Metadata.cs",
    "TypeSystem/Common/InstantiatedType.MethodImpls.cs",
    "TypeSystem/Common/InstantiatedType.TypeEquivalence.cs",
    "TypeSystem/Common/InstantiatedType.cs",
    "TypeSystem/Common/Instantiation.cs",
    "TypeSystem/Common/LayoutInt.cs",
    "TypeSystem/Common/LocalVariableDefinition.cs",
    "TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs",
    "TypeSystem/Common/MetadataRuntimeInterfacesAlgorithm.cs",
    "TypeSystem/Common/MetadataType.Interfaces.cs",
    "TypeSystem/Common/MetadataType.MethodImpls.cs",
    "TypeSystem/Common/MetadataType.cs",
    "TypeSystem/Common/MetadataTypeSystemContext.cs",
    "TypeSystem/Common/MetadataVirtualMethodAlgorithm.cs",
    "TypeSystem/Common/MethodDelegator.Diagnostic.cs",
    "TypeSystem/Common/MethodDelegator.cs",
    "TypeSystem/Common/MethodDesc.Diagnostic.cs",
    "TypeSystem/Common/MethodDesc.Dummy.Diagnostic.cs",
    "TypeSystem/Common/MethodDesc.ToString.cs",
    "TypeSystem/Common/MethodDesc.cs",
    "TypeSystem/Common/MethodForInstantiatedType.Diagnostic.cs",
    "TypeSystem/Common/MethodForInstantiatedType.cs",
    "TypeSystem/Common/ModuleDesc.cs",
    "TypeSystem/Common/NotFoundBehavior.cs",
    "TypeSystem/Common/ParameterizedType.cs",
    "TypeSystem/Common/PointerType.cs",
    "TypeSystem/Common/PortableExecutableMethodExtensions.cs",
    "TypeSystem/Common/PropertySignature.cs",
    "TypeSystem/Common/ResolutionFailure.cs",
    "TypeSystem/Common/RuntimeInterfacesAlgorithm.cs",
    "TypeSystem/Common/SignatureVariable.cs",
    "TypeSystem/Common/SimpleArrayOfTRuntimeInterfacesAlgorithm.cs",
    "TypeSystem/Common/TargetArchitecture.cs",
    "TypeSystem/Common/TargetDetails.ToString.cs",
    "TypeSystem/Common/TargetDetails.cs",
    "TypeSystem/Common/ThreadSafeFlags.cs",
    "TypeSystem/Common/ThrowHelper.Common.cs",
    "TypeSystem/Common/ThrowHelper.cs",
    "TypeSystem/Common/TypeDesc.Interfaces.cs",
    "TypeSystem/Common/TypeDesc.ToString.cs",
    "TypeSystem/Common/TypeDesc.TypeEquivalence.cs",
    "TypeSystem/Common/TypeDesc.cs",
    "TypeSystem/Common/TypeFlags.cs",
    "TypeSystem/Common/TypeHashingAlgorithms.cs",
    "TypeSystem/Common/TypeSystemConstraintsHelpers.cs",
    "TypeSystem/Common/TypeSystemContext.FieldLayout.cs",
    "TypeSystem/Common/TypeSystemContext.Resolution.cs",
    "TypeSystem/Common/TypeSystemContext.cs",
    "TypeSystem/Common/TypeSystemEntity.cs",
    "TypeSystem/Common/TypeSystemException.Resources.cs",
    "TypeSystem/Common/TypeSystemException.cs",
    "TypeSystem/Common/TypeSystemHelpers.cs",
    "TypeSystem/Common/TypeWithRepeatedFields.Diagnostic.cs",
    "TypeSystem/Common/TypeWithRepeatedFields.Sorting.cs",
    "TypeSystem/Common/TypeWithRepeatedFields.cs",
    "TypeSystem/Common/TypeWithRepeatedFieldsFieldLayoutAlgorithm.cs",
    "TypeSystem/Common/UniversalCanonLayoutAlgorithm.cs",
    "TypeSystem/Common/Utilities/CustomAttributeTypeNameFormatter.cs",
    "TypeSystem/Common/Utilities/CustomAttributeTypeNameParser.cs",
    "TypeSystem/Common/Utilities/DebugNameFormatter.cs",
    "TypeSystem/Common/Utilities/ExceptionTypeNameFormatter.Metadata.cs",
    "TypeSystem/Common/Utilities/ExceptionTypeNameFormatter.cs",
    "TypeSystem/Common/Utilities/GCPointerMap.Algorithm.cs",
    "TypeSystem/Common/Utilities/GCPointerMap.cs",
    "TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs",
    "TypeSystem/Common/Utilities/LockFreeReaderHashtableOfPointers.cs",
    "TypeSystem/Common/Utilities/TypeNameFormatter.cs",
    "TypeSystem/Common/VirtualMethodAlgorithm.cs",
    "TypeSystem/Common/WellKnownType.cs",
    "TypeSystem/Ecma/CachingMetadataStringDecoder.cs",
    "TypeSystem/Ecma/CustomAttributeTypeProvider.cs",
    "TypeSystem/Ecma/EcmaAssembly.Symbols.cs",
    "TypeSystem/Ecma/EcmaAssembly.cs",
    "TypeSystem/Ecma/EcmaField.CodeGen.cs",
    "TypeSystem/Ecma/EcmaField.Sorting.cs",
    "TypeSystem/Ecma/EcmaField.cs",
    "TypeSystem/Ecma/EcmaGenericParameter.Diagnostic.cs",
    "TypeSystem/Ecma/EcmaGenericParameter.Sorting.cs",
    "TypeSystem/Ecma/EcmaGenericParameter.cs",
    "TypeSystem/Ecma/EcmaMethod.Diagnostic.cs",
    "TypeSystem/Ecma/EcmaMethod.Sorting.cs",
    "TypeSystem/Ecma/EcmaMethod.cs",
    "TypeSystem/Ecma/EcmaModule.Sorting.cs",
    "TypeSystem/Ecma/EcmaModule.Symbols.cs",
    "TypeSystem/Ecma/EcmaModule.cs",
    "TypeSystem/Ecma/EcmaSignatureEncoder.cs",
    "TypeSystem/Ecma/EcmaSignatureParser.cs",
    "TypeSystem/Ecma/EcmaSignatureTranslator.cs",
    "TypeSystem/Ecma/EcmaType.Diagnostic.cs",
    "TypeSystem/Ecma/EcmaType.Interfaces.cs",
    "TypeSystem/Ecma/EcmaType.MethodImpls.cs",
    "TypeSystem/Ecma/EcmaType.Sorting.cs",
    "TypeSystem/Ecma/EcmaType.TypeEquivalence.cs",
    "TypeSystem/Ecma/EcmaType.cs",
    "TypeSystem/Ecma/EffectiveVisibility.cs",
    "TypeSystem/Ecma/IEcmaModule.cs",
    "TypeSystem/Ecma/IMetadataStringDecoderProvider.cs",
    "TypeSystem/Ecma/MetadataExtensions.cs",
    "TypeSystem/Ecma/PrimitiveTypeProvider.cs",
    "TypeSystem/Ecma/SymbolReader/PdbSymbolReader.cs",
    "TypeSystem/Ecma/SymbolReader/PortablePdbSymbolReader.cs",
    "TypeSystem/Ecma/SymbolReader/UnmanagedPdbSymbolReader.cs",
    "TypeSystem/IL/DelegateInfo.cs",
    "TypeSystem/IL/EcmaMethodIL.Symbols.cs",
    "TypeSystem/IL/EcmaMethodIL.cs",
    "TypeSystem/IL/FlowGraph.cs",
    "TypeSystem/IL/HelperExtensions.cs",
    "TypeSystem/IL/ILDisassembler.cs",
    "TypeSystem/IL/ILImporter.cs",
    "TypeSystem/IL/ILOpcode.cs",
    "TypeSystem/IL/ILOpcodeHelper.cs",
    "TypeSystem/IL/ILProvider.cs",
    "TypeSystem/IL/ILReader.cs",
    "TypeSystem/IL/ILStackHelper.cs",
    "TypeSystem/IL/ILTokenReplacer.cs",
    "TypeSystem/IL/InstantiatedMethodIL.cs",
    "TypeSystem/IL/MethodIL.Symbols.cs",
    "TypeSystem/IL/MethodIL.cs",
    "TypeSystem/IL/MethodILDebugView.cs",
    "TypeSystem/IL/NativeAotILProvider.cs",
    "TypeSystem/IL/StackValueKind.cs",
    "TypeSystem/IL/Stubs/ArrayMethodILEmitter.cs",
    "TypeSystem/IL/Stubs/AssemblyGetExecutingAssemblyMethodThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/AssemblyGetExecutingAssemblyMethodThunk.cs",
    "TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.Mangling.cs",
    "TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.cs",
    "TypeSystem/IL/Stubs/ComparerIntrinsics.cs",
    "TypeSystem/IL/Stubs/DebuggerSteppingHelpers.cs",
    "TypeSystem/IL/Stubs/DelegateMarshallingMethodThunk.Mangling.cs",
    "TypeSystem/IL/Stubs/DelegateMarshallingMethodThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/DelegateMarshallingMethodThunk.cs",
    "TypeSystem/IL/Stubs/DelegateMethodILEmitter.cs",
    "TypeSystem/IL/Stubs/DelegateThunks.Sorting.cs",
    "TypeSystem/IL/Stubs/DelegateThunks.cs",
    "TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.Mangling.cs",
    "TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.cs",
    "TypeSystem/IL/Stubs/EnumThunks.Sorting.cs",
    "TypeSystem/IL/Stubs/EnumThunks.cs",
    "TypeSystem/IL/Stubs/ForwardDelegateCreationThunk.Mangling.cs",
    "TypeSystem/IL/Stubs/ForwardDelegateCreationThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/ForwardDelegateCreationThunk.cs",
    "TypeSystem/IL/Stubs/GetCanonTypeIntrinsic.cs",
    "TypeSystem/IL/Stubs/ILEmitter.cs",
    "TypeSystem/IL/Stubs/InterlockedIntrinsics.cs",
    "TypeSystem/IL/Stubs/MethodBaseGetCurrentMethodThunk.Mangling.cs",
    "TypeSystem/IL/Stubs/MethodBaseGetCurrentMethodThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/MethodBaseGetCurrentMethodThunk.cs",
    "TypeSystem/IL/Stubs/PInvokeILCodeStreams.cs",
    "TypeSystem/IL/Stubs/PInvokeILEmitter.cs",
    "TypeSystem/IL/Stubs/PInvokeLazyFixupField.Sorting.cs",
    "TypeSystem/IL/Stubs/PInvokeLazyFixupField.cs",
    "TypeSystem/IL/Stubs/PInvokeTargetNativeMethod.Diagnostic.cs",
    "TypeSystem/IL/Stubs/PInvokeTargetNativeMethod.Mangling.cs",
    "TypeSystem/IL/Stubs/PInvokeTargetNativeMethod.Sorting.cs",
    "TypeSystem/IL/Stubs/PInvokeTargetNativeMethod.cs",
    "TypeSystem/IL/Stubs/RuntimeHelpersIntrinsics.cs",
    "TypeSystem/IL/Stubs/StreamIntrinsics.cs",
    "TypeSystem/IL/Stubs/StructMarshallingThunk.Mangling.cs",
    "TypeSystem/IL/Stubs/StructMarshallingThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/StructMarshallingThunk.cs",
    "TypeSystem/IL/Stubs/TypeGetTypeMethodThunk.Sorting.cs",
    "TypeSystem/IL/Stubs/TypeGetTypeMethodThunk.cs",
    "TypeSystem/IL/Stubs/TypeSystemThrowingILEmitter.cs",
    "TypeSystem/IL/Stubs/UnsafeIntrinsics.cs",
    "TypeSystem/IL/Stubs/ValueTypeGetFieldHelperMethodOverride.Sorting.cs",
    "TypeSystem/IL/Stubs/ValueTypeGetFieldHelperMethodOverride.cs",
    "TypeSystem/IL/UnsafeAccessors.cs",
    "TypeSystem/Interop/FieldDesc.Interop.cs",
    "TypeSystem/Interop/IL/InlineArrayType.Sorting.cs",
    "TypeSystem/Interop/IL/InlineArrayType.cs",
    "TypeSystem/Interop/IL/MarshalHelpers.Aot.cs",
    "TypeSystem/Interop/IL/MarshalHelpers.cs",
    "TypeSystem/Interop/IL/MarshalUtils.cs",
    "TypeSystem/Interop/IL/Marshaller.Aot.cs",
    "TypeSystem/Interop/IL/Marshaller.cs",
    "TypeSystem/Interop/IL/MarshallerKind.cs",
    "TypeSystem/Interop/IL/NativeStructType.Mangling.cs",
    "TypeSystem/Interop/IL/NativeStructType.Sorting.cs",
    "TypeSystem/Interop/IL/NativeStructType.cs",
    "TypeSystem/Interop/IL/PInvokeDelegateWrapper.Mangling.cs",
    "TypeSystem/Interop/IL/PInvokeDelegateWrapper.Sorting.cs",
    "TypeSystem/Interop/IL/PInvokeDelegateWrapper.cs",
    "TypeSystem/Interop/IL/PInvokeDelegateWrapperConstructor.Sorting.cs",
    "TypeSystem/Interop/IL/PInvokeDelegateWrapperConstructor.cs",
    "TypeSystem/Interop/IL/PInvokeILEmitterConfiguration.cs",
    "TypeSystem/Interop/InstantiatedType.Interop.cs",
    "TypeSystem/Interop/InteropStateManager.cs",
    "TypeSystem/Interop/InteropTypes.cs",
    "TypeSystem/Interop/MarshalAsDescriptor.cs",
    "TypeSystem/Interop/MetadataType.Interop.cs",
    "TypeSystem/Interop/MethodDelegator.Interop.cs",
    "TypeSystem/Interop/MethodDesc.Interop.cs",
    "TypeSystem/Interop/UnmanagedCallingConventions.cs",
    "TypeSystem/Mangling/IPrefixMangledMethod.cs",
    "TypeSystem/Mangling/IPrefixMangledSignature.cs",
    "TypeSystem/Mangling/IPrefixMangledType.cs",
    "TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs",
    "TypeSystem/RuntimeDetermined/ArrayType.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/ByRefType.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/DefType.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/FieldDesc.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/FunctionPointerType.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/GenericParameterDesc.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/MethodDesc.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/MethodForRuntimeDeterminedType.Diagnostic.cs",
    "TypeSystem/RuntimeDetermined/MethodForRuntimeDeterminedType.Sorting.cs",
    "TypeSystem/RuntimeDetermined/MethodForRuntimeDeterminedType.cs",
    "TypeSystem/RuntimeDetermined/ParameterizedType.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/PointerType.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/RuntimeDeterminedCanonicalizationAlgorithm.cs",
    "TypeSystem/RuntimeDetermined/RuntimeDeterminedFieldLayoutAlgorithm.cs",
    "TypeSystem/RuntimeDetermined/RuntimeDeterminedType.Diagnostic.cs",
    "TypeSystem/RuntimeDetermined/RuntimeDeterminedType.Sorting.cs",
    "TypeSystem/RuntimeDetermined/RuntimeDeterminedType.cs",
    "TypeSystem/RuntimeDetermined/RuntimeDeterminedTypeUtilities.cs",
    "TypeSystem/RuntimeDetermined/SignatureVariable.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/TypeDesc.RuntimeDetermined.cs",
    "TypeSystem/RuntimeDetermined/TypeSystemContext.RuntimeDetermined.cs",
    "TypeSystem/Sorting/ArrayType.Sorting.cs",
    "TypeSystem/Sorting/ByRefType.Sorting.cs",
    "TypeSystem/Sorting/FieldDesc.Sorting.cs",
    "TypeSystem/Sorting/FieldForInstantiatedType.Sorting.cs",
    "TypeSystem/Sorting/FunctionPointerType.Sorting.cs",
    "TypeSystem/Sorting/InstantiatedMethod.Sorting.cs",
    "TypeSystem/Sorting/InstantiatedType.Sorting.cs",
    "TypeSystem/Sorting/MethodDesc.Sorting.cs",
    "TypeSystem/Sorting/MethodForInstantiatedType.Sorting.cs",
    "TypeSystem/Sorting/MethodSignature.Sorting.cs",
    "TypeSystem/Sorting/PointerType.Sorting.cs",
    "TypeSystem/Sorting/SignatureVariable.Sorting.cs",
    "TypeSystem/Sorting/TypeDesc.Sorting.cs",
    "TypeSystem/Sorting/TypeSystemComparer.cs",
    "TypeSystem/TypesDebugInfoWriter/TypesDebugInfoWriter.cs",
])
