load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.Formats.Asn1",
    srcs = [
        "ref/System.Formats.Asn1.cs",
    ],
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
    ],
    defines = [
        "NET9_0_OR_GREATER",
    ]
)

netcoreapp_impl_assembly(
    name = "impl_System.Formats.Asn1",
    multitarget = True,
    skip_cs1591 = True,
    defines = ["CP_NO_ZEROMEMORY"],
    srcs = [
        "src/System/Formats/Asn1/Asn1Tag.Accelerators.cs",
        "src/System/Formats/Asn1/Asn1Tag.cs",
        "src/System/Formats/Asn1/AsnCharacterStringEncodings.cs",
        "src/System/Formats/Asn1/AsnContentException.cs",
        "src/System/Formats/Asn1/AsnDecoder.BitString.cs",
        "src/System/Formats/Asn1/AsnDecoder.Boolean.cs",
        "src/System/Formats/Asn1/AsnDecoder.Enumerated.cs",
        "src/System/Formats/Asn1/AsnDecoder.GeneralizedTime.cs",
        "src/System/Formats/Asn1/AsnDecoder.Integer.cs",
        "src/System/Formats/Asn1/AsnDecoder.NamedBitList.cs",
        "src/System/Formats/Asn1/AsnDecoder.Null.cs",
        "src/System/Formats/Asn1/AsnDecoder.OctetString.cs",
        "src/System/Formats/Asn1/AsnDecoder.Oid.cs",
        "src/System/Formats/Asn1/AsnDecoder.Sequence.cs",
        "src/System/Formats/Asn1/AsnDecoder.SetOf.cs",
        "src/System/Formats/Asn1/AsnDecoder.Text.cs",
        "src/System/Formats/Asn1/AsnDecoder.UtcTime.cs",
        "src/System/Formats/Asn1/AsnDecoder.cs",
        "src/System/Formats/Asn1/AsnEncodingRules.cs",
        "src/System/Formats/Asn1/AsnReaderOptions.cs",
        "src/System/Formats/Asn1/AsnWriter.BitString.cs",
        "src/System/Formats/Asn1/AsnWriter.Boolean.cs",
        "src/System/Formats/Asn1/AsnWriter.Enumerated.cs",
        "src/System/Formats/Asn1/AsnWriter.GeneralizedTime.cs",
        "src/System/Formats/Asn1/AsnWriter.Integer.cs",
        "src/System/Formats/Asn1/AsnWriter.NamedBitList.cs",
        "src/System/Formats/Asn1/AsnWriter.Null.cs",
        "src/System/Formats/Asn1/AsnWriter.OctetString.cs",
        "src/System/Formats/Asn1/AsnWriter.Oid.cs",
        "src/System/Formats/Asn1/AsnWriter.Sequence.cs",
        "src/System/Formats/Asn1/AsnWriter.SetOf.cs",
        "src/System/Formats/Asn1/AsnWriter.Text.cs",
        "src/System/Formats/Asn1/AsnWriter.UtcTime.cs",
        "src/System/Formats/Asn1/AsnWriter.cs",
        "src/System/Formats/Asn1/SetOfValueComparer.cs",
        "src/System/Formats/Asn1/TagClass.cs",
        "src/System/Formats/Asn1/UniversalTagNumber.cs",
        "src/System/Formats/Asn1/WellKnownOids.cs",
    ] + [
        "//src/libraries/Common:src/System/Security/Cryptography/CryptoPool.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
    ],
    assembly_description = "Provides classes that can read and write the ASN.1 BER, CER, and DER data formats.",
)
