load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Reflection.Emit.Tests",
    srcs = [
        "AssemblyBuilderTests.cs",
        "ConstructorBuilder/ConstructorBuilderDefineParameter.cs",
        "ConstructorBuilder/ConstructorBuilderGetILGenerator.cs",
        "ConstructorBuilder/ConstructorBuilderInitLocals.cs",
        "ConstructorBuilder/ConstructorBuilderSetCustomAttribute.cs",
        "ConstructorBuilder/ConstructorBuilderSetImplementationFlags.cs",
        "ConstructorBuilder/ConstructorBuilderToString.cs",
        "EnumBuilder/EnumBuilder.Methods.Tests.cs",
        "EnumBuilder/EnumBuilder.Properties.Tests.cs",
        "EventBuilder/EventBuilderAddOtherMethod.cs",
        "EventBuilder/EventBuilderSetAddOnMethod.cs",
        "EventBuilder/EventBuilderSetCustomAttribute.cs",
        "EventBuilder/EventBuilderSetRaiseMethod.cs",
        "EventBuilder/EventBuilderSetRemoveOnMethod.cs",
        "FieldBuilder/FieldBuilderGetValue.cs",
        "FieldBuilder/FieldBuilderSetConstant.cs",
        "FieldBuilder/FieldBuilderSetCustomAttribute.cs",
        "FieldBuilder/FieldBuilderSetOffset.cs",
        "GenericTypeParameterBuilder/GenericTyepParameterBuilderSetBaseTypeConstraint.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderGUID.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderIsByRefLike.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderMakeArrayType.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderMakeByRefType.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderMakeGenericType.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderMakePointerType.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderSetCustomAttribute.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderSetGenericParameterAttributes.cs",
        "GenericTypeParameterBuilder/GenericTypeParameterBuilderSetInterfaceConstraints.cs",
        "MethodBuilder/MethodBuilderByRefs.cs",
        "MethodBuilder/MethodBuilderContainsGenericParameters.cs",
        "MethodBuilder/MethodBuilderDefineGenericParameters.cs",
        "MethodBuilder/MethodBuilderDefineParameter.cs",
        "MethodBuilder/MethodBuilderEquals.cs",
        "MethodBuilder/MethodBuilderGetGenericArguments.cs",
        "MethodBuilder/MethodBuilderGetGenericMethodDefinition.cs",
        "MethodBuilder/MethodBuilderGetHashCode.cs",
        "MethodBuilder/MethodBuilderGetILGenerator.cs",
        "MethodBuilder/MethodBuilderInitLocals.cs",
        "MethodBuilder/MethodBuilderIsGenericMethod.cs",
        "MethodBuilder/MethodBuilderMakeGenericMethod.cs",
        "MethodBuilder/MethodBuilderReturnParameter.cs",
        "MethodBuilder/MethodBuilderSetCustomAttribute.cs",
        "MethodBuilder/MethodBuilderSetImplementationFlags.cs",
        "MethodBuilder/MethodBuilderSetParameters.cs",
        "MethodBuilder/MethodBuilderSetReturnType.cs",
        "MethodBuilder/MethodBuilderSetSignature.cs",
        "MethodBuilder/MethodBuilderToString.cs",
        "ModuleBuilder/ModuleBuilderCreateGlobalFunctions.cs",
        "ModuleBuilder/ModuleBuilderDefineEnum.cs",
        "ModuleBuilder/ModuleBuilderDefineInitializedData.cs",
        "ModuleBuilder/ModuleBuilderDefinePInvokeMethod.cs",
        "ModuleBuilder/ModuleBuilderDefineType.cs",
        "ModuleBuilder/ModuleBuilderDefineUninitializedData.cs",
        "ModuleBuilder/ModuleBuilderGetArrayMethod.cs",
        "ModuleBuilder/ModuleBuilderSetCustomAttribute.cs",
        "OpCodesTests.cs",
        "ParameterBuilder/ParameterBuilderSetConstant.cs",
        "PersistedAssemblyBuilder/AssemblySaveAssemblyBuilderTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveConstructorBuilderTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveCustomAttributeTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveEnumBuilderTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveEventBuilderTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveILGeneratorTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveModuleBuilderTests.cs",
        "PersistedAssemblyBuilder/AssemblySavePropertyBuilderTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveResourceTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveTools.cs",
        "PersistedAssemblyBuilder/AssemblySaveTypeBuilderAPIsTests.cs",
        "PersistedAssemblyBuilder/AssemblySaveTypeBuilderTests.cs",
        "PortablePdb/ILGeneratorScopesAndSequencePointsTests.cs",
        "PortablePdb/PortablePdbStandalonePdbTest.cs",
        "PropertyBuilder/PropertyBuilderAddOtherMethod.cs",
        "PropertyBuilder/PropertyBuilderAttributes.cs",
        "PropertyBuilder/PropertyBuilderCanRead.cs",
        "PropertyBuilder/PropertyBuilderCanWrite.cs",
        "PropertyBuilder/PropertyBuilderDeclaringType.cs",
        "PropertyBuilder/PropertyBuilderGetIndexParameters.cs",
        "PropertyBuilder/PropertyBuilderGetValue.cs",
        "PropertyBuilder/PropertyBuilderSetConstant.cs",
        "PropertyBuilder/PropertyBuilderSetCustomAttribute.cs",
        "PropertyBuilder/PropertyBuilderSetGetMethod.cs",
        "PropertyBuilder/PropertyBuilderSetSetMethod.cs",
        "PropertyBuilder/PropertyBuilderSetValue.cs",
        "TypeBuilder/TypeBuilderAddInterfaceImplementation.cs",
        "TypeBuilder/TypeBuilderAssemblyQualifiedName.cs",
        "TypeBuilder/TypeBuilderCreateType.cs",
        "TypeBuilder/TypeBuilderCreateTypeInfo.cs",
        "TypeBuilder/TypeBuilderDeclaringMethod.cs",
        "TypeBuilder/TypeBuilderDefineConstructor.cs",
        "TypeBuilder/TypeBuilderDefineDefaultConstructor.cs",
        "TypeBuilder/TypeBuilderDefineEvent.cs",
        "TypeBuilder/TypeBuilderDefineField.cs",
        "TypeBuilder/TypeBuilderDefineGenericParameters.cs",
        "TypeBuilder/TypeBuilderDefineMethod.cs",
        "TypeBuilder/TypeBuilderDefineMethodOverride.cs",
        "TypeBuilder/TypeBuilderDefineNestedType.cs",
        "TypeBuilder/TypeBuilderDefinePInvokeMethod.cs",
        "TypeBuilder/TypeBuilderDefineProperty.cs",
        "TypeBuilder/TypeBuilderDefineTypeInitializer.cs",
        "TypeBuilder/TypeBuilderGUID.cs",
        "TypeBuilder/TypeBuilderGenericParameterAttributes.cs",
        "TypeBuilder/TypeBuilderGenericParameterPosition.cs",
        "TypeBuilder/TypeBuilderGetConstructor.cs",
        "TypeBuilder/TypeBuilderGetElementType.cs",
        "TypeBuilder/TypeBuilderGetField.cs",
        "TypeBuilder/TypeBuilderGetGenericTypeDefinition.cs",
        "TypeBuilder/TypeBuilderGetMethod.cs",
        "TypeBuilder/TypeBuilderIsByRefLike.cs",
        "TypeBuilder/TypeBuilderIsGenericParameter.cs",
        "TypeBuilder/TypeBuilderIsGenericType.cs",
        "TypeBuilder/TypeBuilderIsGenericTypeDefinition.cs",
        "TypeBuilder/TypeBuilderMakeArrayType.cs",
        "TypeBuilder/TypeBuilderMakeByRefType.cs",
        "TypeBuilder/TypeBuilderMakeGenericType.cs",
        "TypeBuilder/TypeBuilderMakePointerType.cs",
        "TypeBuilder/TypeBuilderName.cs",
        "TypeBuilder/TypeBuilderNamespace.cs",
        "TypeBuilder/TypeBuilderPackingSize.cs",
        "TypeBuilder/TypeBuilderSetCustomAttribute.cs",
        "TypeBuilder/TypeBuilderSetParent.cs",
        "TypeBuilder/TypeBuilderSize.cs",
        "TypeBuilder/TypeBuilderToString.cs",
        "Utilities.cs",
    ] + [
        "//src/libraries/Common/tests:System/IO/TempFile.cs",
    ],
    deps = [
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.MetadataLoadContext:live_System.Reflection.MetadataLoadContext",
        "//src/libraries/System.Reflection.Metadata:ref_System.Reflection.Metadata",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Diagnostics.StackTrace:ref_System.Diagnostics.StackTrace",
        "//src/libraries/System.Resources.Writer:ref_System.Resources.Writer",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
