# Headers for the JIT compiler.
# The compiled JIT library will be added later.

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//src/coreclr:__subpackages__"])

cc_library(
    name = "jit_headers",
    hdrs = glob(
        [
            "*.h",
            "*.hpp",
            "*.def",
            "jitstd/*.h",
        ],
        allow_empty = True,
    ),
)
