load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Collections.Tests",
    srcs = [
        "BitArray/BitArray_CtorTests.cs",
        "BitArray/BitArray_GetSetTests.cs",
        "BitArray/BitArray_OperatorsTests.cs",
        "Generic/CollectionExtensionsTests.cs",
        "Generic/Comparers/Comparer.Generic.Tests.cs",
        "Generic/Comparers/Comparer.Tests.cs",
        "Generic/Comparers/Comparers.Generic.cs",
        "Generic/Comparers/EqualityComparer.Generic.Serialization.Tests.cs",
        "Generic/Comparers/EqualityComparer.Generic.Tests.cs",
        "Generic/Comparers/EqualityComparer.Tests.cs",
        "Generic/Comparers/ReferenceEqualityComparer.Tests.cs",
        "Generic/Dictionary/Dictionary.Generic.Tests.ConcurrentAccessDetection.cs",
        "Generic/Dictionary/Dictionary.Generic.Tests.Keys.cs",
        "Generic/Dictionary/Dictionary.Generic.Tests.Values.cs",
        "Generic/Dictionary/Dictionary.Generic.Tests.cs",
        "Generic/Dictionary/Dictionary.Generic.cs",
        "Generic/Dictionary/Dictionary.Tests.cs",
        "Generic/Dictionary/HashCollisionScenarios/InputData.cs",
        "Generic/Dictionary/HashCollisionScenarios/OutOfBoundsRegression.cs",
        "Generic/HashSet/HashSet.Generic.Tests.AsNonGenericIEnumerable.cs",
        "Generic/HashSet/HashSet.Generic.Tests.cs",
        "Generic/HashSet/HashSet.Generic.cs",
        "Generic/HashSet/HashSet.NonGeneric.Tests.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.AddAfter.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.AddBefore.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.AddFirst.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.AddLast.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.AsNonGenericICollection.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.Constructor.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.Find.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.FindLast.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.Node.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.RemoveFirst.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.RemoveLast.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.RemoveNode.cs",
        "Generic/LinkedList/LinkedList.Generic.Tests.cs",
        "Generic/LinkedList/LinkedList.Generic.cs",
        "Generic/List/List.Generic.Tests.AddRange.cs",
        "Generic/List/List.Generic.Tests.AsNonGenericIList.cs",
        "Generic/List/List.Generic.Tests.BinarySearch.cs",
        "Generic/List/List.Generic.Tests.Constructor.cs",
        "Generic/List/List.Generic.Tests.ConvertAll.cs",
        "Generic/List/List.Generic.Tests.CopyTo.cs",
        "Generic/List/List.Generic.Tests.EnsureCapacity.cs",
        "Generic/List/List.Generic.Tests.Find.cs",
        "Generic/List/List.Generic.Tests.ForEach.cs",
        "Generic/List/List.Generic.Tests.IndexOf.cs",
        "Generic/List/List.Generic.Tests.InsertRange.cs",
        "Generic/List/List.Generic.Tests.Misc.cs",
        "Generic/List/List.Generic.Tests.Remove.cs",
        "Generic/List/List.Generic.Tests.Reverse.cs",
        "Generic/List/List.Generic.Tests.Sort.cs",
        "Generic/List/List.Generic.Tests.cs",
        "Generic/List/List.Generic.cs",
        "Generic/OrderedDictionary/OrderedDictionary.Generic.Tests.Keys.cs",
        "Generic/OrderedDictionary/OrderedDictionary.Generic.Tests.Values.cs",
        "Generic/OrderedDictionary/OrderedDictionary.Generic.Tests.cs",
        "Generic/OrderedDictionary/OrderedDictionary.Generic.cs",
        "Generic/OrderedDictionary/OrderedDictionary.IList.Tests.cs",
        "Generic/OrderedDictionary/OrderedDictionary.Tests.cs",
        "Generic/PriorityQueue/PriorityQueue.Generic.Tests.cs",
        "Generic/PriorityQueue/PriorityQueue.Generic.cs",
        "Generic/PriorityQueue/PriorityQueue.PropertyTests.cs",
        "Generic/PriorityQueue/PriorityQueue.Tests.Dijkstra.cs",
        "Generic/PriorityQueue/PriorityQueue.Tests.cs",
        "Generic/Queue/Queue.Generic.Tests.cs",
        "Generic/Queue/Queue.Generic.cs",
        "Generic/Queue/Queue.Tests.cs",
        "Generic/ReadOnlySet/ReadOnlySetTests.cs",
        "Generic/SortedDictionary/SortedDictionary.Generic.Tests.Keys.cs",
        "Generic/SortedDictionary/SortedDictionary.Generic.Tests.Values.cs",
        "Generic/SortedDictionary/SortedDictionary.Generic.Tests.cs",
        "Generic/SortedDictionary/SortedDictionary.Generic.cs",
        "Generic/SortedDictionary/SortedDictionary.Tests.cs",
        "Generic/SortedList/SortedList.Generic.Tests.Keys.cs",
        "Generic/SortedList/SortedList.Generic.Tests.Values.cs",
        "Generic/SortedList/SortedList.Generic.Tests.cs",
        "Generic/SortedList/SortedList.Generic.cs",
        "Generic/SortedList/SortedList.Tests.cs",
        "Generic/SortedSet/SortedSet.Generic.Tests.cs",
        "Generic/SortedSet/SortedSet.Generic.cs",
        "Generic/SortedSet/SortedSet.Tests.cs",
        "Generic/SortedSet/SortedSet.TreeSubSet.Tests.cs",
        "Generic/Stack/Stack.Generic.Tests.cs",
        "Generic/Stack/Stack.Generic.cs",
        "Generic/Stack/Stack.Tests.cs",
        "StructuralComparisonsTests.cs",
    ] + [
        # Common collection test infrastructure
        "//src/libraries/Common/tests:System/Collections/CollectionAsserts.cs",
        "//src/libraries/Common/tests:System/Collections/ICollection.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/ICollection.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.Generic.Tests.netcoreapp.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.NonGeneric.Tests.netcoreapp.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Serialization.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.Generic.Serialization.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IList.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IList.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IGenericSharedAPI.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/ISet.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/TestBase.NonGeneric.cs",
        "//src/libraries/Common/tests:System/Collections/TestBase.Generic.cs",
        "//src/libraries/Common/tests:System/Collections/DebugView.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/DictionaryEntry.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/TestingTypes.cs",
        "//src/libraries/Common/tests:System/EnumTypes.cs",
        "//src/libraries/Common/tests:System/ObjectCloner.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs",
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = [
        "SYSLIB0011",
        "SYSLIB0050",
        "SYSLIB0051",
    ],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
