load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Runtime.Numerics.Tests",
    srcs = [
        "BigInteger/BigIntTools.cs",
        "BigInteger/BigInteger.AddTests.cs",
        "BigInteger/BigInteger.SubtractTests.cs",
        "BigInteger/BigIntegerToStringTests.cs",
        "BigInteger/Comparison.cs",
        "BigInteger/DebuggerDisplayTests.cs",
        "BigInteger/Driver.cs",
        "BigInteger/GetBitLengthTests.cs",
        "BigInteger/IsEven.cs",
        "BigInteger/IsOne.cs",
        "BigInteger/IsPowerOfTwo.cs",
        "BigInteger/IsZero.cs",
        "BigInteger/MyBigInt.cs",
        "BigInteger/Rotate.cs",
        "BigInteger/SampleGeneration.cs",
        "BigInteger/ToByteArray.cs",
        "BigInteger/TryWriteBytes.cs",
        "BigInteger/UInt32Samples.cs",
        "BigInteger/absolutevalue.cs",
        "BigInteger/cast_from.cs",
        "BigInteger/cast_to.cs",
        "BigInteger/ctor.cs",
        "BigInteger/divide.cs",
        "BigInteger/divrem.cs",
        "BigInteger/gcd.cs",
        "BigInteger/log.cs",
        "BigInteger/log02.cs",
        "BigInteger/log10.cs",
        "BigInteger/max.cs",
        "BigInteger/min.cs",
        "BigInteger/modpow.cs",
        "BigInteger/multiply.cs",
        "BigInteger/op_and.cs",
        "BigInteger/op_decrement.cs",
        "BigInteger/op_divide.cs",
        "BigInteger/op_increment.cs",
        "BigInteger/op_leftshift.cs",
        "BigInteger/op_modulus.cs",
        "BigInteger/op_multiply.cs",
        "BigInteger/op_not.cs",
        "BigInteger/op_or.cs",
        "BigInteger/op_rightshift.cs",
        "BigInteger/op_xor.cs",
        "BigInteger/parse.cs",
        "BigInteger/pow.cs",
        "BigInteger/properties.cs",
        "BigInteger/remainder.cs",
        "BigInteger/sign.cs",
        "BigInteger/stackcalculator.cs",
    ] + [
        "BigIntegerTests.GenericMath.cs",
        "ComplexTests.cs",
        "ComplexTests.GenericMath.cs",
        "//src/libraries/Common/tests:System/GenericMathHelpers.cs",
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Numerics:impl_System.Runtime.Numerics",
        "//src/libraries/Common/tests:TestUtilities",
        "//src/libraries:ref_System.Text.RegularExpressions",
        "//src/libraries:ref_System.Net.Mime",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = [
        "CS8500",
        "CS8969",
        "IDE0100",
        "IDE0060",
        "SYSLIB0011",
        "SYSLIB0050",
        "SYSLIB0051",
        "IL2121",
        "NU5105",
    ],
    nullable = "annotations",
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
