load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Private.Xml.Linq",
    srcs = [
        "src/System/Xml/Linq/BaseUriAnnotation.cs",
        "src/System/Xml/Linq/Extensions.cs",
        "src/System/Xml/Linq/LineInfoAnnotation.cs",
        "src/System/Xml/Linq/LineInfoEndElementAnnotation.cs",
        "src/System/Xml/Linq/XAttribute.cs",
        "src/System/Xml/Linq/XCData.cs",
        "src/System/Xml/Linq/XComment.cs",
        "src/System/Xml/Linq/XContainer.cs",
        "src/System/Xml/Linq/XDeclaration.cs",
        "src/System/Xml/Linq/XDocument.cs",
        "src/System/Xml/Linq/XDocumentType.cs",
        "src/System/Xml/Linq/XElement.cs",
        "src/System/Xml/Linq/XHashtable.cs",
        "src/System/Xml/Linq/XHelper.cs",
        "src/System/Xml/Linq/XLinq.cs",
        "src/System/Xml/Linq/XName.cs",
        "src/System/Xml/Linq/XNamespace.cs",
        "src/System/Xml/Linq/XNode.cs",
        "src/System/Xml/Linq/XNodeBuilder.cs",
        "src/System/Xml/Linq/XNodeDocumentOrderComparer.cs",
        "src/System/Xml/Linq/XNodeEqualityComparer.cs",
        "src/System/Xml/Linq/XNodeReader.cs",
        "src/System/Xml/Linq/XObject.cs",
        "src/System/Xml/Linq/XObjectChangeAnnotation.cs",
        "src/System/Xml/Linq/XObjectChangeEventArgs.cs",
        "src/System/Xml/Linq/XProcessingInstruction.cs",
        "src/System/Xml/Linq/XStreamingElement.cs",
        "src/System/Xml/Linq/XText.cs",
        "src/System/Xml/Schema/XNodeValidator.cs",
        "src/System/Xml/XPath/XNodeNavigator.cs",
        "src/System/Xml/XPath/XObjectExtensions.cs",
    ] + [
        "//src/libraries/Common:src/System/Collections/Generic/EnumerableHelpers.cs",
        "//src/libraries/Common:src/System/Text/StringBuilderCache.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Private.Xml:impl_System.Private.Xml",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
    ],
)
