load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

exports_files([
    "src/System/Polyfills.cs",
    "src/System/Collections/Frozen/String/Hashing.cs",
    "src/System/Collections/Frozen/String/KeyAnalyzer.cs",
    "src/Validation/Requires.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Collections.Immutable",
    srcs = [
        "ref/System.Collections.Immutable.cs",
        "ref/System.Collections.Immutable.netcoreapp.cs",
        # net9 only
        "ref/System.Collections.Immutable.net9.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Collections.Immutable",
    multitarget = True,
    srcs = [
        "src/System/Collections/Frozen/Constants.cs",
        "src/System/Collections/Frozen/DefaultFrozenDictionary.AlternateLookup.cs",
        "src/System/Collections/Frozen/DefaultFrozenDictionary.cs",
        "src/System/Collections/Frozen/DefaultFrozenSet.AlternateLookup.cs",
        "src/System/Collections/Frozen/DefaultFrozenSet.cs",
        "src/System/Collections/Frozen/EmptyFrozenDictionary.cs",
        "src/System/Collections/Frozen/EmptyFrozenSet.cs",
        "src/System/Collections/Frozen/FrozenDictionary.AlternateLookup.cs",
        "src/System/Collections/Frozen/FrozenDictionary.cs",
        "src/System/Collections/Frozen/FrozenHashTable.cs",
        "src/System/Collections/Frozen/FrozenSet.AlternateLookup.cs",
        "src/System/Collections/Frozen/FrozenSet.cs",
        "src/System/Collections/Frozen/FrozenSetInternalBase.cs",
        "src/System/Collections/Frozen/Int32/Int32FrozenDictionary.AlternateLookup.cs",
        "src/System/Collections/Frozen/Int32/Int32FrozenDictionary.cs",
        "src/System/Collections/Frozen/Int32/Int32FrozenSet.AlternateLookup.cs",
        "src/System/Collections/Frozen/Int32/Int32FrozenSet.cs",
        "src/System/Collections/Frozen/Integer/DenseIntegralFrozenDictionary.cs",
        "src/System/Collections/Frozen/ItemsFrozenSet.cs",
        "src/System/Collections/Frozen/KeysAndValuesFrozenDictionary.cs",
        "src/System/Collections/Frozen/SmallFrozenDictionary.AlternateLookup.cs",
        "src/System/Collections/Frozen/SmallFrozenDictionary.cs",
        "src/System/Collections/Frozen/SmallFrozenSet.AlternateLookup.cs",
        "src/System/Collections/Frozen/SmallFrozenSet.cs",
        "src/System/Collections/Frozen/SmallValueTypeComparableFrozenDictionary.cs",
        "src/System/Collections/Frozen/SmallValueTypeComparableFrozenSet.cs",
        "src/System/Collections/Frozen/SmallValueTypeDefaultComparerFrozenDictionary.cs",
        "src/System/Collections/Frozen/SmallValueTypeDefaultComparerFrozenSet.cs",
        "src/System/Collections/Frozen/String/Hashing.cs",
        "src/System/Collections/Frozen/String/KeyAnalyzer.cs",
        "src/System/Collections/Frozen/String/LengthBuckets.cs",
        "src/System/Collections/Frozen/String/LengthBucketsFrozenDictionary.AlternateLookup.cs",
        "src/System/Collections/Frozen/String/LengthBucketsFrozenDictionary.cs",
        "src/System/Collections/Frozen/String/LengthBucketsFrozenSet.AlternateLookup.cs",
        "src/System/Collections/Frozen/String/LengthBucketsFrozenSet.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary.AlternateLookup.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_Full.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_FullCaseInsensitive.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_FullCaseInsensitiveAscii.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_LeftJustifiedCaseInsensitiveAsciiSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_LeftJustifiedCaseInsensitiveSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_LeftJustifiedSingleChar.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_LeftJustifiedSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_RightJustifiedCaseInsensitiveAsciiSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_RightJustifiedCaseInsensitiveSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_RightJustifiedSingleChar.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenDictionary_RightJustifiedSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet.AlternateLookup.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_Full.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_FullCaseInsensitive.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_FullCaseInsensitiveAscii.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_LeftJustifiedCaseInsensitiveAsciiSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_LeftJustifiedCaseInsensitiveSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_LeftJustifiedSingleChar.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_LeftJustifiedSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_RightJustifiedCaseInsensitiveAsciiSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_RightJustifiedCaseInsensitiveSubstring.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_RightJustifiedSingleChar.cs",
        "src/System/Collections/Frozen/String/OrdinalStringFrozenSet_RightJustifiedSubstring.cs",
        "src/System/Collections/Frozen/ValueTypeDefaultComparerFrozenDictionary.cs",
        "src/System/Collections/Frozen/ValueTypeDefaultComparerFrozenSet.cs",
        "src/System/Collections/Immutable/AllocFreeConcurrentStack.cs",
        "src/System/Collections/Immutable/DictionaryEnumerator.cs",
        "src/System/Collections/Immutable/DisposableEnumeratorAdapter_2.cs",
        "src/System/Collections/Immutable/IImmutableArray.cs",
        "src/System/Collections/Immutable/IImmutableDictionary.cs",
        "src/System/Collections/Immutable/IImmutableDictionaryInternal.cs",
        "src/System/Collections/Immutable/IImmutableList.cs",
        "src/System/Collections/Immutable/IImmutableQueue.cs",
        "src/System/Collections/Immutable/IImmutableSet.cs",
        "src/System/Collections/Immutable/IImmutableStack.cs",
        "src/System/Collections/Immutable/IStrongEnumerable_2.cs",
        "src/System/Collections/Immutable/IStrongEnumerator_1.cs",
        "src/System/Collections/Immutable/ImmutableArray.cs",
        "src/System/Collections/Immutable/ImmutableArray_1.Builder.DebuggerProxy.cs",
        "src/System/Collections/Immutable/ImmutableArray_1.Builder.cs",
        "src/System/Collections/Immutable/ImmutableArray_1.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs",
        "src/System/Collections/Immutable/ImmutableArray_1.cs",
        "src/System/Collections/Immutable/ImmutableArray_1.netcoreapp.cs",
        "src/System/Collections/Immutable/ImmutableDictionary.cs",
        "src/System/Collections/Immutable/ImmutableDictionary_2.Builder.cs",
        "src/System/Collections/Immutable/ImmutableDictionary_2.Comparers.cs",
        "src/System/Collections/Immutable/ImmutableDictionary_2.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableDictionary_2.HashBucket.cs",
        "src/System/Collections/Immutable/ImmutableDictionary_2.MutationInput.cs",
        "src/System/Collections/Immutable/ImmutableDictionary_2.MutationResult.cs",
        "src/System/Collections/Immutable/ImmutableDictionary_2.cs",
        "src/System/Collections/Immutable/ImmutableEnumerableDebuggerProxy.cs",
        "src/System/Collections/Immutable/ImmutableExtensions.Minimal.cs",
        "src/System/Collections/Immutable/ImmutableExtensions.cs",
        "src/System/Collections/Immutable/ImmutableHashSet.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.Builder.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.HashBucket.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.HashBucketByRefEqualityComparer.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.HashBucketByValueEqualityComparer.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.MutationInput.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.MutationResult.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.NodeEnumerable.cs",
        "src/System/Collections/Immutable/ImmutableHashSet_1.cs",
        "src/System/Collections/Immutable/ImmutableInterlocked.cs",
        "src/System/Collections/Immutable/ImmutableList.cs",
        "src/System/Collections/Immutable/ImmutableList_1.Builder.cs",
        "src/System/Collections/Immutable/ImmutableList_1.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableList_1.Node.cs",
        "src/System/Collections/Immutable/ImmutableList_1.cs",
        "src/System/Collections/Immutable/ImmutableQueue.cs",
        "src/System/Collections/Immutable/ImmutableQueue_1.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableQueue_1.cs",
        "src/System/Collections/Immutable/ImmutableSortedDictionary.cs",
        "src/System/Collections/Immutable/ImmutableSortedDictionary_2.Builder.cs",
        "src/System/Collections/Immutable/ImmutableSortedDictionary_2.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableSortedDictionary_2.Node.cs",
        "src/System/Collections/Immutable/ImmutableSortedDictionary_2.cs",
        "src/System/Collections/Immutable/ImmutableSortedSet.cs",
        "src/System/Collections/Immutable/ImmutableSortedSet_1.Builder.DebuggerProxy.cs",
        "src/System/Collections/Immutable/ImmutableSortedSet_1.Builder.cs",
        "src/System/Collections/Immutable/ImmutableSortedSet_1.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableSortedSet_1.Node.cs",
        "src/System/Collections/Immutable/ImmutableSortedSet_1.cs",
        "src/System/Collections/Immutable/ImmutableStack.cs",
        "src/System/Collections/Immutable/ImmutableStack_1.Enumerator.cs",
        "src/System/Collections/Immutable/ImmutableStack_1.cs",
        "src/System/Collections/Immutable/KeysOrValuesCollectionAccessor.cs",
        "src/System/Collections/Immutable/RefAsValueType.cs",
        "src/System/Collections/Immutable/SecureObjectPool.cs",
        "src/System/Collections/Immutable/SortedInt32KeyNode.Enumerator.cs",
        "src/System/Collections/Immutable/SortedInt32KeyNode.cs",
        "src/System/Collections/ThrowHelper.cs",
        "src/System/Linq/ImmutableArrayExtensions.cs",
        "src/System/Polyfills.cs",
        "src/System/Runtime.InteropServices/ImmutableCollectionsMarshal.cs",
        "src/Validation/Requires.cs",
    ] + [
        # CoreLibSharedDir files
        "//src/libraries/System.Private.CoreLib:src/System/Collections/HashHelpers.cs",
        "//src/libraries/System.Private.CoreLib:src/System/Collections/Generic/DebugViewDictionaryItem.cs",
        "//src/libraries/System.Private.CoreLib:src/System/Collections/Generic/IDictionaryDebugView.cs",
        # CommonPath files
        "//src/libraries/Common:src/System/Runtime/Versioning/NonVersionableAttribute.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    assembly_description = "This package provides collections that are thread safe and guaranteed to never change their contents, also known as immutable collections. Like strings, any methods that perform modifications will not change the existing instance but instead return a new instance. For efficiency reasons, the implementation uses a sharing mechanism to ensure that newly created instances share as much data as possible with the previous instance while ensuring that operations have a predictable time complexity.\n\nThe System.Collections.Immutable library is built-in as part of the shared framework in .NET Runtime. The package can be installed when you need to use it in other target frameworks.",
)
