load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "regex-redux-5",
    srcs = ["regex-redux-5.cs", "harness-helpers.cs"],
    debug_type = "pdbonly",
    optimize = True,
    deps = [
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
    ],
)

coreclr_test(
    name = "regex-redux-1",
    srcs = ["regex-redux-1.cs", "harness-helpers.cs"],
    debug_type = "pdbonly",
    optimize = True,
    deps = [
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
    ],
)
