load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

exports_files([
    "ref/System.ComponentModel.TypeConverter.cs",
    "ref/System.ComponentModel.TypeConverter.Forwards.cs",
    "ref/System.ComponentModel.manual.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.ComponentModel.TypeConverter",
    srcs = [
        "ref/System.ComponentModel.manual.cs",
        "ref/System.ComponentModel.TypeConverter.cs",
        "ref/System.ComponentModel.TypeConverter.Forwards.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Resources.Writer:ref_System.Resources.Writer",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.ComponentModel.TypeConverter",
    analyzers = [
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    srcs = [
        "src/System/ComponentModel/AddingNewEventArgs.cs",
        "src/System/ComponentModel/AddingNewEventHandler.cs",
        "src/System/ComponentModel/AmbientValueAttribute.cs",
        "src/System/ComponentModel/ArrayConverter.cs",
        "src/System/ComponentModel/AttributeCollection.cs",
        "src/System/ComponentModel/AttributeProviderAttribute.cs",
        "src/System/ComponentModel/BaseComponentEditor.cs",
        "src/System/ComponentModel/BaseNumberConverter.cs",
        "src/System/ComponentModel/BindableAttribute.cs",
        "src/System/ComponentModel/BindableSupport.cs",
        "src/System/ComponentModel/BindingDirection.cs",
        "src/System/ComponentModel/BindingList.cs",
        "src/System/ComponentModel/BooleanConverter.cs",
        "src/System/ComponentModel/ByteConverter.cs",
        "src/System/ComponentModel/CancelEventHandler.cs",
        "src/System/ComponentModel/CharConverter.cs",
        "src/System/ComponentModel/CollectionChangeAction.cs",
        "src/System/ComponentModel/CollectionChangeEventArgs.cs",
        "src/System/ComponentModel/CollectionChangeEventHandler.cs",
        "src/System/ComponentModel/CollectionConverter.cs",
        "src/System/ComponentModel/ComplexBindingPropertiesAttribute.cs",
        "src/System/ComponentModel/ComponentConverter.cs",
        "src/System/ComponentModel/ComponentResourceManager.cs",
        "src/System/ComponentModel/Container.cs",
        "src/System/ComponentModel/ContainerFilterService.cs",
        "src/System/ComponentModel/CultureInfoConverter.cs",
        "src/System/ComponentModel/CustomTypeDescriptor.cs",
        "src/System/ComponentModel/DataObjectAttribute.cs",
        "src/System/ComponentModel/DataObjectFieldAttribute.cs",
        "src/System/ComponentModel/DataObjectMethodAttribute.cs",
        "src/System/ComponentModel/DataObjectMethodType.cs",
        "src/System/ComponentModel/DateOnlyConverter.cs",
        "src/System/ComponentModel/DateTimeConverter.cs",
        "src/System/ComponentModel/DateTimeOffsetConverter.cs",
        "src/System/ComponentModel/DecimalConverter.cs",
        "src/System/ComponentModel/DefaultBindingPropertyAttribute.cs",
        "src/System/ComponentModel/DefaultEventAttribute.cs",
        "src/System/ComponentModel/DefaultPropertyAttribute.cs",
        "src/System/ComponentModel/DelegatingTypeDescriptionProvider.cs",
        "src/System/ComponentModel/Design/ActiveDesignerEventArgs.cs",
        "src/System/ComponentModel/Design/ActiveDocumentEventHandler.cs",
        "src/System/ComponentModel/Design/CheckoutException.cs",
        "src/System/ComponentModel/Design/CommandID.cs",
        "src/System/ComponentModel/Design/ComponentChangedEventArgs.cs",
        "src/System/ComponentModel/Design/ComponentChangedEventHandler.cs",
        "src/System/ComponentModel/Design/ComponentChangingEventArgs.cs",
        "src/System/ComponentModel/Design/ComponentChangingEventHandler.cs",
        "src/System/ComponentModel/Design/ComponentEventArgs.cs",
        "src/System/ComponentModel/Design/ComponentEventHandler.cs",
        "src/System/ComponentModel/Design/ComponentRenameEventArgs.cs",
        "src/System/ComponentModel/Design/ComponentRenameEventHandler.cs",
        "src/System/ComponentModel/Design/DesignerCollection.cs",
        "src/System/ComponentModel/Design/DesignerEventArgs.cs",
        "src/System/ComponentModel/Design/DesignerEventHandler.cs",
        "src/System/ComponentModel/Design/DesignerOptionService.cs",
        "src/System/ComponentModel/Design/DesignerTransaction.cs",
        "src/System/ComponentModel/Design/DesignerTransactionCloseEventArgs.cs",
        "src/System/ComponentModel/Design/DesignerTransactionCloseEventHandler.cs",
        "src/System/ComponentModel/Design/DesignerVerb.cs",
        "src/System/ComponentModel/Design/DesignerVerbCollection.cs",
        "src/System/ComponentModel/Design/DesigntimeLicenseContext.cs",
        "src/System/ComponentModel/Design/DesigntimeLicenseContextSerializer.cs",
        "src/System/ComponentModel/Design/HelpContextType.cs",
        "src/System/ComponentModel/Design/HelpKeywordAttribute.cs",
        "src/System/ComponentModel/Design/HelpKeywordType.cs",
        "src/System/ComponentModel/Design/IComponentChangeService.cs",
        "src/System/ComponentModel/Design/IComponentDiscoveryService.cs",
        "src/System/ComponentModel/Design/IComponentInitializer.cs",
        "src/System/ComponentModel/Design/IDesigner.cs",
        "src/System/ComponentModel/Design/IDesignerEventService.cs",
        "src/System/ComponentModel/Design/IDesignerFilter.cs",
        "src/System/ComponentModel/Design/IDesignerHost.cs",
        "src/System/ComponentModel/Design/IDesignerHostTransactionState.cs",
        "src/System/ComponentModel/Design/IDesignerOptionService.cs",
        "src/System/ComponentModel/Design/IDictionaryService.cs",
        "src/System/ComponentModel/Design/IEventPropertyService.cs",
        "src/System/ComponentModel/Design/IExtenderListService.cs",
        "src/System/ComponentModel/Design/IExtenderProviderService.cs",
        "src/System/ComponentModel/Design/IHelpService.cs",
        "src/System/ComponentModel/Design/IInheritanceService.cs",
        "src/System/ComponentModel/Design/IMenuCommandService.cs",
        "src/System/ComponentModel/Design/IReferenceService.cs",
        "src/System/ComponentModel/Design/IResourceService.cs",
        "src/System/ComponentModel/Design/IRootDesigner.cs",
        "src/System/ComponentModel/Design/ISelectionService.cs",
        "src/System/ComponentModel/Design/IServiceObjectContainer.cs",
        "src/System/ComponentModel/Design/ITreeDesigner.cs",
        "src/System/ComponentModel/Design/ITypeDescriptorFilterService.cs",
        "src/System/ComponentModel/Design/ITypeDiscoveryService.cs",
        "src/System/ComponentModel/Design/ITypeResolutionService.cs",
        "src/System/ComponentModel/Design/InheritanceLevel.cs",
        "src/System/ComponentModel/Design/MenuCommand.cs",
        "src/System/ComponentModel/Design/PropertyTabAttribute.cs",
        "src/System/ComponentModel/Design/PropertyTabScope.cs",
        "src/System/ComponentModel/Design/SelectionTypes.cs",
        "src/System/ComponentModel/Design/Serialization/ComponentSerializationService.cs",
        "src/System/ComponentModel/Design/Serialization/ContextStack.cs",
        "src/System/ComponentModel/Design/Serialization/DefaultSerializationProviderAttribute.cs",
        "src/System/ComponentModel/Design/Serialization/DesignerLoader.cs",
        "src/System/ComponentModel/Design/Serialization/IDesignerLoaderHost.cs",
        "src/System/ComponentModel/Design/Serialization/IDesignerLoaderService.cs",
        "src/System/ComponentModel/Design/Serialization/IDesignerSerializationManager.cs",
        "src/System/ComponentModel/Design/Serialization/IDesignerSerializationProvider.cs",
        "src/System/ComponentModel/Design/Serialization/IDesignerSerializationService.cs",
        "src/System/ComponentModel/Design/Serialization/INameCreationService.cs",
        "src/System/ComponentModel/Design/Serialization/InstanceDescriptor.cs",
        "src/System/ComponentModel/Design/Serialization/MemberRelationshipService.cs",
        "src/System/ComponentModel/Design/Serialization/ResolveNameEventArgs.cs",
        "src/System/ComponentModel/Design/Serialization/ResolveNameEventHandler.cs",
        "src/System/ComponentModel/Design/Serialization/RootDesignerSerializerAttribute.cs",
        "src/System/ComponentModel/Design/Serialization/SerializationStore.cs",
        "src/System/ComponentModel/Design/ServiceContainer.cs",
        "src/System/ComponentModel/Design/ServiceCreatorCallback.cs",
        "src/System/ComponentModel/Design/StandardCommands.cs",
        "src/System/ComponentModel/Design/StandardToolWindows.cs",
        "src/System/ComponentModel/Design/ViewTechnology.cs",
        "src/System/ComponentModel/DesignTimeVisibleAttribute.cs",
        "src/System/ComponentModel/DoubleConverter.cs",
        "src/System/ComponentModel/EnumConverter.cs",
        "src/System/ComponentModel/EventDescriptor.cs",
        "src/System/ComponentModel/EventDescriptorCollection.cs",
        "src/System/ComponentModel/ExpandableObjectConverter.cs",
        "src/System/ComponentModel/ExtendedPropertyDescriptor.cs",
        "src/System/ComponentModel/ExtenderProvidedPropertyAttribute.cs",
        "src/System/ComponentModel/GuidConverter.cs",
        "src/System/ComponentModel/HalfConverter.cs",
        "src/System/ComponentModel/HandledEventArgs.cs",
        "src/System/ComponentModel/HandledEventHandler.cs",
        "src/System/ComponentModel/IBindingList.cs",
        "src/System/ComponentModel/IBindingListView.cs",
        "src/System/ComponentModel/ICancelAddNew.cs",
        "src/System/ComponentModel/IComNativeDescriptorHandler.cs",
        "src/System/ComponentModel/ICustomTypeDescriptor.cs",
        "src/System/ComponentModel/IDataErrorInfo.cs",
        "src/System/ComponentModel/IExtenderProvider.cs",
        "src/System/ComponentModel/IIntellisenseBuilder.cs",
        "src/System/ComponentModel/IListSource.cs",
        "src/System/ComponentModel/INestedContainer.cs",
        "src/System/ComponentModel/INestedSite.cs",
        "src/System/ComponentModel/IRaiseItemChangedEvents.cs",
        "src/System/ComponentModel/ISupportInitializeNotification.cs",
        "src/System/ComponentModel/ITypeDescriptorContext.cs",
        "src/System/ComponentModel/ITypedList.cs",
        "src/System/ComponentModel/InheritanceAttribute.cs",
        "src/System/ComponentModel/InstallerTypeAttribute.cs",
        "src/System/ComponentModel/InstanceCreationEditor.cs",
        "src/System/ComponentModel/Int128Converter.cs",
        "src/System/ComponentModel/Int16Converter.cs",
        "src/System/ComponentModel/Int32Converter.cs",
        "src/System/ComponentModel/Int64Converter.cs",
        "src/System/ComponentModel/InterlockedBitVector32.cs",
        "src/System/ComponentModel/LicFileLicenseProvider.cs",
        "src/System/ComponentModel/License.cs",
        "src/System/ComponentModel/LicenseContext.cs",
        "src/System/ComponentModel/LicenseException.cs",
        "src/System/ComponentModel/LicenseManager.LicenseInteropHelper.cs",
        "src/System/ComponentModel/LicenseManager.cs",
        "src/System/ComponentModel/LicenseProvider.cs",
        "src/System/ComponentModel/LicenseProviderAttribute.cs",
        "src/System/ComponentModel/LicenseUsageMode.cs",
        "src/System/ComponentModel/ListBindableAttribute.cs",
        "src/System/ComponentModel/ListChangedEventArgs.cs",
        "src/System/ComponentModel/ListChangedEventHandler.cs",
        "src/System/ComponentModel/ListChangedType.cs",
        "src/System/ComponentModel/ListSortDescription.cs",
        "src/System/ComponentModel/ListSortDescriptionCollection.cs",
        "src/System/ComponentModel/ListSortDirection.cs",
        "src/System/ComponentModel/LookupBindingPropertiesAttribute.cs",
        "src/System/ComponentModel/MarshalByValueComponent.cs",
        "src/System/ComponentModel/MaskedTextProvider.cs",
        "src/System/ComponentModel/MaskedTextResultHint.cs",
        "src/System/ComponentModel/MemberDescriptor.cs",
        "src/System/ComponentModel/MultilineStringConverter.cs",
        "src/System/ComponentModel/NestedContainer.cs",
        "src/System/ComponentModel/NullableConverter.cs",
        "src/System/ComponentModel/PasswordPropertyTextAttribute.cs",
        "src/System/ComponentModel/PropertyDescriptor.cs",
        "src/System/ComponentModel/PropertyDescriptorCollection.cs",
        "src/System/ComponentModel/ProvidePropertyAttribute.cs",
        "src/System/ComponentModel/RecommendedAsConfigurableAttribute.cs",
        "src/System/ComponentModel/ReferenceConverter.cs",
        "src/System/ComponentModel/ReflectEventDescriptor.cs",
        "src/System/ComponentModel/ReflectPropertyDescriptor.cs",
        "src/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs",
        "src/System/ComponentModel/ReflectTypeDescriptionProvider.cs",
        "src/System/ComponentModel/ReflectionCachesUpdateHandler.cs",
        "src/System/ComponentModel/RefreshEventArgs.cs",
        "src/System/ComponentModel/RefreshEventHandler.cs",
        "src/System/ComponentModel/RunInstallerAttribute.cs",
        "src/System/ComponentModel/SByteConverter.cs",
        "src/System/ComponentModel/SettingsBindableAttribute.cs",
        "src/System/ComponentModel/SingleConverter.cs",
        "src/System/ComponentModel/StringConverter.cs",
        "src/System/ComponentModel/SyntaxCheck.cs",
        "src/System/ComponentModel/TimeOnlyConverter.cs",
        "src/System/ComponentModel/TimeSpanConverter.cs",
        "src/System/ComponentModel/ToolboxItemAttribute.cs",
        "src/System/ComponentModel/ToolboxItemFilterAttribute.cs",
        "src/System/ComponentModel/ToolboxItemFilterType.cs",
        "src/System/ComponentModel/TrimSafeReflectionHelper.cs",
        "src/System/ComponentModel/TypeConverter.cs",
        "src/System/ComponentModel/TypeDescriptionProvider.cs",
        "src/System/ComponentModel/TypeDescriptionProviderService.cs",
        "src/System/ComponentModel/TypeDescriptor.cs",
        "src/System/ComponentModel/TypeListConverter.cs",
        "src/System/ComponentModel/UInt128Converter.cs",
        "src/System/ComponentModel/UInt16Converter.cs",
        "src/System/ComponentModel/UInt32Converter.cs",
        "src/System/ComponentModel/UInt64Converter.cs",
        "src/System/ComponentModel/UriTypeConverter.cs",
        "src/System/ComponentModel/VersionConverter.cs",
        "src/System/ComponentModel/WarningException.cs",
        "src/System/ComponentModel/WeakHashtable.cs",
        "src/System/Drawing/ColorConverter.cs",
        "src/System/Drawing/PointConverter.cs",
        "src/System/Drawing/RectangleConverter.cs",
        "src/System/Drawing/SizeConverter.cs",
        "src/System/Drawing/SizeFConverter.cs",
        "src/System/InvariantComparer.cs",
        "src/System/Security/Authentication/ExtendedProtection/ExtendedProtectionPolicyTypeConverter.cs",
        "src/System/Timers/ElapsedEventArgs.cs",
        "src/System/Timers/ElapsedEventHandler.cs",
        "src/System/Timers/Timer.cs",
        "src/System/Timers/TimersDescriptionAttribute.cs",
    ] + [
        "src/MS/Internal/Xml/Linq/ComponentModel/XComponentModel.cs",
        "//src/libraries/Common:src/System/Drawing/ColorConverterCommon.cs",
        "//src/libraries/Common:src/System/Drawing/ColorTable.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
    ],
    partial_facade = True,
    generate_facades = True,
    facade_contract_assembly = ":ref_System.ComponentModel.TypeConverter",
    resx_file = "src/Resources/Strings.resx",
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.Security:ref_System.Net.Security",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Resources.Writer:ref_System.Resources.Writer",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Loader:ref_System.Runtime.Loader",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
    ],
)
