load("//src/tests:live_test.bzl", "coreclr_merged_test")

coreclr_merged_test(
    name = "IL_Conformance",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/IL_Conformance/Convert:TestConvertFromIntegral",
        "//src/tests/JIT/IL_Conformance/Old/Base:add",
        "//src/tests/JIT/IL_Conformance/Old/Base:add_ovf",
        "//src/tests/JIT/IL_Conformance/Old/Base:and",
        "//src/tests/JIT/IL_Conformance/Old/Base:beq",
        "//src/tests/JIT/IL_Conformance/Old/Base:beq_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:bge",
        "//src/tests/JIT/IL_Conformance/Old/Base:bge_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:bgt",
        "//src/tests/JIT/IL_Conformance/Old/Base:bgt_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:ble",
        "//src/tests/JIT/IL_Conformance/Old/Base:ble_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:blt",
        "//src/tests/JIT/IL_Conformance/Old/Base:blt_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:bne",
        "//src/tests/JIT/IL_Conformance/Old/Base:bne_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:br",
        "//src/tests/JIT/IL_Conformance/Old/Base:br_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:brfalse",
        "//src/tests/JIT/IL_Conformance/Old/Base:brfalse_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:brtrue",
        "//src/tests/JIT/IL_Conformance/Old/Base:brtrue_s",
        "//src/tests/JIT/IL_Conformance/Old/Base:call",
        "//src/tests/JIT/IL_Conformance/Old/Base:ceq",
        "//src/tests/JIT/IL_Conformance/Old/Base:cgt",
        "//src/tests/JIT/IL_Conformance/Old/Base:ckfinite",
        "//src/tests/JIT/IL_Conformance/Old/Base:clt",
        "//src/tests/JIT/IL_Conformance/Old/Base:conv",
        "//src/tests/JIT/IL_Conformance/Old/Base:conv_ovf",
        "//src/tests/JIT/IL_Conformance/Old/Base:cpblk",
        "//src/tests/JIT/IL_Conformance/Old/Base:div",
        "//src/tests/JIT/IL_Conformance/Old/Base:dup",
        "//src/tests/JIT/IL_Conformance/Old/Base:initblk",
        "//src/tests/JIT/IL_Conformance/Old/Base:jmp",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldarg_n",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldarg_starg",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldargs_stargs",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldc",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldc_i4_n",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldftn_calli",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldind_stind",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldloc_stloc",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldloca",
        "//src/tests/JIT/IL_Conformance/Old/Base:ldnull",
        "//src/tests/JIT/IL_Conformance/Old/Base:mul",
        "//src/tests/JIT/IL_Conformance/Old/Base:mul_ovf",
        "//src/tests/JIT/IL_Conformance/Old/Base:neg",
        "//src/tests/JIT/IL_Conformance/Old/Base:nop",
        "//src/tests/JIT/IL_Conformance/Old/Base:not",
        "//src/tests/JIT/IL_Conformance/Old/Base:or",
        "//src/tests/JIT/IL_Conformance/Old/Base:pop",
        "//src/tests/JIT/IL_Conformance/Old/Base:rem",
        "//src/tests/JIT/IL_Conformance/Old/Base:ret",
        "//src/tests/JIT/IL_Conformance/Old/Base:shl",
        "//src/tests/JIT/IL_Conformance/Old/Base:shr",
        "//src/tests/JIT/IL_Conformance/Old/Base:sub",
        "//src/tests/JIT/IL_Conformance/Old/Base:sub_ovf",
        "//src/tests/JIT/IL_Conformance/Old/Base:switch",
        "//src/tests/JIT/IL_Conformance/Old/Base:tailcall",
        "//src/tests/JIT/IL_Conformance/Old/Base:unaligned",
        "//src/tests/JIT/IL_Conformance/Old/Base:volatile",
        "//src/tests/JIT/IL_Conformance/Old/Base:xor",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ConvDLL",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:Conv_I4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:Conv_I8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:Conv_R4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_I4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_ovf_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:add_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:and_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:and_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:beq_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:beq_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:beq_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:beq_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:beq_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_u",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_un_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_un_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_un_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bge_un_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_u",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_un_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bgt_un_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_u",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_un_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ble_un_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_u",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_un_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:blt_un_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bne_u",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bne_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bne_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bne_un_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:bne_un_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:br_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:brfalse_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:brtrue_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_br",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_brfalse",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_brtrue",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_call",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_cpblk",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_initblk",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_ldvirtftn",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_localloc",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_nop",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_ret",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:c_switch",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:call_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ceq_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ceq_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ceq_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ceq_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ceq_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_u",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_un_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cgt_un_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ckfinite_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ckfinite_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_u",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_un_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:clt_un_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_i1_un",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_i4_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_i4_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_i4_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_i8_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_i8_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_i8_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_r8_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_r8_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_r8_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_u4_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_u4_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_u4_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_u4_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_u8_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:conv_ovf_u8_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:cpblk_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:div_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:div_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:div_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:div_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:div_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:div_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:dup4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:dup8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:dupi",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:initblk_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarg_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarg_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarg_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarg_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarg_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarg_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarga_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarga_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarga_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarga_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarga_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldarga_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_add_ovf_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_c_cpblk",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_c_initblk",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_c_nop",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_c_ret",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_c_switch",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ckfinite_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ckfinite_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_i4_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_i4_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_i4_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_i8_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_i8_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_r8_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_r8_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_r8_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_u4_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_u4_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_u4_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_u4_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_u8_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_conv_ovf_u8_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_mul_ovf_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_neg_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_neg_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ret_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ret_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ret_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ret_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ret_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_ret_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldc_sub_ovf_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldftn",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldind_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldloc_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldloc_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldloc_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldloc_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldloc_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldloc_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldnull_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldnull_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ldvirtftn_Conformance_Base",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:localloc_Conformance_Base",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_ovf_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:mul_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:neg_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:neg_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:neg_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:neg_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:nop_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:not_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:not_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:or_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:or_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:pop4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:pop8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:popi",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:refs",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:rem_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:rem_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:rem_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:rem_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:rem_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:rem_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ret_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ret_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ret_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ret_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ret_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ret_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:ret_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:shl_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:shl_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:shr_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:shr_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:shr_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:shr_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sizeof",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:starg_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:starg_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:starg_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:starg_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:starg_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:starg_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stind_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stind_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stind_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stind_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stind_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stind_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stloc_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stloc_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stloc_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stloc_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stloc_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:stloc_ref",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_i",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_i1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_i2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_i4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_i8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_u1",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_u2",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_ovf_u8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_r4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:sub_r8",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:switch_Conformance",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:xor_u4",
        "//src/tests/JIT/IL_Conformance/Old/Conformance_Base:xor_u8",
        "//src/tests/JIT/IL_Conformance/Old/directed:AutoInit",
        "//src/tests/JIT/IL_Conformance/Old/directed:heap_ovf",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldarg_s_i1",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldarg_s_i2",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldarg_s_i4",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldarg_s_i8",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldarg_s_r4",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldarg_s_r8",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloc_s_i1",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloc_s_i2",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloc_s_i4",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloc_s_i8",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloc_s_r4",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloc_s_r8",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloca_s_i1",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloca_s_i2",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloca_s_i4",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloca_s_i8",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloca_s_r4",
        "//src/tests/JIT/IL_Conformance/Old/directed:ldloca_s_r8",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:Box_Unbox",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:array_tests",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:callintf",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:callnonvirt",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:callstatic",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:callsuper",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:callvirt",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:castclass",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:cpobj",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:field_tests",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:fielda_tests",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:initobj",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:isinst",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:ldlen",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:ldobj",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:ldstr",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:ldtoken",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:ldvirtftn_objectmodel",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:localloc_objectmodel",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:newobj",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:seh_tests",
        "//src/tests/JIT/IL_Conformance/Old/objectmodel:throw",
    ],
)
