load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "nested",
    srcs = ["nested.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "gcref1",
    srcs = ["gcref1.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "oddsize",
    srcs = ["oddsize.il"],
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "overlap",
    srcs = ["overlap.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "simplearg",
    srcs = ["simplearg.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "gcref2",
    srcs = ["gcref2.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "simple",
    srcs = ["simple.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "extended",
    srcs = ["extended.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)
