load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "resgen")

resgen(
    name = "TestResx",
    out = "TestResx.resources",
    resx_file = "Resources/TestResx.resx",
)

library_test(
    name = "System.ComponentModel.TypeConverter.Tests",
    srcs = [
        "AddingNewEventArgsTests.cs",
        "AmbientValueAttributeTests.cs",
        "ArrayConverterTests.cs",
        "AttributeCollectionTests.cs",
        "AttributeProviderAttributeTests.cs",
        "BaseNumberConverterTests.cs",
        "BindableAttributeTests.cs",
        "BindingListTests.cs",
        "BooleanConverterTests.cs",
        "ByteConvertersTests.cs",
        "CharConverterTests.cs",
        "CollectionChangedEventArgsTests.cs",
        "CollectionConverterTests.cs",
        "ComplexBindingPropertiesAttributeTests.cs",
        "ComponentConverterTests.cs",
        "ComponentEditorTests.cs",
        "ComponentResourceManagerTests.cs",
        "ContainerFilterServiceTests.cs",
        "ContainerTests.cs",
        "ContextStackTests.cs",
        "ConverterTestBase.cs",
        "CultureInfoConverterTests.cs",
        "DataObjectAttributeTests.cs",
        "DataObjectFieldAttributeTests.cs",
        "DataObjectMethodAttributeTests.cs",
        "DateOnlyConverterTests.cs",
        "DateTimeConverterTests.cs",
        "DateTimeOffsetConverterTests.cs",
        "DecimalConverterTests.cs",
        "DefaultBindingPropertyAttributeTests.cs",
        "DefaultEventAttributeTests.cs",
        "DefaultPropertyAttributeTests.cs",
        "DescriptorTestAttribute.cs",
        "DescriptorTestComponent.cs",
        "Design/ActiveDesignerEventArgsTests.cs",
        "Design/CheckoutExceptionTests.cs",
        "Design/CommandIDTests.cs",
        "Design/ComponentChangedEventArgsTests.cs",
        "Design/ComponentChangingEventArgsTests.cs",
        "Design/ComponentEventArgsTests.cs",
        "Design/ComponentRenameEventArgsTests.cs",
        "Design/DesignerCollectionTests.cs",
        "Design/DesignerEventArgsTests.cs",
        "Design/DesignerOptionServiceTests.cs",
        "Design/DesignerTransactionCloseEventArgsTests.cs",
        "Design/DesignerTransactionTests.cs",
        "Design/DesignerVerbCollectionTests.cs",
        "Design/DesignerVerbTests.cs",
        "Design/DesigntimeLicenseContextSerializerTests.cs",
        "Design/DesigntimeLicenseContextTests.cs",
        "Design/HelpKeywordAttributeTests.cs",
        "Design/MenuCommandTests.cs",
        "Design/Serialization/ComponentSerializationServiceTests.cs",
        "Design/Serialization/DefaultSerializationProviderAttributeTests.cs",
        "Design/Serialization/DesignerLoaderTests.cs",
        "Design/Serialization/InstanceDescriptorTests.cs",
        "Design/Serialization/MemberRelationshipServiceTests.cs",
        "Design/Serialization/MemberRelationshipTests.cs",
        "Design/Serialization/ResolveNameEventArgsTests.cs",
        "Design/Serialization/RootDesignerSerializerAttributeTests.cs",
        "Design/Serialization/SerializationStoreTests.cs",
        "Design/ServiceContainerTests.cs",
        "Design/StandardCommandsTests.cs",
        "Design/StandardToolWindowsTests.cs",
        "DesignTimeVisibleAttributeTests.cs",
        "DoubleConverterTests.cs",
        "Drawing/ColorConverterTests.cs",
        "Drawing/PointConverterTests.cs",
        "Drawing/RectangleConverterTests.cs",
        "Drawing/SizeConverterTests.cs",
        "Drawing/SizeFConverterTests.cs",
        "Drawing/StringTypeConverterTestBase.cs",
        "EnumConverterTest.cs",
        "EventDescriptorCollectionTests.cs",
        "EventDescriptorTests.cs",
        "ExtenderProvidedPropertyAttributeTests.cs",
        "Extensions/EnumeratorExtensions.cs",
        "GuidConverterTests.cs",
        "HalfConverterTests.cs",
        "HandledEventArgsTests.cs",
        "InheritanceAttributeTests.cs",
        "InstallerTypeAttributeTests.cs",
        "InstanceCreationEditorTests.cs",
        "Int128ConverterTests.cs",
        "Int16ConverterTests.cs",
        "Int32ConverterTests.cs",
        "Int64ConverterTests.cs",
        "LicenseContextTests.cs",
        "LicenseExceptionTests.cs",
        "LicenseManagerTests.cs",
        "LicenseProviderAttributeTests.cs",
        "ListBindableAttributeTests.cs",
        "ListChangedEventArgsTests.cs",
        "ListSortDescriptionTests.cs",
        "LookupBindingPropertiesAttributeTests.cs",
        "MarshalByValueComponentTests.cs",
        "MaskedTextProviderTests.cs",
        "MemberDescriptorTests.cs",
        "Mocks/MockDesigner.cs",
        "Mocks/MockDesignerHost.cs",
        "Mocks/MockEventDescriptor.cs",
        "Mocks/MockPropertyDescriptor.cs",
        "Mocks/MockServiceProvider.cs",
        "MultilineStringConverterTests.cs",
        "NestedContainerTests.cs",
        "NullableConverterTests.cs",
        "PasswordPropertyTextAttributeTests.cs",
        "PropertyDescriptorCollectionTests.cs",
        "PropertyDescriptorTests.cs",
        "ProvidePropertyAttributeTests.cs",
        "RecommendedAsConfigurableAttributeTests.cs",
        "ReferenceConverterTests.cs",
        "ReflectTypeDescriptionProviderTests.cs",
        "ReflectionCachesUpdateHandlerTests.cs",
        "RefreshEventArgsTests.cs",
        "Resources/TestResx.Designer.cs",
        "RunInstallerAttributeTests.cs",
        "SByteConverterTests.cs",
        "SampleClasses.cs",
        "SettingsBindableAttributeTests.cs",
        "SingleConverterTests.cs",
        "StringConverterTests.cs",
        "SyntaxCheckTests.cs",
        "TestDesignerHost.cs",
        "TimeOnlyConverterTests.cs",
        "TimeSpanConverterTests.cs",
        "TimerTests.cs",
        "Timers/TimersDescriptionAttributeTests.cs",
        "ToolboxItemAttributeTests.cs",
        "ToolboxItemFilterAttributeTests.cs",
        "TypeConverterAttributeTests.cs",
        "TypeConverterTestBase.cs",
        "TypeConverterTests.cs",
        "TypeDescriptionProviderAttributeTests.cs",
        "TypeListConverterTests.cs",
        "UInt128ConverterTests.cs",
        "UInt16ConverterTests.cs",
        "UInt32ConverterTests.cs",
        "UInt64ConverterTests.cs",
        "UriTypeConverterTests.cs",
        "VersionConverterTests.cs",
        "WarningExceptionTests.cs",
    ],
    deps = [
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    defines = ["FUNCTIONAL_TESTS"],
    resources = [":TestResx"],
    resource_logical_names = {"TestResx.resources": "Resources.TestResx.resources"},
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
    nowarn = ["SYSLIB0011"],
    size = "large",
)
