load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Reflection.Metadata.Tests",
    srcs = [
        "Metadata/AssemblyNameInfoTests.cs",
        "Metadata/BlobContentIdTests.cs",
        "Metadata/BlobTests.cs",
        "Metadata/BlobUtilitiesTests.cs",
        "Metadata/Decoding/CustomAttributeDecoderTests.cs",
        "Metadata/Decoding/DisassemblingTypeProvider.cs",
        "Metadata/Decoding/MethodSignatureTests.cs",
        "Metadata/Decoding/OpaqueHandleTypeProvider.cs",
        "Metadata/Decoding/SignatureDecoderTests.cs",
        "Metadata/Ecma335/CodedIndexTests.cs",
        "Metadata/Ecma335/Encoding/BlobEncodersTests.cs",
        "Metadata/Ecma335/Encoding/ControlFlowBuilderTests.cs",
        "Metadata/Ecma335/Encoding/ExceptionRegionEncoderTests.cs",
        "Metadata/Ecma335/Encoding/InstructionEncoderTests.cs",
        "Metadata/Ecma335/Encoding/LabelHandleTests.cs",
        "Metadata/Ecma335/Encoding/MethodBodyStreamEncoderTests.cs",
        "Metadata/Ecma335/MetadataAggregatorTests.cs",
        "Metadata/Ecma335/MetadataBuilderTests.cs",
        "Metadata/Ecma335/MetadataRootBuilderTests.cs",
        "Metadata/Ecma335/MetadataTokensTests.cs",
        "Metadata/Ecma335/PortablePdbBuilderTests.cs",
        "Metadata/HandleComparerTests.cs",
        "Metadata/HandleTests.cs",
        "Metadata/LargeTablesAndHeapsTests.cs",
        "Metadata/MetadataReaderProviderTests.cs",
        "Metadata/MetadataReaderTestHelpers.cs",
        "Metadata/MetadataReaderTests.cs",
        "Metadata/PortablePdb/DocumentNameTests.cs",
        "Metadata/PortablePdb/StandalonePortablePdbStreamTests.cs",
        "Metadata/TagToTokenTests.cs",
        "Metadata/TypeNameParserHelpersTests.cs",
        "Metadata/TypeNameParserSamples.cs",
        "Metadata/TypeNameTests.cs",
        "Metadata/TypeSystem/AssemblyDefinitionTests.cs",
        "Metadata/TypeSystem/AssemblyReferenceTests.cs",
        "Metadata/TypeSystem/ClassLayoutRow.cs",
        "Metadata/TypeSystem/MethodImportRow.cs",
        "Metadata/TypeSystem/TypeDefinitionTests.cs",
        "PortableExecutable/BadImageFormat.cs",
        "PortableExecutable/DebugDirectoryBuilderTests.cs",
        "PortableExecutable/DebugDirectoryTests.cs",
        "PortableExecutable/PEBinaryReaderTests.cs",
        "PortableExecutable/PEBuilderTests.cs",
        "PortableExecutable/PEHeaderBuilderTests.cs",
        "PortableExecutable/PEHeadersTests.cs",
        "PortableExecutable/PEMemoryBlockTests.cs",
        "PortableExecutable/PEReaderTests.cs",
        "PortableExecutable/SectionHeaderTests.cs",
        "PortableExecutable/TestStream.cs",
        "PortableExecutable/TestStreamBase.cs",
        "Resources/TestResources.cs",
        "TestUtilities/AssertEx.cs",
        "TestUtilities/ByteArrayUtilities.cs",
        "TestUtilities/CustomAccessMemoryStream.cs",
        "TestUtilities/DiffUtil.cs",
        "TestUtilities/LoaderUtilities.cs",
        "TestUtilities/PinnedBlob.cs",
        "TestUtilities/SigningUtilities.cs",
        "TestUtilities/TestBuilders.cs",
        "TestUtilities/TestMetadataResolver.cs",
        "TestUtilities/TestMetadataStringDecoder.cs",
        "Utilities/AbstractMemoryBlockTests.cs",
        "Utilities/BlobReaderTests.cs",
        "Utilities/CompressedIntegerTests.cs",
        "Utilities/HashTests.cs",
        "Utilities/MemoryBlockTests.cs",
        "Utilities/OrderByTests.cs",
        "Utilities/StringUtilsTests.cs",
    ] + [
        "//src/libraries/Common/tests:System/IO/TempFile.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/SignatureSupport.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.FreeLibrary.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.GetModuleHandle.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.LoadLibraryEx.cs",
        "//src/libraries/Common:src/Microsoft/Win32/SafeHandles/SafeLibraryHandle.cs",
    ],
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    deps = [
        "//src/libraries/System.Reflection.Metadata:impl_System.Reflection.Metadata",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.IO.MemoryMappedFiles:ref_System.IO.MemoryMappedFiles",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries:ref_System.Linq.Expressions",
        "//src/libraries:ref_System.Text.RegularExpressions",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    resources = [
        "Resources/Interop/IndexerWithByRefParam.dll",
        "Resources/Interop/Interop.Mock01.Impl.dll",
        "Resources/Interop/Interop.Mock01.dll",
        "Resources/Interop/OtherAccessors.dll",
        "Resources/Misc/CPPClassLibrary2.obj",
        "Resources/Misc/Debug.dll",
        "Resources/Misc/Deterministic.dll",
        "Resources/Misc/EmptyType.dll",
        "Resources/Misc/KeyPair.snk",
        "Resources/Misc/Members.dll",
        "Resources/Misc/SatelliteAssembly.resources.dll",
        "Resources/Misc/Signed.exe",
        "Resources/Namespace/NamespaceForwardedCS.dll",
        "Resources/Namespace/NamespaceTests.dll",
        "Resources/NetModule/AppCS.exe",
        "Resources/NetModule/ModuleCS00.mod",
        "Resources/NetModule/ModuleCS01.mod",
        "Resources/NetModule/ModuleVB01.mod",
        "Resources/PortablePdbs/Documents.Embedded.dll",
        "Resources/PortablePdbs/Documents.dll",
        "Resources/PortablePdbs/Documents.pdb",
        "Resources/WinRT/Lib.winmd",
    ],
    resource_logical_names = {
        "IndexerWithByRefParam.dll": "System.Reflection.Metadata.Tests.Resources.Interop.IndexerWithByRefParam.dll",
        "OtherAccessors.dll": "System.Reflection.Metadata.Tests.Resources.Interop.OtherAccessors.dll",
        "Interop.Mock01.dll": "System.Reflection.Metadata.Tests.Resources.Interop.Interop.Mock01.dll",
        "Interop.Mock01.Impl.dll": "System.Reflection.Metadata.Tests.Resources.Interop.Interop.Mock01.Impl.dll",
        "CPPClassLibrary2.obj": "System.Reflection.Metadata.Tests.Resources.Misc.CPPClassLibrary2.obj",
        "Debug.dll": "System.Reflection.Metadata.Tests.Resources.Misc.Debug.dll",
        "Deterministic.dll": "System.Reflection.Metadata.Tests.Resources.Misc.Deterministic.dll",
        "EmptyType.dll": "System.Reflection.Metadata.Tests.Resources.Misc.EmptyType.dll",
        "KeyPair.snk": "System.Reflection.Metadata.Tests.Resources.Misc.KeyPair.snk",
        "Members.dll": "System.Reflection.Metadata.Tests.Resources.Misc.Members.dll",
        "SatelliteAssembly.resources.dll": "System.Reflection.Metadata.Tests.Resources.Misc.SatelliteAssembly.resources.dll",
        "Signed.exe": "System.Reflection.Metadata.Tests.Resources.Misc.Signed.exe",
        "NamespaceForwardedCS.dll": "System.Reflection.Metadata.Tests.Resources.Namespace.NamespaceForwardedCS.dll",
        "NamespaceTests.dll": "System.Reflection.Metadata.Tests.Resources.Namespace.NamespaceTests.dll",
        "AppCS.exe": "System.Reflection.Metadata.Tests.Resources.NetModule.AppCS.exe",
        "ModuleCS00.mod": "System.Reflection.Metadata.Tests.Resources.NetModule.ModuleCS00.mod",
        "ModuleCS01.mod": "System.Reflection.Metadata.Tests.Resources.NetModule.ModuleCS01.mod",
        "ModuleVB01.mod": "System.Reflection.Metadata.Tests.Resources.NetModule.ModuleVB01.mod",
        "Documents.dll": "System.Reflection.Metadata.Tests.Resources.PortablePdbs.Documents.dll",
        "Documents.pdb": "System.Reflection.Metadata.Tests.Resources.PortablePdbs.Documents.pdb",
        "Documents.Embedded.dll": "System.Reflection.Metadata.Tests.Resources.PortablePdbs.Documents.Embedded.dll",
        "Lib.winmd": "System.Reflection.Metadata.Tests.Resources.WinRT.Lib.winmd",
    },
    nowarn = [
        "CS0436",
        "SYSLIB0037",
    ],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
