load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "mutualrecurthd-tls",
    srcs = ["MutualRecurThd-TLS.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "test-tls",
    srcs = ["Test-TLS.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)
