load("//src/tests:live_test.bzl", "library_test")

genrule(
    name = "mono_testdata",
    srcs = ["System.Data.DataSetExtensions.Tests/Mono/testdataset1.xml"],
    outs = ["Mono/testdataset1.xml"],
    cmd = "cp $< $@",
)

library_test(
    name = "System.Data.Common.Tests",
    srcs = [
        "DataProvider.cs",
        "System.Data.DataSetExtensions.Tests/Mono/DataRowComparerTest.cs",
        "System.Data.DataSetExtensions.Tests/Mono/DataRowExtensionsTest.cs",
        "System.Data.DataSetExtensions.Tests/Mono/DataTableExtensionsTest.cs",
        "System.Data.DataSetExtensions.Tests/Mono/EnumerableRowCollectionTest.cs",
        "System.Data.DataSetExtensions.Tests/System/Data/DataRowComparerTests.cs",
        "System.Data.DataSetExtensions.Tests/System/Data/DataRowExtensionsTests.cs",
        "System.Data.DataSetExtensions.Tests/System/Data/DataTableExtensionsTests.cs",
        "System.Data.DataSetExtensions.Tests/System/Data/EnumerableRowCollectionExtensionsTests.cs",
        "System.Data.DataSetExtensions.Tests/System/Data/TypedTableBaseExtensionsTests.cs",
        "System/Data/Common/DataAdapterTest.cs",
        "System/Data/Common/DataColumnMappingCollectionTest.cs",
        "System/Data/Common/DataColumnMappingTest.cs",
        "System/Data/Common/DataTableMappingCollectionTest.cs",
        "System/Data/Common/DataTableMappingCollectionTest2.cs",
        "System/Data/Common/DataTableMappingTest.cs",
        "System/Data/Common/DbCommandBuilderTest.cs",
        "System/Data/Common/DbCommandTests.cs",
        "System/Data/Common/DbConnectionStringBuilderTest.cs",
        "System/Data/Common/DbConnectionTests.cs",
        "System/Data/Common/DbDataAdapterTest.cs",
        "System/Data/Common/DbDataReaderMock.cs",
        "System/Data/Common/DbDataReaderTest.cs",
        "System/Data/Common/DbExceptionTests.cs",
        "System/Data/Common/DbProviderFactoryTest.cs",
        "System/Data/Common/DbTransactionTest.cs",
        "System/Data/Common/RowUpdatedEventArgsTest.cs",
        "System/Data/Common/RowUpdatingEventArgsTest.cs",
        "System/Data/ConstraintCollectionTest.cs",
        "System/Data/ConstraintCollectionTest2.cs",
        "System/Data/ConstraintExceptionTest.cs",
        "System/Data/ConstraintTest.cs",
        "System/Data/DBConcurrencyExceptionTest.cs",
        "System/Data/DataColumnCollectionTest.cs",
        "System/Data/DataColumnCollectionTest2.cs",
        "System/Data/DataColumnExpressionTest.cs",
        "System/Data/DataColumnTest.cs",
        "System/Data/DataColumnTest2.cs",
        "System/Data/DataCommonEventSourceTest.cs",
        "System/Data/DataExceptionTest.cs",
        "System/Data/DataRelationCollectionTest.cs",
        "System/Data/DataRelationCollectionTest2.cs",
        "System/Data/DataRelationTest.cs",
        "System/Data/DataRelationTest2.cs",
        "System/Data/DataRowCollectionTest.cs",
        "System/Data/DataRowCollectionTest2.cs",
        "System/Data/DataRowTest.cs",
        "System/Data/DataRowTest2.cs",
        "System/Data/DataRowViewTest.cs",
        "System/Data/DataRowViewTest2.cs",
        "System/Data/DataSet1.Designer.cs",
        "System/Data/DataSetAssertion.cs",
        "System/Data/DataSetInferXmlSchemaTest.cs",
        "System/Data/DataSetReadXmlSchemaTest.cs",
        "System/Data/DataSetReadXmlTest.cs",
        "System/Data/DataSetTest.cs",
        "System/Data/DataSetTest2.cs",
        "System/Data/DataSetTypedDataSetTest.cs",
        "System/Data/DataSetWriteXMLTest.cs",
        "System/Data/DataTableCollectionTest.cs",
        "System/Data/DataTableCollectionTest2.cs",
        "System/Data/DataTableExtensionsTest.cs",
        "System/Data/DataTableLoadRowTest.cs",
        "System/Data/DataTableReadWriteXmlTest.cs",
        "System/Data/DataTableReadXmlSchemaTest.cs",
        "System/Data/DataTableReaderTest.cs",
        "System/Data/DataTableTest.cs",
        "System/Data/DataTableTest2.cs",
        "System/Data/DataTableTest3.cs",
        "System/Data/DataTableTest4.cs",
        "System/Data/DataTableTest5.cs",
        "System/Data/DataViewManagerTest.cs",
        "System/Data/DataViewTest.cs",
        "System/Data/DataViewTest2.cs",
        "System/Data/DataViewTest_IBindingList.cs",
        "System/Data/DataViewTest_IBindingListView.cs",
        "System/Data/DeletedRowInaccessibleExceptionTest.cs",
        "System/Data/DuplicateNameExceptionTest.cs",
        "System/Data/EvaluateExceptionTest.cs",
        "System/Data/ForeignKeyConstraintTest.cs",
        "System/Data/ForeignKeyConstraintTest2.cs",
        "System/Data/InRowChangingEventExceptionTest.cs",
        "System/Data/InvalidConstraintExceptionTest.cs",
        "System/Data/MissingPrimaryKeyExceptionTest.cs",
        "System/Data/MonkeyDataSet.cs",
        "System/Data/NoNullAllowedExceptionTest.cs",
        "System/Data/ReadOnlyExceptionTest.cs",
        "System/Data/RestrictedTypeHandlingTests.cs",
        "System/Data/RowNotInTableExceptionTest.cs",
        "System/Data/SqlTypes/SqlBinaryTest.cs",
        "System/Data/SqlTypes/SqlBooleanTest.cs",
        "System/Data/SqlTypes/SqlByteTest.cs",
        "System/Data/SqlTypes/SqlBytesTest.cs",
        "System/Data/SqlTypes/SqlCharsTest.cs",
        "System/Data/SqlTypes/SqlDateTimeTest.cs",
        "System/Data/SqlTypes/SqlDecimalTest.cs",
        "System/Data/SqlTypes/SqlDoubleTest.cs",
        "System/Data/SqlTypes/SqlGuidTest.cs",
        "System/Data/SqlTypes/SqlInt16Test.cs",
        "System/Data/SqlTypes/SqlInt32Test.cs",
        "System/Data/SqlTypes/SqlInt64Test.cs",
        "System/Data/SqlTypes/SqlMoneyTest.cs",
        "System/Data/SqlTypes/SqlSingleTest.cs",
        "System/Data/SqlTypes/SqlStringSortingTest.cs",
        "System/Data/SqlTypes/SqlStringTest.cs",
        "System/Data/SqlTypes/SqlXmlTest.cs",
        "System/Data/SyntaxErrorExceptionTest.cs",
        "System/Data/TrailingSpaceTest.cs",
        "System/Data/UniqueConstraintTest.cs",
        "System/Data/UniqueConstraintTest2.cs",
        "System/Data/VersionNotFoundException.cs",
        "System/Data/XmlDataLoaderTest.cs",
        "System/Data/XmlDataReaderTest.cs",
        "System/Xml/XmlDataDocumentTests.cs",
    ] + [
        "//src/libraries/Common/tests:System/Diagnostics/Tracing/TestEventListener.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs",
    ],
    deps = [
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XmlSerializer:ref_System.Xml.XmlSerializer",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Text.Encoding.CodePages:ref_System.Text.Encoding.CodePages",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
    data = [
        "@paket.main//system.data.common.testdata:content_files",
        ":mono_testdata",
    ],
    nowarn = ["0168", "0169", "0414", "0219", "0649", "SYSLIB0011", "SYSLIB0051"],
    size = "large",
)
