load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly", "netcoreapp_ref_assembly", "ref_impl_pair")

netcoreapp_ref_assembly(
    name = "ref_System.Reflection.MetadataLoadContext",
    srcs = [
        "ref/System.Reflection.MetadataLoadContext.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Reflection.MetadataLoadContext",
    srcs = [
        "src/System/CoreRtBridge.cs",
        "src/System/Reflection/DefaultBinder.CanConvert.cs",
        "src/System/Reflection/DefaultBinder.cs",
        "src/System/Reflection/MetadataAssemblyResolver.cs",
        "src/System/Reflection/MetadataLoadContext.Apis.cs",
        "src/System/Reflection/MetadataLoadContext.CoreAssembly.cs",
        "src/System/Reflection/MetadataLoadContext.Disposing.cs",
        "src/System/Reflection/MetadataLoadContext.KnownConstructors.cs",
        "src/System/Reflection/MetadataLoadContext.Loading.cs",
        "src/System/Reflection/MetadataLoadContext.Resolving.cs",
        "src/System/Reflection/PathAssemblyResolver.cs",
        "src/System/Reflection/Runtime/AssemblyNameHelpers.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/ConstructorPolicies.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/EventPolicies.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/FieldPolicies.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/MemberPolicies.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/MemberTypeIndex.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/MethodPolicies.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/NameFilter.Ecma.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/NameFilter.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/NestedTypePolicies.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/PropertyPolicies.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/QueriedMemberList.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/QueryResult.Enumerator.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/QueryResult.cs",
        "src/System/Reflection/Runtime/BindingFlagSupport/Shared.cs",
        "src/System/Reflection/Runtime/General/ListBuilder.cs",
        "src/System/Reflection/Runtime/SignatureTypeExtensions.cs",
        "src/System/Reflection/TypeLoading/Assemblies/AssemblyFileInfo.cs",
        "src/System/Reflection/TypeLoading/Assemblies/Ecma/EcmaAssembly.GetName.cs",
        "src/System/Reflection/TypeLoading/Assemblies/Ecma/EcmaAssembly.ManifestResources.cs",
        "src/System/Reflection/TypeLoading/Assemblies/Ecma/EcmaAssembly.Modules.cs",
        "src/System/Reflection/TypeLoading/Assemblies/Ecma/EcmaAssembly.cs",
        "src/System/Reflection/TypeLoading/Assemblies/RoAssembly.GetForwardedTypes.cs",
        "src/System/Reflection/TypeLoading/Assemblies/RoAssembly.Modules.cs",
        "src/System/Reflection/TypeLoading/Assemblies/RoAssembly.cs",
        "src/System/Reflection/TypeLoading/Assemblies/RoExceptionAssembly.cs",
        "src/System/Reflection/TypeLoading/Assemblies/RoStubAssembly.cs",
        "src/System/Reflection/TypeLoading/Constructors/RoConstructor.cs",
        "src/System/Reflection/TypeLoading/Constructors/RoDefinitionConstructor.cs",
        "src/System/Reflection/TypeLoading/Constructors/RoSyntheticConstructor.cs",
        "src/System/Reflection/TypeLoading/CustomAttributes/CustomAttributeArguments.cs",
        "src/System/Reflection/TypeLoading/CustomAttributes/CustomAttributeHelpers.cs",
        "src/System/Reflection/TypeLoading/CustomAttributes/Ecma/EcmaCustomAttributeData.cs",
        "src/System/Reflection/TypeLoading/CustomAttributes/Ecma/EcmaCustomAttributeHelpers.cs",
        "src/System/Reflection/TypeLoading/CustomAttributes/RoCustomAttributeData.cs",
        "src/System/Reflection/TypeLoading/CustomAttributes/RoPseudoCustomAttributeData.cs",
        "src/System/Reflection/TypeLoading/Events/Ecma/EcmaEvent.cs",
        "src/System/Reflection/TypeLoading/Events/RoEvent.cs",
        "src/System/Reflection/TypeLoading/Fields/Ecma/EcmaField.cs",
        "src/System/Reflection/TypeLoading/Fields/RoField.cs",
        "src/System/Reflection/TypeLoading/General/AssemblyNameData.cs",
        "src/System/Reflection/TypeLoading/General/Assignability.cs",
        "src/System/Reflection/TypeLoading/General/CoreType.cs",
        "src/System/Reflection/TypeLoading/General/CoreTypes.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/EcmaDefaultValueProcessing.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/EcmaHelpers.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/EcmaPinnedTypeProvider.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/EcmaSignatureTypeProviderForToString.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/EcmaToStringHelpers.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/EcmaWrappedTypeProvider.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/GuardedPEReader.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/InternalManifestResourceInfo.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/MetadataExtensions.cs",
        "src/System/Reflection/TypeLoading/General/Ecma/MetadataTable.cs",
        "src/System/Reflection/TypeLoading/General/HashHelpers.cs",
        "src/System/Reflection/TypeLoading/General/Helpers.cs",
        "src/System/Reflection/TypeLoading/General/MethodSig.cs",
        "src/System/Reflection/TypeLoading/General/RoAssemblyName.cs",
        "src/System/Reflection/TypeLoading/General/Sentinels.cs",
        "src/System/Reflection/TypeLoading/General/TypeContext.cs",
        "src/System/Reflection/TypeLoading/General/TypeExtensions.net.cs",
        "src/System/Reflection/TypeLoading/General/TypeFactories.cs",
        "src/System/Reflection/TypeLoading/General/Utf8Constants.cs",
        "src/System/Reflection/TypeLoading/MethodBase/Ecma/EcmaMethodBody.cs",
        "src/System/Reflection/TypeLoading/MethodBase/Ecma/EcmaMethodDecoder.cs",
        "src/System/Reflection/TypeLoading/MethodBase/IMethodDecoder.cs",
        "src/System/Reflection/TypeLoading/MethodBase/IRoMethodBase.cs",
        "src/System/Reflection/TypeLoading/MethodBase/RoExceptionHandlingClause.cs",
        "src/System/Reflection/TypeLoading/MethodBase/RoLocalVariableInfo.cs",
        "src/System/Reflection/TypeLoading/MethodBase/RoMethodBody.cs",
        "src/System/Reflection/TypeLoading/Methods/RoConstructedGenericMethod.cs",
        "src/System/Reflection/TypeLoading/Methods/RoDefinitionMethod.DllImport.cs",
        "src/System/Reflection/TypeLoading/Methods/RoDefinitionMethod.cs",
        "src/System/Reflection/TypeLoading/Methods/RoMethod.cs",
        "src/System/Reflection/TypeLoading/Methods/RoSyntheticMethod.cs",
        "src/System/Reflection/TypeLoading/Modules/Ecma/EcmaModule.GetTypeCore.cs",
        "src/System/Reflection/TypeLoading/Modules/Ecma/EcmaModule.ManifestResources.cs",
        "src/System/Reflection/TypeLoading/Modules/Ecma/EcmaModule.MetadataTables.cs",
        "src/System/Reflection/TypeLoading/Modules/Ecma/EcmaModule.TypeProvider.cs",
        "src/System/Reflection/TypeLoading/Modules/Ecma/EcmaModule.cs",
        "src/System/Reflection/TypeLoading/Modules/GetTypeCoreCache.cs",
        "src/System/Reflection/TypeLoading/Modules/RoModule.Unifier.cs",
        "src/System/Reflection/TypeLoading/Modules/RoModule.cs",
        "src/System/Reflection/TypeLoading/Modules/RoResourceModule.cs",
        "src/System/Reflection/TypeLoading/Parameters/Ecma/EcmaFatMethodParameter.cs",
        "src/System/Reflection/TypeLoading/Parameters/RoFatMethodParameter.cs",
        "src/System/Reflection/TypeLoading/Parameters/RoMethodParameter.cs",
        "src/System/Reflection/TypeLoading/Parameters/RoParameter.cs",
        "src/System/Reflection/TypeLoading/Parameters/RoPropertyIndexParameter.cs",
        "src/System/Reflection/TypeLoading/Parameters/RoThinMethodParameter.cs",
        "src/System/Reflection/TypeLoading/Properties/Ecma/EcmaProperty.cs",
        "src/System/Reflection/TypeLoading/Properties/RoProperty.cs",
        "src/System/Reflection/TypeLoading/RuntimeTypeInfo.BindingFlags.cs",
        "src/System/Reflection/TypeLoading/RuntimeTypeInfo.GetMember.cs",
        "src/System/Reflection/TypeLoading/RuntimeTypeInfo.TypeComponentsCache.cs",
        "src/System/Reflection/TypeLoading/Types/Ecma/EcmaDefinitionType.BindingFlags.cs",
        "src/System/Reflection/TypeLoading/Types/Ecma/EcmaDefinitionType.cs",
        "src/System/Reflection/TypeLoading/Types/Ecma/EcmaGenericMethodParameterType.cs",
        "src/System/Reflection/TypeLoading/Types/Ecma/EcmaGenericParameterType.cs",
        "src/System/Reflection/TypeLoading/Types/Ecma/EcmaGenericTypeParameterType.cs",
        "src/System/Reflection/TypeLoading/Types/RoArrayType.Key.cs",
        "src/System/Reflection/TypeLoading/Types/RoArrayType.cs",
        "src/System/Reflection/TypeLoading/Types/RoByRefType.cs",
        "src/System/Reflection/TypeLoading/Types/RoConstructedGenericType.Key.cs",
        "src/System/Reflection/TypeLoading/Types/RoConstructedGenericType.cs",
        "src/System/Reflection/TypeLoading/Types/RoDefinitionType.cs",
        "src/System/Reflection/TypeLoading/Types/RoExceptionType.cs",
        "src/System/Reflection/TypeLoading/Types/RoFunctionPointerType.cs",
        "src/System/Reflection/TypeLoading/Types/RoGenericParameterType.cs",
        "src/System/Reflection/TypeLoading/Types/RoHasElementType.cs",
        "src/System/Reflection/TypeLoading/Types/RoInstantiationProviderType.cs",
        "src/System/Reflection/TypeLoading/Types/RoModifiedFunctionPointerType.cs",
        "src/System/Reflection/TypeLoading/Types/RoModifiedGenericType.cs",
        "src/System/Reflection/TypeLoading/Types/RoModifiedHasElementType.cs",
        "src/System/Reflection/TypeLoading/Types/RoModifiedStandaloneType.cs",
        "src/System/Reflection/TypeLoading/Types/RoModifiedType.cs",
        "src/System/Reflection/TypeLoading/Types/RoPinnedType.cs",
        "src/System/Reflection/TypeLoading/Types/RoPointerType.cs",
        "src/System/Reflection/TypeLoading/Types/RoStubType.cs",
        "src/System/Reflection/TypeLoading/Types/RoType.GetInterface.cs",
        "src/System/Reflection/TypeLoading/Types/RoType.TypeClassification.cs",
        "src/System/Reflection/TypeLoading/Types/RoType.cs",
        "src/System/Reflection/TypeLoading/Types/RoWrappedType.cs",
        "src/System/ThrowHelper.cs",
    ] + [
        "//src/libraries/Common:src/System/Obsoletions.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Reflection.Metadata:ref_System.Reflection.Metadata",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)

ref_impl_pair(
    name = "live_System.Reflection.MetadataLoadContext",
    ref = ":ref_System.Reflection.MetadataLoadContext",
    lib = ":impl_System.Reflection.MetadataLoadContext",
    visibility = ["//visibility:public"],
)
