load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Private.DataContractSerialization",
    analyzers = [
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    srcs = [
        "src/System/Runtime/Serialization/AccessorBuilder.cs",
        "src/System/Runtime/Serialization/Attributes.cs",
        "src/System/Runtime/Serialization/BitFlagsGenerator.cs",
        "src/System/Runtime/Serialization/ClassDataContract.cs",
        "src/System/Runtime/Serialization/CodeGenerator.cs",
        "src/System/Runtime/Serialization/CollectionDataContract.cs",
        "src/System/Runtime/Serialization/ContextAware.cs",
        "src/System/Runtime/Serialization/DataContract.cs",
        "src/System/Runtime/Serialization/DataContractResolver.cs",
        "src/System/Runtime/Serialization/DataContractSerializer.cs",
        "src/System/Runtime/Serialization/DataContractSerializerExtensions.cs",
        "src/System/Runtime/Serialization/DataContractSerializerSettings.cs",
        "src/System/Runtime/Serialization/DataContractSet.cs",
        "src/System/Runtime/Serialization/DataContractSurrogateCaller.cs",
        "src/System/Runtime/Serialization/DataMember.cs",
        "src/System/Runtime/Serialization/DateTimeOffsetAdapter.cs",
        "src/System/Runtime/Serialization/DictionaryGlobals.cs",
        "src/System/Runtime/Serialization/EnumDataContract.cs",
        "src/System/Runtime/Serialization/ExceptionUtility.cs",
        "src/System/Runtime/Serialization/ExportOptions.cs",
        "src/System/Runtime/Serialization/ExtensionDataObject.cs",
        "src/System/Runtime/Serialization/ExtensionDataReader.cs",
        "src/System/Runtime/Serialization/GenericParameterDataContract.cs",
        "src/System/Runtime/Serialization/Globals.cs",
        "src/System/Runtime/Serialization/HybridObjectCache.cs",
        "src/System/Runtime/Serialization/IExtensibleDataObject.cs",
        "src/System/Runtime/Serialization/Json/ByteArrayHelperWithString.cs",
        "src/System/Runtime/Serialization/Json/DataContractJsonSerializer.cs",
        "src/System/Runtime/Serialization/Json/DataContractJsonSerializerExtensions.cs",
        "src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs",
        "src/System/Runtime/Serialization/Json/DateTimeFormat.cs",
        "src/System/Runtime/Serialization/Json/EmitTypeInformation.cs",
        "src/System/Runtime/Serialization/Json/IXmlJsonReaderInitializer.cs",
        "src/System/Runtime/Serialization/Json/IXmlJsonWriterInitializer.cs",
        "src/System/Runtime/Serialization/Json/JsonByteArrayDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonClassDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonCollectionDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonEncodingStreamWrapper.cs",
        "src/System/Runtime/Serialization/Json/JsonEnumDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonFormatGeneratorStatics.cs",
        "src/System/Runtime/Serialization/Json/JsonFormatReaderGenerator.cs",
        "src/System/Runtime/Serialization/Json/JsonFormatWriterGenerator.cs",
        "src/System/Runtime/Serialization/Json/JsonGlobals.cs",
        "src/System/Runtime/Serialization/Json/JsonNodeType.cs",
        "src/System/Runtime/Serialization/Json/JsonObjectDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonQNameDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonReaderDelegator.cs",
        "src/System/Runtime/Serialization/Json/JsonReaderWriterFactory.cs",
        "src/System/Runtime/Serialization/Json/JsonStringDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonUriDataContract.cs",
        "src/System/Runtime/Serialization/Json/JsonWriterDelegator.cs",
        "src/System/Runtime/Serialization/Json/JsonXmlDataContract.cs",
        "src/System/Runtime/Serialization/Json/ReflectionJsonFormatReader.cs",
        "src/System/Runtime/Serialization/Json/ReflectionJsonFormatWriter.cs",
        "src/System/Runtime/Serialization/Json/XmlJsonReader.cs",
        "src/System/Runtime/Serialization/Json/XmlJsonWriter.cs",
        "src/System/Runtime/Serialization/Json/XmlObjectSerializerReadContextComplexJson.cs",
        "src/System/Runtime/Serialization/Json/XmlObjectSerializerWriteContextComplexJson.cs",
        "src/System/Runtime/Serialization/KnownTypeDataContractResolver.cs",
        "src/System/Runtime/Serialization/MemoryStreamAdapter.cs",
        "src/System/Runtime/Serialization/ObjectReferenceStack.cs",
        "src/System/Runtime/Serialization/ObjectToIdCache.cs",
        "src/System/Runtime/Serialization/PrimitiveDataContract.cs",
        "src/System/Runtime/Serialization/ReflectionClassWriter.cs",
        "src/System/Runtime/Serialization/ReflectionReader.cs",
        "src/System/Runtime/Serialization/ReflectionXmlFormatReader.cs",
        "src/System/Runtime/Serialization/ReflectionXmlFormatWriter.cs",
        "src/System/Runtime/Serialization/SchemaExporter.cs",
        "src/System/Runtime/Serialization/SchemaHelper.cs",
        "src/System/Runtime/Serialization/SchemaImporter.cs",
        "src/System/Runtime/Serialization/ScopedKnownTypes.cs",
        "src/System/Runtime/Serialization/SerializationOption.cs",
        "src/System/Runtime/Serialization/SpecialTypeDataContract.cs",
        "src/System/Runtime/Serialization/XPathQueryGenerator.cs",
        "src/System/Runtime/Serialization/XmlDataContract.cs",
        "src/System/Runtime/Serialization/XmlFormatGeneratorStatics.cs",
        "src/System/Runtime/Serialization/XmlFormatReaderGenerator.cs",
        "src/System/Runtime/Serialization/XmlFormatWriterGenerator.cs",
        "src/System/Runtime/Serialization/XmlObjectSerializer.cs",
        "src/System/Runtime/Serialization/XmlObjectSerializerContext.cs",
        "src/System/Runtime/Serialization/XmlObjectSerializerReadContext.cs",
        "src/System/Runtime/Serialization/XmlObjectSerializerReadContextComplex.cs",
        "src/System/Runtime/Serialization/XmlObjectSerializerWriteContext.cs",
        "src/System/Runtime/Serialization/XmlObjectSerializerWriteContextComplex.cs",
        "src/System/Runtime/Serialization/XmlReaderDelegator.cs",
        "src/System/Runtime/Serialization/XmlSerializableReader.cs",
        "src/System/Runtime/Serialization/XmlSerializableServices.cs",
        "src/System/Runtime/Serialization/XmlSerializableWriter.cs",
        "src/System/Runtime/Serialization/XmlWriterDelegator.cs",
        "src/System/Runtime/Serialization/XsdDataContractExporter.cs",
        "src/System/Text/Base64Encoding.cs",
        "src/System/Text/BinHexEncoding.cs",
        "src/System/Text/SurrogateChar.cs",
        "src/System/Xml/ArrayHelper.cs",
        "src/System/Xml/BytesWithOffset.cs",
        "src/System/Xml/EncodingStreamWrapper.cs",
        "src/System/Xml/IFragmentCapableXmlDictionaryWriter.cs",
        "src/System/Xml/IStreamProvider.cs",
        "src/System/Xml/IXmlDictionary.cs",
        "src/System/Xml/PrefixHandle.cs",
        "src/System/Xml/StringHandle.cs",
        "src/System/Xml/UniqueId.cs",
        "src/System/Xml/ValueHandle.cs",
        "src/System/Xml/XmlBaseReader.cs",
        "src/System/Xml/XmlBaseWriter.cs",
        "src/System/Xml/XmlBinaryNodeType.cs",
        "src/System/Xml/XmlBinaryReader.cs",
        "src/System/Xml/XmlBinaryReaderSession.cs",
        "src/System/Xml/XmlBinaryWriter.cs",
        "src/System/Xml/XmlBinaryWriterSession.cs",
        "src/System/Xml/XmlBufferReader.cs",
        "src/System/Xml/XmlCanonicalWriter.cs",
        "src/System/Xml/XmlConverter.cs",
        "src/System/Xml/XmlDictionary.cs",
        "src/System/Xml/XmlDictionaryAsyncCheckWriter.cs",
        "src/System/Xml/XmlDictionaryReader.cs",
        "src/System/Xml/XmlDictionaryReaderQuotas.cs",
        "src/System/Xml/XmlDictionaryString.cs",
        "src/System/Xml/XmlDictionaryWriter.cs",
        "src/System/Xml/XmlExceptionHelper.cs",
        "src/System/Xml/XmlNodeWriter.cs",
        "src/System/Xml/XmlSigningNodeWriter.cs",
        "src/System/Xml/XmlStreamNodeWriter.cs",
        "src/System/Xml/XmlUTF8TextReader.cs",
        "src/System/Xml/XmlUTF8TextWriter.cs",
    ] + [
        "//src/libraries/Common:src/System/NotImplemented.cs",
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeTypeReference.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeTypeReferenceCollection.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeObject.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    nowarn = ["CS0649", "CS1634", "CS1691"],
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.Intrinsics:ref_System.Runtime.Intrinsics",
        "//src/libraries/System.Runtime.Loader:ref_System.Runtime.Loader",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Runtime.Serialization.Primitives:ref_System.Runtime.Serialization.Primitives",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.XmlSerializer:ref_System.Xml.XmlSerializer",
    ],
)
