exports_files([
    "Canonicalization/CanonicalizationTestHelper.cs",
    "Canonicalization/CryptoCanonicalization/AncestralNamespaceContextProviderProxy.cs",
    "Canonicalization/CryptoCanonicalization/CanonicalEncoder.cs",
    "Canonicalization/CryptoCanonicalization/CanonicalWriter.cs",
    "Canonicalization/CryptoCanonicalization/Engine.cs",
    "Canonicalization/CryptoCanonicalization/ExclusiveCanonicalNamespaceManager.cs",
    "Canonicalization/CryptoCanonicalization/Pool.cs",
    "Canonicalization/CryptoCanonicalization/SimpleXmlNodeList.cs",
    "Canonicalization/CryptoCanonicalization/XPathHelper.cs",
    "Canonicalization/CryptoCanonicalization/XmlBuffer.cs",
    "Canonicalization/TestConfigHelper.cs",
    "Canonicalization/XmlCanonicalizationTest.cs",
    "DataContractSerializer.cs",
    "DataContractSerializerStressTests.cs",
    "MyResolver.cs",
    "SerializationTestTypes/Collections.cs",
    "SerializationTestTypes/ComparisonHelper.cs",
    "SerializationTestTypes/DCRImplVariations.cs",
    "SerializationTestTypes/DCRSampleType.cs",
    "SerializationTestTypes/DCRTypeLibrary.cs",
    "SerializationTestTypes/DataContract.cs",
    "SerializationTestTypes/DataContractResolverLibrary.cs",
    "SerializationTestTypes/InheritanceCases.cs",
    "SerializationTestTypes/InheritanceObjectRef.cs",
    "SerializationTestTypes/ObjRefSample.cs",
    "SerializationTestTypes/Primitives.cs",
    "SerializationTestTypes/SampleIObjectRef.cs",
    "SerializationTestTypes/SampleTypes.cs",
    "SerializationTestTypes/SelfRefAndCycles.cs",
    "SerializationTypes.RuntimeOnly.cs",
    "SerializationTypes.cs",
    "System.Xml/XmlBinaryNodeType.cs",
    "TrimmingTests/EndToEndTest.cs",
    "XmlDictionaryReaderTests.cs",
    "XmlDictionaryWriterTest.cs",
    "XmlSerializerTests.cs",
    "XsdDataContractExporterTests/ExportOptionsTests.cs",
    "XsdDataContractExporterTests/ExporterApiTests.cs",
    "XsdDataContractExporterTests/ExporterTypesTests.cs",
    "XsdDataContractExporterTests/SchemaUtils.cs",
    "XsdDataContractExporterTests/SerializationTypes/ArrayTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/ConfigTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/ConflictingNameTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/DataContractSurrogate.cs",
    "XsdDataContractExporterTests/SerializationTypes/DataContractTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/Enums.cs",
    "XsdDataContractExporterTests/SerializationTypes/GenericTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/ISerializableTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/IXmlSerializableTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/LegacyTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/NullableTypes.cs",
    "XsdDataContractExporterTests/SerializationTypes/PartialTrust.cs",
    "XsdDataContractExporterTests/SerializationTypes/SerializableTypes.cs",
    "XsdDataContractExporterTests/SurrogateTests.cs",
    "XsdDataContractExporterTests/Types.cs",
])

load("//src/tests:live_test.bzl", "library_test")
load("@rules_dotnet//dotnet:defs.bzl", "csharp_library")
load("//:defs.bzl", "NETCOREAPP_CURRENT")

csharp_library(
    name = "SerializableAssembly",
    srcs = ["SerializationTypes.cs"],
    target_frameworks = [NETCOREAPP_CURRENT],
    deps = [
        "//src/libraries/System.Runtime.Serialization.Xml:ref_System.Runtime.Serialization.Xml",
        "//src/libraries/System.Runtime.Serialization.Json:ref_System.Runtime.Serialization.Json",
        "//src/libraries/System.Runtime.Serialization.Primitives:ref_System.Runtime.Serialization.Primitives",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.XmlSerializer:ref_System.Xml.XmlSerializer",
        "//src/libraries/System.Reflection.Metadata:ref_System.Reflection.Metadata",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries:ref_System.Runtime",
    ],
)

library_test(
    name = "System.Runtime.Serialization.Xml.Tests",
    srcs = [
        "DataContractSerializer.cs",
        "DataContractSerializerStressTests.cs",
        "MyResolver.cs",
        "SerializationTestTypes/Collections.cs",
        "SerializationTestTypes/ComparisonHelper.cs",
        "SerializationTestTypes/DCRImplVariations.cs",
        "SerializationTestTypes/DCRSampleType.cs",
        "SerializationTestTypes/DCRTypeLibrary.cs",
        "SerializationTestTypes/DataContract.cs",
        "SerializationTestTypes/DataContractResolverLibrary.cs",
        "SerializationTestTypes/InheritanceCases.cs",
        "SerializationTestTypes/InheritanceObjectRef.cs",
        "SerializationTestTypes/ObjRefSample.cs",
        "SerializationTestTypes/Primitives.cs",
        "SerializationTestTypes/SampleIObjectRef.cs",
        "SerializationTestTypes/SampleTypes.cs",
        "SerializationTestTypes/SelfRefAndCycles.cs",
        "SerializationTypes.RuntimeOnly.cs",
        "SerializationTypes.cs",
        "System.Xml/XmlBinaryNodeType.cs",
        "XmlDictionaryReaderTests.cs",
        "XmlDictionaryWriterTest.cs",
        "XmlSerializerTests.cs",
    ] + [
        "//src/libraries/Common/tests:System/IO/TempFile.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/DataContractSerializerHelper.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/Utils.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Serialization.Xml:ref_System.Runtime.Serialization.Xml",
        "//src/libraries/System.Runtime.Serialization.Json:ref_System.Runtime.Serialization.Json",
        "//src/libraries/System.Runtime.Serialization.Primitives:ref_System.Runtime.Serialization.Primitives",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.XmlSerializer:ref_System.Xml.XmlSerializer",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries/System.Reflection.Metadata:ref_System.Reflection.Metadata",
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.CodeDom:ref_System.CodeDom",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Diagnostics.TraceSource:ref_System.Diagnostics.TraceSource",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
    data = [":SerializableAssembly"],
)