load("@rules_cc//cc:defs.bzl", "cc_library", "cc_shared_library")

cc_library(
    name = "System.Native_lib",
    srcs = [
        "entrypoints.c",
        "pal_autoreleasepool.c",
        "pal_console.c",
        "pal_datetime.c",
        "pal_dynamicload.c",
        "pal_environment.c",
        "pal_errno.c",
        "pal_interfaceaddresses.c",
        "pal_io.c",
        "pal_iossupportversion.c",
        "pal_log.c",
        "pal_maphardwaretype.c",
        "pal_memory.c",
        "pal_mount.c",
        "pal_networkchange.c",
        "pal_networking.c",
        "pal_networkstatistics.c",
        "pal_process.c",
        "pal_random.c",
        "pal_runtimeinformation.c",
        "pal_searchpath.c",
        "pal_signal.c",
        "pal_string.c",
        "pal_sysctl.c",
        "pal_tcpstate.c",
        "pal_threading.c",
        "pal_time.c",
        "pal_uid.c",
    ] + glob(["*.h"]),
    copts = [
        "-std=gnu99",
        "-Wno-declaration-after-statement",
        "-Isrc/native",
        "-Isrc/native/libs/Common",
        "-Isrc/native/libs/bazel",
    ],
    defines = [
        "HAS_CONSOLE_SIGNALS",
        "_FILE_OFFSET_BITS=64",
        "_GNU_SOURCE",
    ],
    linkopts = ["-lrt"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/native/libs:common",
        "//src/native/minipal",
    ],
)

cc_shared_library(
    name = "System.Native",
    shared_lib_name = "libSystem.Native.so",
    visibility = ["//visibility:public"],
    deps = [":System.Native_lib"],
)
