load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.ComponentModel.Annotations",
    srcs = [
        "ref/System.ComponentModel.Annotations.cs",
    ],
    deps = [
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.ComponentModel.Annotations",
    srcs = [
        "src/System/ComponentModel/DataAnnotations/AllowedValuesAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/AssociatedMetadataTypeTypeDescriptionProvider.cs",
        "src/System/ComponentModel/DataAnnotations/AssociatedMetadataTypeTypeDescriptor.cs",
        "src/System/ComponentModel/DataAnnotations/AssociationAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Base64StringAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/CompareAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/ConcurrencyCheckAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/CreditCardAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/CustomValidationAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/DataType.cs",
        "src/System/ComponentModel/DataAnnotations/DataTypeAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/DeniedValuesAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/DisplayAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/DisplayColumnAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/DisplayFormatAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/EditableAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/EnumDataTypeAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/FileExtensionsAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/FilterUIHintAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/IValidatableObject.cs",
        "src/System/ComponentModel/DataAnnotations/KeyAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/LengthAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/LocalizableString.cs",
        "src/System/ComponentModel/DataAnnotations/MaxLengthAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/MetadataPropertyDescriptorWrapper.cs",
        "src/System/ComponentModel/DataAnnotations/MetadataTypeAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/MinLengthAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/PhoneAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/RangeAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/RegularExpressionAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/RequiredAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/ScaffoldColumnAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/ColumnAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/ComplexTypeAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/DatabaseGeneratedAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/DatabaseGeneratedOption.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/ForeignKeyAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/InversePropertyAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/NotMappedAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/Schema/TableAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/StringLengthAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/TimestampAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/UIHintAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/UrlAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/ValidationAttribute.cs",
        "src/System/ComponentModel/DataAnnotations/ValidationAttributeStore.cs",
        "src/System/ComponentModel/DataAnnotations/ValidationContext.cs",
        "src/System/ComponentModel/DataAnnotations/ValidationException.cs",
        "src/System/ComponentModel/DataAnnotations/ValidationResult.cs",
        "src/System/ComponentModel/DataAnnotations/Validator.cs",
    ] + [
        # Common sources
        "//src/libraries/Common:src/System/NotImplemented.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    deps = [
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
