<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetCoreAppToolCurrent)</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <DisableImplicitFrameworkReferences>false</DisableImplicitFrameworkReferences>
    <AddAdditionalExplicitAssemblyReferences>true</AddAdditionalExplicitAssemblyReferences>
    <AssemblyName>ManagedGC.Foundation.Tests</AssemblyName>
    <SignAssembly>false</SignAssembly>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.XUnitExtensions" Version="$(MicrosoftDotNetXUnitExtensionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="GCFoundationTests.cs" />
    <Compile Include="../src/Internal/Runtime/GarbageCollection/GCEventEnums.cs" Link="GCEventEnums.cs" />
    <Compile Include="../src/Internal/Runtime/GarbageCollection/GCEventStatus.cs" Link="GCEventStatus.cs" />
    <Compile Include="../src/Internal/Runtime/GarbageCollection/IntroSort.cs" Link="IntroSort.cs" />
  </ItemGroup>
</Project>
