load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Private.Uri.Functional.Tests",
    srcs = [
        "AppxUriValue.cs",
        "EscapeUnescapeIriTests.cs",
        "IdnCheckHostNameTest.cs",
        "IdnDnsSafeHostTest.cs",
        "IdnHostNameValidationTest.cs",
        "IriEncodingDecodingTests.cs",
        "IriRelativeFileResolutionTest.cs",
        "IriTest.cs",
        "UncTest.cs",
        "UriBuilderParameterTest.cs",
        "UriBuilderRefreshTest.cs",
        "UriBuilderTests.cs",
        "UriCreationOptionsTest.cs",
        "UriEscapingTest.cs",
        "UriGetComponentsTest.cs",
        "UriIpHostTest.cs",
        "UriIsWellFormedUriStringTest.cs",
        "UriMailToTest.cs",
        "UriParameterValidationTest.cs",
        "UriParserTest.cs",
        "UriRelativeResolutionTest.cs",
        "UriTests.cs",
        "WebSocketsUriParserTest.cs",
    ],
    deps = [
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = ["SYSLIB0013"],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
