load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.ComponentModel.Annotations.Tests",
    srcs = [
        "System/ComponentModel/DataAnnotations/AllowedValuesAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/AssociatedMetadataTypeTypeDescriptionProviderTests.cs",
        "System/ComponentModel/DataAnnotations/AssociationAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/Base64StringAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/CompareAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/CreditCardAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/CustomValidationAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/DataTypeAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/DeniedValuesAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/DisplayAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/DisplayColumnAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/DisplayFormatAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/DisplayFormatAttributeTests.netcoreapp.cs",
        "System/ComponentModel/DataAnnotations/EditableAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/EmailAddressAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/EnumDataTypeAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/FileExtensionsAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/FilterUIHintAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/LengthAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/MaxLengthAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/MetadataTypeAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/MinLengthAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/PhoneAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/RangeAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/RegularExpressionAttributeTests.Core.cs",
        "System/ComponentModel/DataAnnotations/RegularExpressionAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/RequiredAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/ScaffoldColumnAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/Schema/ColumnAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/Schema/DatabaseGeneratedAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/Schema/ForeignKeyAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/Schema/InversePropertyAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/Schema/TableAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/StringLengthAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/UIHintAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/UrlAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/ValidationAttributeTestBase.cs",
        "System/ComponentModel/DataAnnotations/ValidationAttributeTests.cs",
        "System/ComponentModel/DataAnnotations/ValidationContextTests.cs",
        "System/ComponentModel/DataAnnotations/ValidationExceptionTests.cs",
        "System/ComponentModel/DataAnnotations/ValidationResultTests.cs",
    ],
    deps = [
        "//src/libraries/System.ComponentModel.Annotations:ref_System.ComponentModel.Annotations",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nullable = "disable",
    nowarn = ["nullable"],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
