load("//:defs.bzl", "GENFACADES_REPO", "csharp_binary")
load("@rules_dotnet//dotnet:defs.bzl", "import_library")

import_library(
    name = "GenFacadesNuGetFiles",
    library_name = "GenFacadesDlls",
    refs = [
        "@{}//:tools/net/Microsoft.DotNet.GenFacades.dll".format(GENFACADES_REPO),
        "@{}//:tools/net/Microsoft.CodeAnalysis.dll".format(GENFACADES_REPO),
        "@{}//:tools/net/Microsoft.CodeAnalysis.CSharp.dll".format(GENFACADES_REPO),
    ],
    libs = [
        "@{}//:tools/net/Microsoft.DotNet.GenFacades.dll".format(GENFACADES_REPO),
        "@{}//:tools/net/Microsoft.CodeAnalysis.dll".format(GENFACADES_REPO),
        "@{}//:tools/net/Microsoft.CodeAnalysis.CSharp.dll".format(GENFACADES_REPO),
    ],
)

csharp_binary(
    name = "GenNotSupportedSource",
    srcs = glob(["*.cs"]),
    deps = [
        ":GenFacadesNuGetFiles",
        "@paket.main//microsoft.build.framework",
        "@paket.main//microsoft.build.utilities.core",
    ],
    nullable = "enable",
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
)
