load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN", "impl_assembly")

impl_assembly(
    name = "impl_System.Composition.Hosting",
    srcs = glob(["src/**/*.cs"]),
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Linq.Expressions:ref_System.Linq.Expressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Composition.Runtime:impl_System.Composition.Runtime",
    ],
    resx_file = "src/Resources/Strings.resx",
    nullable = "disable",
    nowarn = MULTITARGET_NOWARN + ["CP0003", "nullable", "CS1591"],
    is_trimmable = False,
    is_aot_compatible = False,
)
