load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN", "impl_assembly")

# For net10.0, this library is a pure set of type forwarders (Index,
# Range, Utf8, Base64Url) since those types already exist in the
# framework.
impl_assembly(
    name = "impl_Microsoft.Bcl.Memory",
    nowarn = MULTITARGET_NOWARN + ["CP0003"],
    srcs = [
        "src/Microsoft.Bcl.Memory.Forwards.cs",
    ],
    defines = ["MICROSOFT_BCL_MEMORY"],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
    exclude_sr = True,
)
