load("@rules_cc//cc:defs.bzl", "cc_library")

# Common headers shared across native libraries

cc_library(
    name = "common",
    srcs = [],
    hdrs = [
        "Common/pal_atomic.h",
        "Common/pal_compiler.h",
        "Common/pal_error_common.h",
        "Common/pal_io_common.h",
        "Common/pal_networking_common.h",
        "Common/pal_safecrt.h",
        "Common/pal_ssl_types.h",
        "Common/pal_types.h",
        "Common/pal_utilities.h",
        "Common/pal_x509_types.h",
    ] + select({
        "@platforms//os:macos": ["//src/native/libs/bazel:darwin-arm64/pal_config.h"],
        "//conditions:default": ["//src/native/libs/bazel:linux-glibc-x64/pal_config.h"],
    }),
    includes = ["Common"] + select({
        "@platforms//os:macos": ["bazel/darwin-arm64"],
        "//conditions:default": ["bazel/linux-glibc-x64"],
    }),
    visibility = ["//src/native:__subpackages__"],
)
