load("@rules_cc//cc:defs.bzl", "cc_library")

# Common headers shared across native libraries

cc_library(
    name = "common",
    srcs = [],
    hdrs = glob(["Common/*.h"]) + [
        "//src/native/libs/bazel:pal_config.h",
    ],
    includes = [
        "Common",
        "bazel",
    ],
    visibility = ["//src/native:__subpackages__"],
)
