load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "RayTracer",
    srcs = [
        "RayTracerBench.cs",
        "Camera.cs",
        "Color.cs",
        "ISect.cs",
        "Light.cs",
        "ObjectPool.cs",
        "Plane.cs",
        "ProducerConsumerCollectionBase.cs",
        "Ray.cs",
        "Raytracer.cs",
        "Scene.cs",
        "SceneObject.cs",
        "Sphere.cs",
        "Surface.cs",
        "Surfaces.cs",
        "Vector.cs",
    ],
    debug_type = "pdbonly",
    optimize = True,
)
