load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Composition.Hosting.Tests",
    srcs = glob(["**/*.cs"]),
    deps = [
        "//src/libraries/System.Composition.Hosting:impl_System.Composition.Hosting",
        "//src/libraries/System.Composition.Runtime:impl_System.Composition.Runtime",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
