name: Bazel Build & Test

on:
  push:
    branches: [ bazel, bazel-mac ]
  pull_request:
    branches: [ bazel, bazel-mac ]

jobs:
  build-macos:
    name: macOS release
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Mount Bazel cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel-disk
          key: bazel-macos-release-${{ hashFiles('MODULE.bazel', 'MODULE.bazel.lock', '.bazelrc') }}-${{ github.sha }}
          restore-keys: |
            bazel-macos-release-${{ hashFiles('MODULE.bazel', 'MODULE.bazel.lock', '.bazelrc') }}-
            bazel-macos-release-

      - name: Build
        run: bazel build //... --config=clr_release --disk_cache=~/.cache/bazel-disk

      - name: Test
        run: bazel test //... --config=clr_release --disk_cache=~/.cache/bazel-disk --test_output=errors
